#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Contributors to the RISCV UnifiedDB <https://github.com/riscv/riscv-unified-db>
# SPDX-License-Identifier: BSD-3-Clause-Clear
#MISE description="Regression task translated from regress-cpp-unit"

set -e

# Step 1: Run cpp unit tests
(
  ./do test:cpp_hart CONFIG=rv64 JOBS=4 BUILD_TYPE=debug
)
