# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# typed: false
# frozen_string_literal: true

require "yaml"

regress_template_yaml = YAML.load_file(Pathname.new(__dir__) / "regress-gh-template.yaml")
# make a deep copy
regress_yaml = YAML.load(YAML.dump(regress_template_yaml))
tests = YAML.load_file(Pathname.new(__dir__) / "regress-tests.yaml")

tests["tests"].each do |test_name, test_data|
  regress_yaml["jobs"][test_name] = {
    "runs-on" => "ubuntu-latest",
    "needs" => "build-container",
    "steps" => [
      {
        "name" => "Clone Github Repo Action",
        "uses" => regress_yaml["jobs"]["build-container"]["steps"][0]["uses"]
      },
      {
        "name" => "Download docker image",
        "uses" => regress_yaml["jobs"]["never-runs"]["steps"][0]["uses"],
        "with" => {
          "name" => "docker_image",
          "path" => "${{ runner.temp }}"
        }
      },
      {
        "name" => "Load image",
        "run" => "docker load --input ${{ runner.temp }}/docker_image.tar"
      }
    ]
  }

  if test_data.key?("env")
    regress_yaml["jobs"][test_name]["env"] = test_data["env"]
  end
  if test_data.key?("strategy")
    regress_yaml["jobs"][test_name]["strategy"] = test_data["strategy"]
  end
  if test_data.key?("pre")
    regress_yaml["jobs"][test_name]["steps"].concat(test_data["pre"])
  end
  regress_yaml["jobs"][test_name]["steps"].concat(test_data["test"])
  if test_data.key?("post")
    regress_yaml["jobs"][test_name]["steps"].concat(test_data["post"])
  end
end

regress_yaml["jobs"]["regress-complete"] = {
  "runs-on" => "ubuntu-latest",
  "needs" => tests["tests"].keys + (regress_template_yaml["jobs"].keys - ["build-container", "never-runs"]),
  "steps" => [
    {
      "name" => "exit success",
      "run" => "exit 0"
    }
  ]
}

f = <<~FILE.strip
# This file was generated by `./bin/ruby tools/test/gen_regress.rb`
# DO NOT EDIT
# Instead, edit `tools/test/regress-tests.yaml` (preferred) or `tools/test/regress-gh-template.yaml`

#{YAML.dump(regress_yaml, line_width: 100)}
FILE
File.write (Pathname.new(__dir__) / ".." / ".." / ".github" / "workflows" / "regress.yml"), "#{f}\n"
