# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `activesupport` gem.
# Please instead update this file by running `bin/tapioca gem activesupport`.


module ActiveSupport
  extend ::ActiveSupport::LazyLoadHooks

  def parse_json_times; end
  def parse_json_times=(val); end

  class << self
    def escape_html_entities_in_json(*_arg0, **_arg1, &_arg2); end
    def escape_html_entities_in_json=(arg); end
    def escape_js_separators_in_json(*_arg0, **_arg1, &_arg2); end
    def escape_js_separators_in_json=(arg); end
    def json_encoder(*_arg0, **_arg1, &_arg2); end
    def json_encoder=(arg); end
    def parse_json_times; end
    def parse_json_times=(val); end
    def time_precision(*_arg0, **_arg1, &_arg2); end
    def time_precision=(arg); end
    def use_standard_json_time_format(*_arg0, **_arg1, &_arg2); end
    def use_standard_json_time_format=(arg); end
  end
end

class ActiveSupport::ArrayInquirer < ::Array
  def any?(*candidates); end

  private

  def method_missing(name, *_arg1, **_arg2, &_arg3); end
  def respond_to_missing?(name, include_private = T.unsafe(nil)); end
end

module ActiveSupport::BigDecimalWithDefaultFormat
  def to_s(format = T.unsafe(nil)); end
end

module ActiveSupport::CoreExt; end

module ActiveSupport::CoreExt::ERBUtil
  def h(s); end
  def html_escape(s); end
  def unwrapped_html_escape(s); end
end

module ActiveSupport::CoreExt::ERBUtilPrivate
  include ::ActiveSupport::CoreExt::ERBUtil

  private

  def h(s); end
  def html_escape(s); end
  def unwrapped_html_escape(s); end
end

module ActiveSupport::DeepMergeable
  def deep_merge(other, &block); end
  def deep_merge!(other, &block); end
  def deep_merge?(other); end
end

module ActiveSupport::Delegation
  class << self
    def generate(owner, methods, location: T.unsafe(nil), to: T.unsafe(nil), prefix: T.unsafe(nil), allow_nil: T.unsafe(nil), nilable: T.unsafe(nil), private: T.unsafe(nil), as: T.unsafe(nil), signature: T.unsafe(nil)); end
    def generate_method_missing(owner, target, allow_nil: T.unsafe(nil)); end
  end
end

ActiveSupport::Delegation::RESERVED_METHOD_NAMES = T.let(T.unsafe(nil), Set)
ActiveSupport::Delegation::RUBY_RESERVED_KEYWORDS = T.let(T.unsafe(nil), Array)

class ActiveSupport::DelegationError < ::NoMethodError
  class << self
    def nil_target(method_name, target); end
  end
end

class ActiveSupport::Duration
  def initialize(value, parts, variable = T.unsafe(nil)); end

  def %(other); end
  def *(other); end
  def +(other); end
  def +@; end
  def -(other); end
  def -@; end
  def /(other); end
  def <=>(other); end
  def ==(other); end
  def _parts; end
  def abs(&_arg0); end
  def after(time = T.unsafe(nil)); end
  def ago(time = T.unsafe(nil)); end
  def as_json(options = T.unsafe(nil)); end
  def before(time = T.unsafe(nil)); end
  def coerce(other); end
  def encode_with(coder); end
  def eql?(other); end
  def from_now(time = T.unsafe(nil)); end
  def hash; end
  def in_days; end
  def in_hours; end
  def in_minutes; end
  def in_months; end
  def in_seconds; end
  def in_weeks; end
  def in_years; end
  def init_with(coder); end
  def inspect; end
  def instance_of?(klass); end
  def is_a?(klass); end
  def iso8601(precision: T.unsafe(nil)); end
  def kind_of?(klass); end
  def negative?(&_arg0); end
  def parts; end
  def positive?(&_arg0); end
  def since(time = T.unsafe(nil)); end
  def to_f(&_arg0); end
  def to_i; end
  def to_s; end
  def until(time = T.unsafe(nil)); end
  def value; end
  def variable?; end
  def zero?(&_arg0); end

  private

  def method_missing(*_arg0, **_arg1, &_arg2); end
  def raise_type_error(other); end
  def respond_to_missing?(method, _); end
  def sum(sign, time = T.unsafe(nil)); end

  class << self
    def ===(other); end
    def build(value); end
    def days(value); end
    def hours(value); end
    def minutes(value); end
    def months(value); end
    def parse(iso8601duration); end
    def seconds(value); end
    def weeks(value); end
    def years(value); end

    private

    def calculate_total_seconds(parts); end
  end
end

class ActiveSupport::Duration::ISO8601Parser
  def initialize(string); end

  def mode; end
  def mode=(_arg0); end
  def parse!; end
  def parts; end
  def scanner; end
  def sign; end
  def sign=(_arg0); end

  private

  def finished?; end
  def number; end
  def raise_parsing_error(reason = T.unsafe(nil)); end
  def scan(pattern); end
  def validate!; end
end

ActiveSupport::Duration::ISO8601Parser::COMMA = T.let(T.unsafe(nil), String)
ActiveSupport::Duration::ISO8601Parser::DATE_COMPONENT = T.let(T.unsafe(nil), Regexp)
ActiveSupport::Duration::ISO8601Parser::DATE_COMPONENTS = T.let(T.unsafe(nil), Array)
ActiveSupport::Duration::ISO8601Parser::DATE_MARKER = T.let(T.unsafe(nil), Regexp)
ActiveSupport::Duration::ISO8601Parser::DATE_TO_PART = T.let(T.unsafe(nil), Hash)
ActiveSupport::Duration::ISO8601Parser::PERIOD = T.let(T.unsafe(nil), String)
ActiveSupport::Duration::ISO8601Parser::PERIOD_OR_COMMA = T.let(T.unsafe(nil), Regexp)
class ActiveSupport::Duration::ISO8601Parser::ParsingError < ::ArgumentError; end
ActiveSupport::Duration::ISO8601Parser::SIGN_MARKER = T.let(T.unsafe(nil), Regexp)
ActiveSupport::Duration::ISO8601Parser::TIME_COMPONENT = T.let(T.unsafe(nil), Regexp)
ActiveSupport::Duration::ISO8601Parser::TIME_COMPONENTS = T.let(T.unsafe(nil), Array)
ActiveSupport::Duration::ISO8601Parser::TIME_MARKER = T.let(T.unsafe(nil), Regexp)
ActiveSupport::Duration::ISO8601Parser::TIME_TO_PART = T.let(T.unsafe(nil), Hash)

class ActiveSupport::Duration::ISO8601Serializer
  def initialize(duration, precision: T.unsafe(nil)); end

  def serialize; end

  private

  def format_seconds(seconds); end
  def normalize; end
  def week_mixed_with_date?(parts); end
end

ActiveSupport::Duration::ISO8601Serializer::DATE_COMPONENTS = T.let(T.unsafe(nil), Array)
ActiveSupport::Duration::PARTS = T.let(T.unsafe(nil), Array)
ActiveSupport::Duration::PARTS_IN_SECONDS = T.let(T.unsafe(nil), Hash)
ActiveSupport::Duration::SECONDS_PER_DAY = T.let(T.unsafe(nil), Integer)
ActiveSupport::Duration::SECONDS_PER_HOUR = T.let(T.unsafe(nil), Integer)
ActiveSupport::Duration::SECONDS_PER_MINUTE = T.let(T.unsafe(nil), Integer)
ActiveSupport::Duration::SECONDS_PER_MONTH = T.let(T.unsafe(nil), Integer)
ActiveSupport::Duration::SECONDS_PER_WEEK = T.let(T.unsafe(nil), Integer)
ActiveSupport::Duration::SECONDS_PER_YEAR = T.let(T.unsafe(nil), Integer)

class ActiveSupport::Duration::Scalar < ::Numeric
  def initialize(value); end

  def %(other); end
  def *(other); end
  def +(other); end
  def -(other); end
  def -@; end
  def /(other); end
  def <=>(other); end
  def coerce(other); end
  def to_f(*_arg0, **_arg1, &_arg2); end
  def to_i(*_arg0, **_arg1, &_arg2); end
  def to_s(*_arg0, **_arg1, &_arg2); end
  def value; end
  def variable?; end

  private

  def calculate(op, other); end
  def raise_type_error(other); end
end

ActiveSupport::Duration::VARIABLE_PARTS = T.let(T.unsafe(nil), Array)

module ActiveSupport::Inflector
  extend ::ActiveSupport::Inflector

  def camelize(term, uppercase_first_letter = T.unsafe(nil)); end
  def classify(table_name); end
  def constantize(camel_cased_word); end
  def dasherize(underscored_word); end
  def deconstantize(path); end
  def demodulize(path); end
  def downcase_first(string); end
  def foreign_key(class_name, separate_class_name_and_id_with_underscore = T.unsafe(nil)); end
  def humanize(lower_case_and_underscored_word, capitalize: T.unsafe(nil), keep_id_suffix: T.unsafe(nil)); end
  def inflections(locale = T.unsafe(nil)); end
  def ordinal(number); end
  def ordinalize(number); end
  def parameterize(string, separator: T.unsafe(nil), preserve_case: T.unsafe(nil), locale: T.unsafe(nil)); end
  def pluralize(word, locale = T.unsafe(nil)); end
  def safe_constantize(camel_cased_word); end
  def singularize(word, locale = T.unsafe(nil)); end
  def tableize(class_name); end
  def titleize(word, keep_id_suffix: T.unsafe(nil)); end
  def transliterate(string, replacement = T.unsafe(nil), locale: T.unsafe(nil)); end
  def underscore(camel_cased_word); end
  def upcase_first(string); end

  private

  def apply_inflections(word, rules, locale = T.unsafe(nil)); end
  def const_regexp(camel_cased_word); end
end

ActiveSupport::Inflector::ALLOWED_ENCODINGS_FOR_TRANSLITERATE = T.let(T.unsafe(nil), Array)

class ActiveSupport::Inflector::Inflections
  def initialize; end

  def acronym(word); end
  def acronyms; end
  def acronyms_camelize_regex; end
  def acronyms_underscore_regex; end
  def clear(scope = T.unsafe(nil)); end
  def human(rule, replacement); end
  def humans; end
  def irregular(singular, plural); end
  def plural(rule, replacement); end
  def plurals; end
  def singular(rule, replacement); end
  def singulars; end
  def uncountable(*words); end
  def uncountables; end

  private

  def define_acronym_regex_patterns; end
  def initialize_dup(orig); end

  class << self
    def instance(locale = T.unsafe(nil)); end
    def instance_or_fallback(locale); end
  end
end

class ActiveSupport::Inflector::Inflections::Uncountables
  include ::Enumerable

  def initialize; end

  def <<(word); end
  def ==(arg); end
  def add(words); end
  def delete(entry); end
  def each(*_arg0, **_arg1, &_arg2); end
  def empty?(*_arg0, **_arg1, &_arg2); end
  def flatten; end
  def pop(*_arg0, **_arg1, &_arg2); end
  def to_a(*_arg0, **_arg1, &_arg2); end
  def to_ary(*_arg0, **_arg1, &_arg2); end
  def to_s(*_arg0, **_arg1, &_arg2); end
  def uncountable?(str); end
end

module ActiveSupport::JSON
  class << self
    def decode(json, options = T.unsafe(nil)); end
    def dump(value, options = T.unsafe(nil)); end
    def encode(value, options = T.unsafe(nil)); end
    def load(json, options = T.unsafe(nil)); end
    def parse_error; end

    private

    def convert_dates_from(data); end
  end
end

ActiveSupport::JSON::DATETIME_REGEX = T.let(T.unsafe(nil), Regexp)
ActiveSupport::JSON::DATE_REGEX = T.let(T.unsafe(nil), Regexp)

module ActiveSupport::JSON::Encoding
  class << self
    def encode_without_escape(value); end
    def encode_without_options(value); end
    def escape_html_entities_in_json; end
    def escape_html_entities_in_json=(_arg0); end
    def escape_js_separators_in_json; end
    def escape_js_separators_in_json=(_arg0); end
    def json_encoder; end
    def json_encoder=(encoder); end
    def time_precision; end
    def time_precision=(_arg0); end
    def use_standard_json_time_format; end
    def use_standard_json_time_format=(_arg0); end
  end
end

ActiveSupport::JSON::Encoding::ESCAPED_CHARS = T.let(T.unsafe(nil), Hash)
ActiveSupport::JSON::Encoding::FULL_ESCAPE_REGEX = T.let(T.unsafe(nil), Regexp)
ActiveSupport::JSON::Encoding::HTML_ENTITIES_REGEX = T.let(T.unsafe(nil), Regexp)

class ActiveSupport::JSON::Encoding::JSONGemCoderEncoder
  def initialize(options = T.unsafe(nil)); end

  def encode(value); end
end

ActiveSupport::JSON::Encoding::JSONGemCoderEncoder::CODER = T.let(T.unsafe(nil), JSON::Coder)
ActiveSupport::JSON::Encoding::JSONGemCoderEncoder::JSON_NATIVE_TYPES = T.let(T.unsafe(nil), Array)

class ActiveSupport::JSON::Encoding::JSONGemEncoder
  def initialize(options = T.unsafe(nil)); end

  def encode(value); end
  def options; end

  private

  def jsonify(value); end
  def stringify(jsonified); end
end

ActiveSupport::JSON::Encoding::JS_SEPARATORS_REGEX = T.let(T.unsafe(nil), Regexp)
ActiveSupport::JSON::Encoding::U2028 = T.let(T.unsafe(nil), String)
ActiveSupport::JSON::Encoding::U2029 = T.let(T.unsafe(nil), String)

module ActiveSupport::LazyLoadHooks
  def on_load(name, options = T.unsafe(nil), &block); end
  def run_load_hooks(name, base = T.unsafe(nil)); end

  private

  def execute_hook(name, base, options, block); end
  def with_execution_control(name, block, once); end

  class << self
    def extended(base); end
  end
end

module ActiveSupport::Multibyte
  class << self
    def proxy_class; end
    def proxy_class=(klass); end
  end
end

class ActiveSupport::Multibyte::Chars
  include ::Comparable

  def initialize(string, deprecation: T.unsafe(nil)); end

  def <=>(*_arg0, **_arg1, &_arg2); end
  def =~(*_arg0, **_arg1, &_arg2); end
  def acts_like_string?(*_arg0, **_arg1, &_arg2); end
  def as_json(options = T.unsafe(nil)); end
  def compose; end
  def decompose; end
  def grapheme_length; end
  def limit(limit); end
  def match?(*_arg0, **_arg1, &_arg2); end
  def method_missing(method, *_arg1, **_arg2, &_arg3); end
  def reverse; end
  def reverse!(*args); end
  def slice!(*args); end
  def split(*args); end
  def tidy_bytes(force = T.unsafe(nil)); end
  def tidy_bytes!(*args); end
  def titlecase; end
  def titleize; end
  def to_s; end
  def to_str; end
  def wrapped_string; end

  private

  def chars(string); end
  def respond_to_missing?(method, include_private); end
end

module ActiveSupport::Multibyte::Unicode
  extend ::ActiveSupport::Multibyte::Unicode

  def compose(codepoints); end
  def decompose(type, codepoints); end
  def tidy_bytes(string, force = T.unsafe(nil)); end

  private

  def recode_windows1252_chars(string); end
end

ActiveSupport::Multibyte::Unicode::UNICODE_VERSION = T.let(T.unsafe(nil), String)

class ActiveSupport::SafeBuffer < ::String
  def initialize(_str = T.unsafe(nil)); end

  def %(args); end
  def *(_); end
  def +(other); end
  def <<(value); end
  def [](*args); end
  def []=(arg1, arg2, arg3 = T.unsafe(nil)); end
  def as_json(*_arg0); end
  def bytesplice(*args, value); end
  def capitalize(*args, &block); end
  def capitalize!(*args); end
  def chomp(*args, &block); end
  def chomp!(*args); end
  def chop(*args, &block); end
  def chop!(*args); end
  def chr; end
  def concat(value); end
  def delete(*args, &block); end
  def delete!(*args); end
  def delete_prefix(*args, &block); end
  def delete_prefix!(*args); end
  def delete_suffix(*args, &block); end
  def delete_suffix!(*args); end
  def downcase(*args, &block); end
  def downcase!(*args); end
  def encode_with(coder); end
  def gsub(*args, &block); end
  def gsub!(*args, &block); end
  def html_safe?; end
  def insert(index, value); end
  def lstrip(*args, &block); end
  def lstrip!(*args); end
  def next(*args, &block); end
  def next!(*args); end
  def prepend(value); end
  def replace(value); end
  def reverse(*args, &block); end
  def reverse!(*args); end
  def rstrip(*args, &block); end
  def rstrip!(*args); end
  def safe_concat(value); end
  def scrub(*args, &block); end
  def scrub!(*args); end
  def slice(*args); end
  def slice!(*args); end
  def squeeze(*args, &block); end
  def squeeze!(*args); end
  def strip(*args, &block); end
  def strip!(*args); end
  def sub(*args, &block); end
  def sub!(*args, &block); end
  def succ(*args, &block); end
  def succ!(*args); end
  def swapcase(*args, &block); end
  def swapcase!(*args); end
  def to_param; end
  def to_s; end
  def tr(*args, &block); end
  def tr!(*args); end
  def tr_s(*args, &block); end
  def tr_s!(*args); end
  def unicode_normalize(*args, &block); end
  def unicode_normalize!(*args); end
  def upcase(*args, &block); end
  def upcase!(*args); end

  protected

  def mark_unsafe!; end

  private

  def explicit_html_escape_interpolated_argument(arg); end
  def implicit_html_escape_interpolated_argument(arg); end
  def initialize_copy(other); end
  def original_concat(*_arg0); end
  def set_block_back_references(block, match_data); end
  def string_into_safe_buffer(new_string, is_html_safe); end
end

class ActiveSupport::SafeBuffer::SafeConcatError < ::StandardError
  def initialize; end
end

ActiveSupport::SafeBuffer::UNSAFE_STRING_METHODS = T.let(T.unsafe(nil), Array)
ActiveSupport::SafeBuffer::UNSAFE_STRING_METHODS_WITH_BACKREF = T.let(T.unsafe(nil), Array)

class ActiveSupport::StringInquirer < ::String
  private

  def method_missing(method_name, *_arg1, **_arg2, &_arg3); end
  def respond_to_missing?(method_name, include_private = T.unsafe(nil)); end
end

module ActiveSupport::Testing; end

module ActiveSupport::Testing::ErrorReporterAssertions
  def assert_error_reported(error_class = T.unsafe(nil), &block); end
  def assert_no_error_reported(&block); end
  def capture_error_reports(error_class = T.unsafe(nil), &block); end
end

module ActiveSupport::Testing::ErrorReporterAssertions::ErrorCollector
  class << self
    def record; end
    def report(error, **kwargs); end

    private

    def subscribe; end
  end
end

class ActiveSupport::Testing::ErrorReporterAssertions::ErrorCollector::Report < ::Struct
  def context; end
  def context=(_); end
  def error; end
  def error=(_); end
  def handled; end
  def handled=(_); end
  def handled?; end
  def severity; end
  def severity=(_); end
  def source; end
  def source=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

class ActiveSupport::TimeWithZone
  include ::DateAndTime::Compatibility
  include ::Comparable

  def initialize(utc_time, time_zone, local_time = T.unsafe(nil), period = T.unsafe(nil)); end

  def +(other); end
  def -(other); end
  def <=>(other); end
  def acts_like_time?; end
  def advance(options); end
  def after?(_arg0); end
  def ago(other); end
  def as_json(options = T.unsafe(nil)); end
  def before?(_arg0); end
  def between?(min, max); end
  def blank?; end
  def change(options); end
  def comparable_time; end
  def day; end
  def dst?; end
  def encode_with(coder); end
  def eql?(other); end
  def formatted_offset(colon = T.unsafe(nil), alternate_utc_string = T.unsafe(nil)); end
  def freeze; end
  def future?; end
  def getgm; end
  def getlocal(utc_offset = T.unsafe(nil)); end
  def getutc; end
  def gmt?; end
  def gmt_offset; end
  def gmtime; end
  def gmtoff; end
  def hash; end
  def hour; end
  def httpdate; end
  def in(other); end
  def in_time_zone(new_zone = T.unsafe(nil)); end
  def init_with(coder); end
  def inspect; end
  def is_a?(klass); end
  def isdst; end
  def iso8601(fraction_digits = T.unsafe(nil)); end
  def kind_of?(klass); end
  def localtime(utc_offset = T.unsafe(nil)); end
  def marshal_dump; end
  def marshal_load(variables); end
  def mday; end
  def method_missing(*_arg0, **_arg1, &_arg2); end
  def min; end
  def mon; end
  def month; end
  def next_day?; end
  def nsec; end
  def past?; end
  def period; end
  def present?; end
  def prev_day?; end
  def respond_to?(sym, include_priv = T.unsafe(nil)); end
  def rfc2822; end
  def rfc3339(fraction_digits = T.unsafe(nil)); end
  def rfc822; end
  def sec; end
  def since(other); end
  def strftime(format); end
  def time; end
  def time_zone; end
  def to_a; end
  def to_date; end
  def to_datetime; end
  def to_f; end
  def to_formatted_s(format = T.unsafe(nil)); end
  def to_fs(format = T.unsafe(nil)); end
  def to_i; end
  def to_r; end
  def to_s; end
  def to_time; end
  def today?; end
  def tomorrow?; end
  def tv_sec; end
  def usec; end
  def utc; end
  def utc?; end
  def utc_offset; end
  def wday; end
  def xmlschema(fraction_digits = T.unsafe(nil)); end
  def yday; end
  def year; end
  def yesterday?; end
  def zone; end

  private

  def duration_of_variable_length?(obj); end
  def get_period_and_ensure_valid_local_time(period); end
  def incorporate_utc_offset(time, offset); end
  def respond_to_missing?(sym, include_priv); end
  def transfer_time_values_to_utc_constructor(time); end
  def wrap_with_time_zone(time); end
end

ActiveSupport::TimeWithZone::PRECISIONS = T.let(T.unsafe(nil), Hash)
ActiveSupport::TimeWithZone::SECONDS_PER_DAY = T.let(T.unsafe(nil), Integer)

class ActiveSupport::TimeZone
  include ::Comparable

  def initialize(name, utc_offset = T.unsafe(nil), tzinfo = T.unsafe(nil)); end

  def <=>(zone); end
  def =~(re); end
  def abbr(time); end
  def at(*args); end
  def dst?(time); end
  def encode_with(coder); end
  def formatted_offset(colon = T.unsafe(nil), alternate_utc_string = T.unsafe(nil)); end
  def init_with(coder); end
  def iso8601(str); end
  def local(*args); end
  def local_to_utc(time, dst = T.unsafe(nil)); end
  def match?(re); end
  def name; end
  def now; end
  def parse(str, now = T.unsafe(nil)); end
  def period_for_local(time, dst = T.unsafe(nil)); end
  def period_for_utc(time); end
  def periods_for_local(time); end
  def rfc3339(str); end
  def standard_name; end
  def strptime(str, format, now = T.unsafe(nil)); end
  def to_s; end
  def today; end
  def tomorrow; end
  def tzinfo; end
  def utc_offset; end
  def utc_to_local(time); end
  def yesterday; end

  private

  def parts_to_time(parts, now); end
  def time_now; end

  class << self
    def [](arg); end
    def all; end
    def clear; end
    def country_zones(country_code); end
    def create(*_arg0); end
    def find_tzinfo(name); end
    def new(name); end
    def seconds_to_utc_offset(seconds, colon = T.unsafe(nil)); end
    def us_zones; end

    private

    def load_country_zones(code); end
    def zones_map; end
  end
end

ActiveSupport::TimeZone::MAPPING = T.let(T.unsafe(nil), Hash)
ActiveSupport::TimeZone::UTC_OFFSET_WITHOUT_COLON = T.let(T.unsafe(nil), String)
ActiveSupport::TimeZone::UTC_OFFSET_WITH_COLON = T.let(T.unsafe(nil), String)

module ActiveSupport::ToJsonWithActiveSupportEncoder
  def to_json(options = T.unsafe(nil)); end
end

module ActiveSupport::Tryable
  def try(*args, **_arg1, &block); end
  def try!(*args, **_arg1, &block); end
end

class Array
  include ::Enumerable

  def as_json(options = T.unsafe(nil)); end
  def to_formatted_s(format = T.unsafe(nil)); end
  def to_fs(format = T.unsafe(nil)); end
  def to_param; end
  def to_query(key); end
  def to_sentence(options = T.unsafe(nil)); end
  def to_xml(options = T.unsafe(nil)); end
end

class BigDecimal < ::Numeric
  include ::ActiveSupport::BigDecimalWithDefaultFormat

  def as_json(options = T.unsafe(nil)); end
end

class Data
  def as_json(options = T.unsafe(nil)); end
end

class Date
  include ::Comparable
  include ::DateAndTime::Zones
  include ::DateAndTime::Calculations

  def +(other); end
  def -(other); end
  def <=>(other); end
  def advance(options); end
  def ago(seconds); end
  def as_json(options = T.unsafe(nil)); end
  def at_beginning_of_day; end
  def at_end_of_day; end
  def at_midday; end
  def at_middle_of_day; end
  def at_midnight; end
  def at_noon; end
  def beginning_of_day; end
  def change(options); end
  def compare_with_coercion(other); end
  def compare_without_coercion(_arg0); end
  def default_inspect; end
  def end_of_day; end
  def in(seconds); end
  def inspect; end
  def midday; end
  def middle_of_day; end
  def midnight; end
  def minus_with_duration(other); end
  def minus_without_duration(_arg0); end
  def noon; end
  def plus_with_duration(other); end
  def plus_without_duration(_arg0); end
  def readable_inspect; end
  def since(seconds); end
  def to_formatted_s(format = T.unsafe(nil)); end
  def to_fs(format = T.unsafe(nil)); end
  def to_time(form = T.unsafe(nil)); end
  def xmlschema; end

  class << self
    def beginning_of_week; end
    def beginning_of_week=(week_start); end
    def beginning_of_week_default; end
    def beginning_of_week_default=(_arg0); end
    def current; end
    def find_beginning_of_week!(week_start); end
    def tomorrow; end
    def yesterday; end
  end
end

Date::DATE_FORMATS = T.let(T.unsafe(nil), Hash)
module DateAndTime; end

module DateAndTime::Calculations
  def after?(date_or_time); end
  def all_day; end
  def all_month; end
  def all_quarter; end
  def all_week(start_day = T.unsafe(nil)); end
  def all_year; end
  def at_beginning_of_month; end
  def at_beginning_of_quarter; end
  def at_beginning_of_week(start_day = T.unsafe(nil)); end
  def at_beginning_of_year; end
  def at_end_of_month; end
  def at_end_of_quarter; end
  def at_end_of_week(start_day = T.unsafe(nil)); end
  def at_end_of_year; end
  def before?(date_or_time); end
  def beginning_of_month; end
  def beginning_of_quarter; end
  def beginning_of_week(start_day = T.unsafe(nil)); end
  def beginning_of_year; end
  def days_ago(days); end
  def days_since(days); end
  def days_to_week_start(start_day = T.unsafe(nil)); end
  def end_of_month; end
  def end_of_quarter; end
  def end_of_week(start_day = T.unsafe(nil)); end
  def end_of_year; end
  def future?; end
  def last_month; end
  def last_quarter; end
  def last_week(start_day = T.unsafe(nil), same_time: T.unsafe(nil)); end
  def last_weekday; end
  def last_year; end
  def monday; end
  def months_ago(months); end
  def months_since(months); end
  def next_day?; end
  def next_occurring(day_of_week); end
  def next_quarter; end
  def next_week(given_day_in_next_week = T.unsafe(nil), same_time: T.unsafe(nil)); end
  def next_weekday; end
  def on_weekday?; end
  def on_weekend?; end
  def past?; end
  def prev_day?; end
  def prev_occurring(day_of_week); end
  def prev_quarter; end
  def prev_week(start_day = T.unsafe(nil), same_time: T.unsafe(nil)); end
  def prev_weekday; end
  def quarter; end
  def sunday; end
  def today?; end
  def tomorrow; end
  def tomorrow?; end
  def weeks_ago(weeks); end
  def weeks_since(weeks); end
  def years_ago(years); end
  def years_since(years); end
  def yesterday; end
  def yesterday?; end

  private

  def copy_time_to(other); end
  def days_span(day); end
  def first_hour(date_or_time); end
  def last_hour(date_or_time); end
end

DateAndTime::Calculations::DAYS_INTO_WEEK = T.let(T.unsafe(nil), Hash)
DateAndTime::Calculations::WEEKEND_DAYS = T.let(T.unsafe(nil), Array)

module DateAndTime::Compatibility
  def utc_to_local_returns_utc_offset_times; end

  class << self
    def utc_to_local_returns_utc_offset_times; end
    def utc_to_local_returns_utc_offset_times=(val); end
  end
end

module DateAndTime::Zones
  def in_time_zone(zone = T.unsafe(nil)); end

  private

  def time_with_zone(time, zone); end
end

class DateTime < ::Date
  def <=>(other); end
  def advance(options); end
  def ago(seconds); end
  def as_json(options = T.unsafe(nil)); end
  def at_beginning_of_day; end
  def at_beginning_of_hour; end
  def at_beginning_of_minute; end
  def at_end_of_day; end
  def at_end_of_hour; end
  def at_end_of_minute; end
  def at_midday; end
  def at_middle_of_day; end
  def at_midnight; end
  def at_noon; end
  def beginning_of_day; end
  def beginning_of_hour; end
  def beginning_of_minute; end
  def change(options); end
  def default_inspect; end
  def end_of_day; end
  def end_of_hour; end
  def end_of_minute; end
  def formatted_offset(colon = T.unsafe(nil), alternate_utc_string = T.unsafe(nil)); end
  def getgm; end
  def getlocal(utc_offset = T.unsafe(nil)); end
  def getutc; end
  def gmtime; end
  def in(seconds); end
  def inspect; end
  def localtime(utc_offset = T.unsafe(nil)); end
  def midday; end
  def middle_of_day; end
  def midnight; end
  def noon; end
  def nsec; end
  def readable_inspect; end
  def seconds_since_midnight; end
  def seconds_until_end_of_day; end
  def since(seconds); end
  def subsec; end
  def to_f; end
  def to_formatted_s(format = T.unsafe(nil)); end
  def to_fs(format = T.unsafe(nil)); end
  def to_i; end
  def usec; end
  def utc; end
  def utc?; end
  def utc_offset; end

  private

  def offset_in_seconds; end
  def seconds_since_unix_epoch; end

  class << self
    def civil_from_format(utc_or_local, year, month = T.unsafe(nil), day = T.unsafe(nil), hour = T.unsafe(nil), min = T.unsafe(nil), sec = T.unsafe(nil)); end
    def current; end
  end
end

class Delegator < ::BasicObject
  include ::ActiveSupport::Tryable
end

module ERB::Util
  include ::ActiveSupport::CoreExt::ERBUtil
  include ::ActiveSupport::CoreExt::ERBUtilPrivate
  extend ::ActiveSupport::CoreExt::ERBUtil

  private

  def html_escape_once(s); end
  def json_escape(s); end
  def xml_name_escape(name); end

  class << self
    def html_escape_once(s); end
    def json_escape(s); end
    def tokenize(source); end
    def unwrapped_html_escape(s); end
    def xml_name_escape(name); end
  end
end

ERB::Util::HTML_ESCAPE = T.let(T.unsafe(nil), Hash)
ERB::Util::HTML_ESCAPE_ONCE_REGEXP = T.let(T.unsafe(nil), Regexp)
ERB::Util::INVALID_TAG_NAME_FOLLOWING_REGEXP = T.let(T.unsafe(nil), Regexp)
ERB::Util::INVALID_TAG_NAME_START_REGEXP = T.let(T.unsafe(nil), Regexp)
ERB::Util::SAFE_XML_TAG_NAME_REGEXP = T.let(T.unsafe(nil), Regexp)
ERB::Util::TAG_NAME_FOLLOWING_CODEPOINTS = T.let(T.unsafe(nil), String)
ERB::Util::TAG_NAME_REPLACEMENT_CHAR = T.let(T.unsafe(nil), String)
ERB::Util::TAG_NAME_START_CODEPOINTS = T.let(T.unsafe(nil), String)

module Enumerable
  include ::ActiveSupport::ToJsonWithActiveSupportEncoder

  def as_json(options = T.unsafe(nil)); end
end

class Exception
  def as_json(options = T.unsafe(nil)); end
end

class FalseClass
  def as_json(options = T.unsafe(nil)); end
  def to_param; end
end

class Float < ::Numeric
  def as_json(options = T.unsafe(nil)); end
end

class Hash
  include ::Enumerable
  include ::ActiveSupport::DeepMergeable

  def as_json(options = T.unsafe(nil)); end
  def assert_valid_keys(*valid_keys); end
  def deep_merge?(other); end
  def deep_stringify_keys; end
  def deep_stringify_keys!; end
  def deep_symbolize_keys; end
  def deep_symbolize_keys!; end
  def deep_transform_keys(&block); end
  def deep_transform_keys!(&block); end
  def except!(*keys); end
  def extract!(*keys); end
  def slice!(*keys); end
  def stringify_keys; end
  def stringify_keys!; end
  def symbolize_keys; end
  def symbolize_keys!; end
  def to_options; end
  def to_options!; end
  def to_param(namespace = T.unsafe(nil)); end
  def to_query(namespace = T.unsafe(nil)); end

  private

  def _deep_transform_keys_in_object(object, &block); end
  def _deep_transform_keys_in_object!(object, &block); end
end

class IO
  include ::Enumerable
  include ::File::Constants

  def as_json(options = T.unsafe(nil)); end
end

class IO::Buffer
  include ::Comparable

  def initialize(*_arg0); end

  def &(_arg0); end
  def <=>(_arg0); end
  def ^(_arg0); end
  def and!(_arg0); end
  def clear(*_arg0); end
  def copy(*_arg0); end
  def each(*_arg0); end
  def each_byte(*_arg0); end
  def empty?; end
  def external?; end
  def free; end
  def get_string(*_arg0); end
  def get_value(_arg0, _arg1); end
  def get_values(_arg0, _arg1); end
  def hexdump(*_arg0); end
  def inspect; end
  def internal?; end
  def locked; end
  def locked?; end
  def mapped?; end
  def not!; end
  def null?; end
  def or!(_arg0); end
  def pread(*_arg0); end
  def private?; end
  def pwrite(*_arg0); end
  def read(*_arg0); end
  def readonly?; end
  def resize(_arg0); end
  def set_string(*_arg0); end
  def set_value(_arg0, _arg1, _arg2); end
  def set_values(_arg0, _arg1, _arg2); end
  def shared?; end
  def size; end
  def slice(*_arg0); end
  def to_s; end
  def transfer; end
  def valid?; end
  def values(*_arg0); end
  def write(*_arg0); end
  def xor!(_arg0); end
  def |(_arg0); end
  def ~; end

  private

  def initialize_copy(_arg0); end

  class << self
    def for(_arg0); end
    def map(*_arg0); end
    def size_of(_arg0); end
    def string(_arg0); end
  end
end

class IO::Buffer::AccessError < ::RuntimeError; end
class IO::Buffer::AllocationError < ::RuntimeError; end
IO::Buffer::BIG_ENDIAN = T.let(T.unsafe(nil), Integer)
IO::Buffer::DEFAULT_SIZE = T.let(T.unsafe(nil), Integer)
IO::Buffer::EXTERNAL = T.let(T.unsafe(nil), Integer)
IO::Buffer::HOST_ENDIAN = T.let(T.unsafe(nil), Integer)
IO::Buffer::INTERNAL = T.let(T.unsafe(nil), Integer)
class IO::Buffer::InvalidatedError < ::RuntimeError; end
IO::Buffer::LITTLE_ENDIAN = T.let(T.unsafe(nil), Integer)
IO::Buffer::LOCKED = T.let(T.unsafe(nil), Integer)
class IO::Buffer::LockedError < ::RuntimeError; end
IO::Buffer::MAPPED = T.let(T.unsafe(nil), Integer)
class IO::Buffer::MaskError < ::ArgumentError; end
IO::Buffer::NETWORK_ENDIAN = T.let(T.unsafe(nil), Integer)
IO::Buffer::PAGE_SIZE = T.let(T.unsafe(nil), Integer)
IO::Buffer::PRIVATE = T.let(T.unsafe(nil), Integer)
IO::Buffer::READONLY = T.let(T.unsafe(nil), Integer)
IO::Buffer::SHARED = T.let(T.unsafe(nil), Integer)

class IO::EAGAINWaitReadable < ::Errno::EAGAIN
  include ::IO::WaitReadable
end

class IO::EAGAINWaitWritable < ::Errno::EAGAIN
  include ::IO::WaitWritable
end

class IO::EINPROGRESSWaitReadable < ::Errno::EINPROGRESS
  include ::IO::WaitReadable
end

class IO::EINPROGRESSWaitWritable < ::Errno::EINPROGRESS
  include ::IO::WaitWritable
end

IO::EWOULDBLOCKWaitReadable = IO::EAGAINWaitReadable
IO::EWOULDBLOCKWaitWritable = IO::EAGAINWaitWritable
IO::PRIORITY = T.let(T.unsafe(nil), Integer)
IO::READABLE = T.let(T.unsafe(nil), Integer)
IO::WRITABLE = T.let(T.unsafe(nil), Integer)
class Integer < ::Numeric; end

class Module
  def as_json(options = T.unsafe(nil)); end
  def cattr_accessor(*syms, instance_reader: T.unsafe(nil), instance_writer: T.unsafe(nil), instance_accessor: T.unsafe(nil), default: T.unsafe(nil), &blk); end
  def cattr_reader(*syms, instance_reader: T.unsafe(nil), instance_accessor: T.unsafe(nil), default: T.unsafe(nil), location: T.unsafe(nil)); end
  def cattr_writer(*syms, instance_writer: T.unsafe(nil), instance_accessor: T.unsafe(nil), default: T.unsafe(nil), location: T.unsafe(nil)); end
  def delegate(*methods, to: T.unsafe(nil), prefix: T.unsafe(nil), allow_nil: T.unsafe(nil), private: T.unsafe(nil)); end
  def delegate_missing_to(target, allow_nil: T.unsafe(nil)); end
  def mattr_accessor(*syms, instance_reader: T.unsafe(nil), instance_writer: T.unsafe(nil), instance_accessor: T.unsafe(nil), default: T.unsafe(nil), &blk); end
  def mattr_reader(*syms, instance_reader: T.unsafe(nil), instance_accessor: T.unsafe(nil), default: T.unsafe(nil), location: T.unsafe(nil)); end
  def mattr_writer(*syms, instance_writer: T.unsafe(nil), instance_accessor: T.unsafe(nil), default: T.unsafe(nil), location: T.unsafe(nil)); end
  def method_visibility(method); end
  def redefine_method(method, &block); end
  def redefine_singleton_method(method, &block); end
  def silence_redefinition_of_method(method); end
end

Module::DelegationError = ActiveSupport::DelegationError

class NameError < ::StandardError
  include ::ErrorHighlight::CoreExt
  include ::DidYouMean::Correctable
end

class NilClass
  def as_json(options = T.unsafe(nil)); end
  def to_param; end
  def to_query(key); end
  def try(*_arg0, &_arg1); end
  def try!(*_arg0, &_arg1); end
end

class Numeric
  include ::Comparable

  def as_json(options = T.unsafe(nil)); end
  def html_safe?; end
end

class Object < ::BasicObject
  include ::Kernel
  include ::PP::ObjectMixin
  include ::Udb::Helpers::WavedromUtil
  include ::ActiveSupport::Tryable
  include ::ActiveSupport::ToJsonWithActiveSupportEncoder

  def acts_like?(duck); end
  def as_json(options = T.unsafe(nil)); end
  def html_safe?; end
  def instance_values; end
  def instance_variable_names; end
  def to_param; end
  def to_query(key); end
end

class Pathname
  def as_json(options = T.unsafe(nil)); end
end

class Process::Status
  def as_json(options = T.unsafe(nil)); end
end

class Range
  include ::Enumerable

  def as_json(options = T.unsafe(nil)); end
end

class Regexp
  def as_json(options = T.unsafe(nil)); end
end

class String
  include ::Comparable

  def acts_like_string?; end
  def as_json(options = T.unsafe(nil)); end
  def at(position); end
  def camelcase(first_letter = T.unsafe(nil)); end
  def camelize(first_letter = T.unsafe(nil)); end
  def classify; end
  def constantize; end
  def dasherize; end
  def deconstantize; end
  def demodulize; end
  def downcase_first; end
  def first(limit = T.unsafe(nil)); end
  def foreign_key(separate_class_name_and_id_with_underscore = T.unsafe(nil)); end
  def from(position); end
  def html_safe; end
  def humanize(capitalize: T.unsafe(nil), keep_id_suffix: T.unsafe(nil)); end
  def is_utf8?; end
  def last(limit = T.unsafe(nil)); end
  def mb_chars; end
  def parameterize(separator: T.unsafe(nil), preserve_case: T.unsafe(nil), locale: T.unsafe(nil)); end
  def pluralize(count = T.unsafe(nil), locale = T.unsafe(nil)); end
  def safe_constantize; end
  def singularize(locale = T.unsafe(nil)); end
  def tableize; end
  def titlecase(keep_id_suffix: T.unsafe(nil)); end
  def titleize(keep_id_suffix: T.unsafe(nil)); end
  def to(position); end
  def underscore; end
  def upcase_first; end
end

class Struct
  include ::Enumerable

  def as_json(options = T.unsafe(nil)); end
end

class Symbol
  include ::Comparable

  def as_json(options = T.unsafe(nil)); end
end

class Time
  include ::Comparable
  include ::DateAndTime::Zones

  def acts_like_time?; end
  def as_json(options = T.unsafe(nil)); end
  def formatted_offset(colon = T.unsafe(nil), alternate_utc_string = T.unsafe(nil)); end
  def rfc3339(*_arg0); end
  def to_formatted_s(format = T.unsafe(nil)); end
  def to_fs(format = T.unsafe(nil)); end

  class << self
    def find_zone(time_zone); end
    def find_zone!(time_zone); end
    def use_zone(time_zone); end
    def zone; end
    def zone=(time_zone); end
    def zone_default; end
    def zone_default=(_arg0); end
  end
end

Time::DATE_FORMATS = T.let(T.unsafe(nil), Hash)

class TrueClass
  def as_json(options = T.unsafe(nil)); end
  def to_param; end
end

class URI::Generic
  def as_json(options = T.unsafe(nil)); end
end
