# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `asciidoctor-diagram-plantuml` gem.
# Please instead update this file by running `bin/tapioca gem asciidoctor-diagram-plantuml`.


# source://asciidoctor-diagram-plantuml//lib/asciidoctor-diagram/plantuml/classpath.rb#3
module Asciidoctor
  class << self
    # source://asciidoctor/2.0.23/lib/asciidoctor.rb#529
    def const_missing(name); end

    # source://asciidoctor/2.0.23/lib/asciidoctor/convert.rb#34
    def convert(input, options = T.unsafe(nil)); end

    # source://asciidoctor/2.0.23/lib/asciidoctor/convert.rb#189
    def convert_file(filename, options = T.unsafe(nil)); end

    # source://asciidoctor/2.0.23/lib/asciidoctor/load.rb#17
    def load(input, options = T.unsafe(nil)); end

    # source://asciidoctor/2.0.23/lib/asciidoctor/load.rb#115
    def load_file(filename, options = T.unsafe(nil)); end

    # source://asciidoctor/2.0.23/lib/asciidoctor/convert.rb#34
    def render(input, options = T.unsafe(nil)); end

    # source://asciidoctor/2.0.23/lib/asciidoctor/convert.rb#189
    def render_file(filename, options = T.unsafe(nil)); end
  end
end

# source://asciidoctor-diagram-plantuml//lib/asciidoctor-diagram/plantuml/classpath.rb#4
module Asciidoctor::Diagram; end

# source://asciidoctor-diagram-plantuml//lib/asciidoctor-diagram/plantuml/classpath.rb#5
module Asciidoctor::Diagram::PlantUmlClasspath; end

# source://asciidoctor-diagram-plantuml//lib/asciidoctor-diagram/plantuml/classpath.rb#6
Asciidoctor::Diagram::PlantUmlClasspath::JAR_FILES = T.let(T.unsafe(nil), Array)
