# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# yaml-language-server: $schema=../../../schemas/param_schema.json

$schema: param_schema.json#
kind: parameter
name: MSTATUS_FS_LEGAL_VALUES
description: The set of values that mstatus.FS supports.
long_name: mstatus.FS legal values
schema:
  type: array
  items:
    type: integer
    enum:
      - 0 # Off
      - 1 # Initial
      - 2 # Clean
      - 3 # Dirty
  maxItems: 4
  minItems: 1
  uniqueItems: true
requirements:
  idl(): |
    implemented?(ExtensionName::F) ->
      $array_includes?(MSTATUS_FS_LEGAL_VALUES, 3);
  reason: If F extension is implemented, then the Dirty state must be supported
definedBy:
  extension:
    allOf:
      - name: Sm
      - anyOf:
          - name: F
          - name: S
