# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# yaml-language-server: $schema=../../../schemas/param_schema.json

$schema: param_schema.json#
kind: parameter
name: SDTRIG_VU_LEGAL_VALUES
description: |
  The set of values that the VU field supports in every trigger type that has one (mcontrol, mcontrol6, icount, itrigger, etrigger).
long_name: Legal values of the trigger VU bit
schema:
  type: array
  items:
    type: integer
    enum:
      - 0
      - 1
  maxItems: 2
  minItems: 1
  uniqueItems: true
requirements:
  idl(): |
    !implemented?(ExtensionName::H) -> !$array_includes?(SDTRIG_VU_LEGAL_VALUES, 1);
  reason: 'Debug spec 1.0: "This bit is hard-wired to 0 if the hart does not support virtualization mode."'
definedBy:
  extension:
    name: Sdtrig
