# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

"""Python access to the RISC-V Unified Database."""

from .architecture import (
    ArchitectureCheck,
    ArchitectureCheckStatus,
    ArchitectureDiagnostic,
    ArchitectureError,
    ConfiguredArchitecture,
    CsrField,
    DeferredQuery,
    QueryPresence,
)
from .authoring import AuthoringPlan, GeneratedFile
from .conditions import (
    FALSE,
    TRUE,
    AllOf,
    AnyOf,
    Condition,
    ConditionError,
    ConstantCondition,
    EvaluationContext,
    ExactlyOne,
    ExtensionTerm,
    FreeTerm,
    Implies,
    NoneOf,
    Not,
    ParameterOperator,
    ParameterTerm,
    TruthValue,
    UnresolvedConditionError,
    UnresolvedIdlCondition,
    XlenTerm,
    all_of,
    any_of,
    exactly_one,
    negate,
    none_of,
    normalize,
    not_,
    parse_condition,
    partial_evaluate,
)
from .configuration import (
    Configuration,
    ConfigurationError,
    ConfigurationKind,
    ExtensionSelection,
    Presence,
)
from .database import (
    Csr,
    Database,
    DatabaseObject,
    Extension,
    Instruction,
    Profile,
    ResolvedDatabase,
)
from .domains import DomainError, EnumerationLimitError, ParameterDomain
from .encoding import (
    CsrAddressKey,
    CsrAddressOverlap,
    InstructionEncoding,
    InstructionOverlap,
    OverlapKind,
)
from .errors import (
    AuthoringError,
    DataError,
    LayoutError,
    ObjectNotFoundError,
    ReferenceError,
    ResolutionError,
    SerializationError,
    UdbError,
    UnknownKindError,
)
from .layouts import (
    LayoutJob,
    generate_layouts,
    iter_layout_jobs,
    layout_plan,
    layout_sources,
    render_layout,
)
from .reference import DataReference, Reference, ResolvedNode, SchemaReference
from .resolver import YamlResolver, merge_patch
from .schema import SchemaError, SchemaStore
from .serialization import (
    SCHEMAS_BASE_URL,
    dumps_json,
    dumps_yaml,
    write_config,
    write_resolved_database,
    write_resolved_schemas,
)
from .solver import (
    ConditionModel,
    ConditionSolver,
    SolverContext,
    SolverError,
    SolverStatus,
    SolverUnknownError,
    finite_check,
    is_satisfiable,
)
from .source import SourceMap, SourceSpan
from .versions import (
    ExtensionVersion,
    ExtensionVersionSet,
    RequirementOperator,
    Version,
    VersionRequirement,
    parse_version_requirements,
)

__all__ = [
    "FALSE",
    "SCHEMAS_BASE_URL",
    "TRUE",
    "AllOf",
    "AnyOf",
    "ArchitectureCheck",
    "ArchitectureCheckStatus",
    "ArchitectureDiagnostic",
    "ArchitectureError",
    "AuthoringError",
    "AuthoringPlan",
    "Condition",
    "ConditionError",
    "ConditionModel",
    "ConditionSolver",
    "Configuration",
    "ConfigurationError",
    "ConfigurationKind",
    "ConfiguredArchitecture",
    "ConstantCondition",
    "Csr",
    "CsrAddressKey",
    "CsrAddressOverlap",
    "CsrField",
    "DataError",
    "DataReference",
    "Database",
    "DatabaseObject",
    "DeferredQuery",
    "DomainError",
    "EnumerationLimitError",
    "EvaluationContext",
    "ExactlyOne",
    "Extension",
    "ExtensionSelection",
    "ExtensionTerm",
    "ExtensionVersion",
    "ExtensionVersionSet",
    "FreeTerm",
    "GeneratedFile",
    "Implies",
    "Instruction",
    "InstructionEncoding",
    "InstructionOverlap",
    "LayoutError",
    "LayoutJob",
    "NoneOf",
    "Not",
    "ObjectNotFoundError",
    "OverlapKind",
    "ParameterDomain",
    "ParameterOperator",
    "ParameterTerm",
    "Presence",
    "Profile",
    "QueryPresence",
    "Reference",
    "ReferenceError",
    "RequirementOperator",
    "ResolutionError",
    "ResolvedDatabase",
    "ResolvedNode",
    "SchemaError",
    "SchemaReference",
    "SchemaStore",
    "SerializationError",
    "SolverContext",
    "SolverError",
    "SolverStatus",
    "SolverUnknownError",
    "SourceMap",
    "SourceSpan",
    "TruthValue",
    "UdbError",
    "UnknownKindError",
    "UnresolvedConditionError",
    "UnresolvedIdlCondition",
    "Version",
    "VersionRequirement",
    "XlenTerm",
    "YamlResolver",
    "all_of",
    "any_of",
    "dumps_json",
    "dumps_yaml",
    "exactly_one",
    "finite_check",
    "generate_layouts",
    "is_satisfiable",
    "iter_layout_jobs",
    "layout_plan",
    "layout_sources",
    "merge_patch",
    "negate",
    "none_of",
    "normalize",
    "not_",
    "parse_condition",
    "parse_version_requirements",
    "partial_evaluate",
    "render_layout",
    "write_config",
    "write_resolved_database",
    "write_resolved_schemas",
]
