# typed: true
# frozen_string_literal: true

require "active_support/array_inquirer"
require "active_support/core_ext/date/calculations"
require "active_support/core_ext/string/output_safety"
require "active_support/inflector/methods"
require "active_support/string_inquirer"
require "asciidoctor"
require "awesome_print"
require "bundler"
require "concurrent"
require "forwardable"
require "idlc"
require "idlc/interfaces"
require "idlc/passes/find_return_values"
require "idlc/passes/gen_adoc"
require "idlc/passes/gen_option_adoc"
require "idlc/passes/prune"
require "idlc/passes/reachable_exceptions"
require "idlc/passes/reachable_functions"
require "idlc/type"
require "json"
require "json_schemer"
require "minitest"
require "pathname"
require "simplecov"
require "sorbet-runtime"
require "terminal-table"
require "thor"
require "tilt"
require "udb/architecture"
require "udb_helpers/backend_helpers"
require "yaml"
require "minisat"
require "z3"
