#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Contributors to the RISCV UnifiedDB <https://github.com/riscv/riscv-unified-db>
# SPDX-License-Identifier: BSD-3-Clause-Clear
#MISE description="Regression task translated from regress-schema-versions"

set -e

# Step 1: Check schema versions against published URLs
(
  uv run --locked udb --schema-dir spec/schemas generate schema-bundle -o gen/schemas && ./bin/python tools/scripts/check_schema_versions.py
)
