grammar org.xtext.example.udb.Udb with org.eclipse.xtext.common.Terminals

generate udb "http://www.xtext.org/example/udb/Udb"

import "http://www.eclipse.org/emf/2002/Ecore" as ecore

Model:
	kind += Kind
	csrName += Name
	longname += LongName
	address += Address
	writable += Writable
	privmode += PrivMode
	length += Length
	description += Description
	definedBy += DefinedBy
	fields += Fields
;


Kind: 'kind' ':' kind=KIND_TYPE ';';
Name: 'name' ':' name=ID';';
LongName: 'long_name' ':' long_name+=ID*';';
Address: 'address' ':' address=Hex';'; /* need to make this only accept 3 digit hex */
Writable: 'writable' ':' writable=BOOLEAN';';
PrivMode:'priv_mode' ':' priv_mode=PRIV_TYPE';';
Length: 'length' ':' length=STRING ';'; /* need to change string into an enum (?) */
Description: 'description' ':' description=STRING ';';

/* will need to change this to include valid extensions */
DefinedBy:'definedBy' ':'extension_name=ID ';';

KIND_TYPE:
	type=('csr'|'extension') /* this will need to be an enum */
;

PRIV_TYPE:
	priv_type=('U'|'S'|'M') /* may need to turn into an enum */
;

Fields:
	{Fields} 'fields' '{'
    fields+=FIELD_DEF+
  '}'
;

FIELD_DEF:
	name=FIELD_TYPE '{'
		field_location += Location
		field_description += Description
		field_type += Type
		field_alias += Alias
		field_sw_write += SWWrite
		field_reset_value += ResetValue
	'}'
	
;

FIELD_TYPE: 
	('VXRM' | 'VXSAT') /* should be an enum */
;

Location: GeneralLocation | SpecificLocation;
Type: "type" ":" type=STRING ';';
Alias: "alias" ":" alias=STRING ';'; /* not sure what this is supposed to be */
SWWrite: "sw_write(csr_value)" ":" STRING ';'; /* this should be IDL */
ResetValue: "reset_value" ":" STRING ';'; /* should be an enum */

GeneralLocation: 
	"location" ":" location=STRING ';'
;

SpecificLocation:
	location32 += LocationRV32
	location64 += LocationRV64
;

LocationRV32: 
	"location_rv32" ":" location32=STRING ";"
;

LocationRV64:
	"location_rv64" ":" location64=STRING ";"
;

Hex:
	value=HEX_VALUE
;
		
/* Terminals */
terminal HEX_VALUE returns ecore::EInt:
	('0x' | '0X')
	('0'..'9' | 'A'..'F' | 'a'..'f')
	(('0'..'9' | 'A'..'F' | 'a'..'f' | '_')*('0'..'9' | 'A'..'F' | 'a'..'f'))?
;

terminal BOOLEAN returns ecore::EBoolean: 'true' | 'false';
