grammar org.xtext.example.udb.Udb with org.eclipse.xtext.common.Terminals

generate udb "http://www.xtext.org/example/udb/Udb"

import "http://www.eclipse.org/emf/2002/Ecore" as ecore

Model:
	csrs += Csr*
	csrName += Name
	kind += Kind
	longname += LongName
	address += Address
	writable += Writable
	privmode += PrivMode
	length += Length
	description += Description
	definedBy += DefinedBy
	fields += Fields
;

/* Taken from Ajit */
Csr:
	'csr' name=ID
		description=STRING
		address=Hex
		reset_value=STRING
		';'
;

Kind:
	'kind'
	':'
	kind=KIND_TYPE
	';'
;

KIND_TYPE:
	type=('csr'|'extension')
;

Name:
	'name' ':'
	name=ID
	';'
;

LongName:
	'long_name' ':'
	name=ID
	';'
;

Address:
	'address' ':'
	value=Hex /* need to make this only accept 3 digit hex */
	';'
;

Writable:
	'writable' ':'
	writable=('T'|'F')
	';'
;

PrivMode:
	'priv_mode' ':'
	priv_mode=PRIV_TYPE
	';'
;

PRIV_TYPE:
	priv_type=('U'|'S'|'M')
;

Length:
	'length' ':'
	length=STRING /* placeholder, will have to change to an enum (?) */
	';'
;

Description:
	'desc' ':'
	description=STRING
	';'
;

DefinedBy:
	'definedBy' ':'
	extension_name=ID
	';'
;

Fields:
	{Fields} 'fields' '{'
    fields+=FIELD_DEF*
  '}'
;

FIELD_DEF:
	name=ID '{'
	/* field values */
	'}'
	
;

Hex:
	value=HEX_VALUE
;
		
/* Terminals */
terminal HEX_VALUE returns ecore::EInt:
	('0x' | '0X')
	('0'..'9' | 'A'..'F' | 'a'..'f')
	(('0'..'9' | 'A'..'F' | 'a'..'f' | '_')*('0'..'9' | 'A'..'F' | 'a'..'f'))?
;