plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-sorbet

inherit_gem:
  rubocop-github:
    - config/default.yml

AllCops:
  TargetRubyVersion: 3.2.3

Lint/UnusedMethodArgument:
  IgnoreEmptyMethods: true
  IgnoreNotImplementedMethods: true

Style/CommentedKeyword:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: "double_quotes"

Style/SymbolArray:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  CountAsOne: ["array", "heredoc", "hash", "method_call"]

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: true
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Enabled: false

Security/Eval:
  Enabled: false
