= UnifiedDB Contribution Guide

Thank you for your interest in contributing to UnifiedDB!
We welcome all contributions that meet our xref:CODE_OF_CONDUCT.adoc[code of conduct].

== Legal

All contributions to UnifiedDB are by default made under the xref:LICENSE[BSD-3-clear license].
Copyrights are held by the specific contributors, and are not tracked by the UnifiedDB project other
than what can be gleaned through git history.

Under special circumstances code may be added under a different license.
For example, code from an existing project may be integrated after careful deliberation.
Any contributions under a different license will receive extra review.
When any contribution is made under a different license, it must be tracked using
https://reuse.software/tutorial/#step-2[a Reuse-compatible identifer].

To keep UnifiedDB open to both private and commercial interests, contributions under a
https://en.wikipedia.org/wiki/copyleft[copyleft license] will never be accepted.

== Ways to contribute

=== Bug Reports

Bug reports should be filed as a https://github.com/riscv-software-src/riscv-unified-db/issues[GitHub Issue] using the `Bug report` template.

=== Feature Requests

Bug reports should be filed as a https://github.com/riscv-software-src/riscv-unified-db/issues[GitHub Issue] using the `Feature request` template.

=== Bug Fixes

Bug fixes should be submitted as a Pull Request.

There should be a corresponding https://github.com/riscv-software-src/riscv-unified-db/issues[GitHub Issue] for the PR. Ensure the two are linked by adding "closes #<issue number>" in the PR description.

=== New data, tools, and features

New data (for example, adding an extension), tools, or features should be submitted as a Pull Request.

There should be a corresponding https://github.com/riscv-software-src/riscv-unified-db/issues[GitHub Issue] for the PR. Ensure the two are linked by adding "closes #<issue number>" in the PR description.

== Submitting a Pull Request

All patches must meet the UnifiedDB code standards. This includes:

* Pass regression tests (run locally as `./do test:regress`)
* Use appropriate commit messages
* Go through code review as a Pull Request

=== Regression tests

All contributions must pass the full suite of regression tests.
Regression tests are checked in GitHub for every PR, and they can also be run locally using `./do test:regress`.

If a Pull Request adds a new feature that is not already covered by the regression test suite, it
must add at least one new test.

=== Commit messages

UnifiedDB adheres to https://www.conventionalcommits.org/en/v1.0.0[Conventional Commits v1.0.0].

The guidelines below are adapted from https://github.com/angular/angular/blob/main/contributing-docs/commit-message-guidelines.md[the Angular commit message guidelines].

Every commit message consists of a mandatory *header*, a mandatory *body*, and an optional *footer*.

```
<header>
<BLANK LINE>
<body>
<BLANK LINE>
<footer>
```

==== Header

.UnifiedDB commit header format
```
<type>(<scope>): <short summary>
  │       │             │
  │       │             └─⫸ Summary in present tense. Not capitalized. No period at the end.
  │       │
  │       └─⫸ Commit Scope: single word describing the affected component
  │
  └─⫸ Commit Type: build|ci|correct|data|docs|feat|fix|refactor|schema|test
```

The `<type>` and `<summary>` fields are mandatory. The `<scope>` field is optional.

Type must be one of the following:

[cols="1l,3,2l"]
|===
| Type | Description | Example scopes

| build    | Changes that affect the build system or external dependencies        | rake, antora
| ci       | Changes to the CI configuration files and script                     | action
| correct  | A correction to data in the database (_i.e., a database bugfix)      | ext, inst, csr
| data     | An addition to the database contents                                 | ext, inst, csr
| docs     | Documentation-only changes                                           | schema, ruby-db, <backend name>
| feat     | A new feature                                                        | ruby-db, <backend name>
| fix      | A code bug fix                                                       | ruby-db, <backend name>
| refactor | A code change that neither fixes a bug nor adds a feature            | ruby-db, <backend name>
| schema   | A change to the database schema                                      | ext, inst, csr
| test     | Adding missing tests or correcting existing tests                    | schema, ruby-db
|===

==== Body

Just as in the summary, use the imperative, present tense: "fix" not "fixed" nor "fixes".

Explain the motivation for the change in the commit message body. This commit message should explain
_why_ you are making the change.
You can include a comparison of the previous behavior with the new behavior in order to illustrate
the impact of the change.

==== Footer

A footer is required when the commit introduces a breaking change or closes a GitHub issue. For example:

```
BREAKING CHANGE: <breaking change summary>
<BLANK LINE>
<breaking change description + migration instructions>
<BLANK LINE>
<BLANK LINE>
Fixes #<issue number>
```

=== Code review

All Pull Requests must go through the code review process.


== Finding tasks

If you are looking to contribute but are unsure what to do, browse through the https://github.com/riscv-software-src/riscv-unified-db/issues[issues]. We try to keep them tagged by area and mark easier tasks with "good first issue".
