= UnifiedDB Contribution Guide

Thank you for your interest in contributing to UnifiedDB!
We welcome all contributions that meet our xref:CODE_OF_CONDUCT.adoc[code of conduct].

== Legal

All contributions to UnifiedDB are by default made under the xref:LICENSE[BSD-3-clear license].
Copyrights are held by the specific contributors, and are not tracked by the UnifiedDB project other
than what can be gleaned through git history.

Under special circumstances code may be added under a different license.
For example, code from an existing project may be integrated after careful deliberation.
Any contributions under a different license will receive extra review.
When any contribution is made under a different license, it must be tracked using
https://reuse.software/tutorial/#step-2[a Reuse-compatible identifer].

To keep UnifiedDB open to both private and commercial interests, contributions under a
https://en.wikipedia.org/wiki/copyleft[copyleft license] will never be accepted.

== Ways to contribute

=== Bug Reports

Bug reports should be filed as a https://github.com/riscv-software-src/riscv-unified-db/issues[GitHub Issue] using the `Bug report` template.

=== Feature Requests

Bug reports should be filed as a https://github.com/riscv-software-src/riscv-unified-db/issues[GitHub Issue] using the `Feature request` template.

=== Bug Fixes

Bug fixes should be submitted as a Pull Request.

There should be a corresponding https://github.com/riscv-software-src/riscv-unified-db/issues[GitHub Issue] for the PR. Ensure the two are linked by adding "closes #<issue number>" in the PR description.

=== New data, tools, and features

New data (for example, adding an extension), tools, or features should be submitted as a Pull Request.

There should be a corresponding https://github.com/riscv-software-src/riscv-unified-db/issues[GitHub Issue] for the PR. Ensure the two are linked by adding "closes #<issue number>" in the PR description.

== Submitting a Pull Request

All patches must meet the UnifiedDB code standards. This includes:

* Pass regression tests (run locally as `./do test:regress`)
* Go through code review as a Pull Request
** Code owners must approve
* Use appropriate commit messages (TODO: commit message policy)

== Finding tasks

If you are looking to contribute but are unsure what to do, browse through the https://github.com/riscv-software-src/riscv-unified-db/issues[issues]. We try to keep them tagged by area and mark easier tasks with "good first issue".
