[tools]
uv = "latest"

[env]
_.python.venv = { path = ".venv", create = true }

[tasks."uv:install"]
description = "Install python dependencies"
run = "uv pip install -r requirements.txt"

[tasks."bundle:install"]
description = "Install gem dependencies"
run = "bundle install"

[tasks."pre-commit:run"]
run = "pre-commit run --all-files"
