= RISC-V Unified Database

== Generated artifacts

The following artifacts have been generated from the top of the `main` branch:

* https://riscv-software-src.github.io/riscv-unified-db/manual/html/index.html[ISA Manual with instruction and CSR appendix]
* https://riscv-software-src.github.io/riscv-unified-db/example_cfg/html/index.html[configuration-specific documentation]
* https://riscv-software-src.github.io/riscv-unified-db/ruby/index.html[Ruby API documentation (database interface)]
* https://riscv-software-src.github.io/riscv-unified-db/pdfs/rva.pdf[RVA Profile Family]
* https://riscv-software-src.github.io/riscv-unified-db/pdfs/MC-1.pdf[MC-1 Certification Requirements Document]

== Overview

The RISC-V Unified Database is intended to hold *all* the information needed to describe RISC-V,
including a list of extensions, instruction specifications, CSR specifications, and documentation prose. The vision is that anything one would need for RISC-V can be generated from the information in this repository.

This repository contains:

 * A (eventually complete) description of the RISC-V specification in a machine-readable format.
 * A tool to generate multiple views of that spec, including:
 ** A configuration-specific, human-readable documentation webpage
 ** [COMING SOON] A configuration-specific Instruction Set Simulator
 ** More backends are planned

== What can it do?

=== Working examples:

 * Generate https://riscv-software-src.github.io/riscv-unified-db/manual/index.html[configuration-specific documentation] taylored to the set of implemented extensions and unnamed implementation options (_e.g._, `./do gen:html[generic_rv64]`).
 ** Only implemented extensions/instructions/CSRs are included
 ** Unreachable/unimplemented parts of the formal specification are pruned away
 ** A dedicated documentation page for every implemented instruction, including its encoding, pruned execution behavior, and what types of exceptions it may cause.
 ** A dedicated documentation page for every implemented CSR, including its (possibly runtime-changing) encoding, fields, and pruned behavior on reads and writes
 ** Clickable links to all mentions of instructions, extensions, CSRs, CSR fields, and glossary terms.
 * Generate documentation for specific extensions (_e.g._, `./do gen:ext_pdf[B]`)
 ** Automatically include a complete list of added instructions and CSRs
 ** Per-instruction documentation
 ** Per-CSR documentation
 ** Formal specification
 * Generate a single YAML file containing *everything* knowable about a configuration (_e.g._, `./do gen:cfg_arch[generic_rv64]`).

=== Possibilities:

  * Generate binutils files for an extension
  * Generate instruction tables for compilers
  * Generate https://github.com/riscv/riscv-opcodes[riscv-opcodes]
  * Generate the full RISC-V specification, along with an appendix of instructions and CSRs
  * ...

== Prerequisites

The only requirement is the `Singularity CE` (>= 3.3) or `Apptainer` (>= 1.0) container system. Either one will work (they are forks).

If it is not installed, either as your IT admin or:

 * For Apptainer, see https://apptainer.org/docs/admin/main/installation.html[Apptainer Installation].
 * For Singularity CE, see https://docs.sylabs.io/guides/latest/admin-guide/installation.html[Singularity CE Installation].

[NOTE]
You do *not* need root privileges to download or use the container. However, to modify/build the container,
you will need either root privileges or the ability to run in `fakeroot` mode. See https://docs.sylabs.io/guides/4.1/user-guide/fakeroot.html[Singularity Fakeroot Documentation] for more information.

== Setup

Do once:

[source,bash]
----
./bin/setup

# or, if you also want development tools (:development group in Gemfile) installed
# DEVELOPMENT=1 ./bin/setup
----

[NOTE]
If you forget, don't worry. Setup will be invoked by any program in bin/ if necessary.

=== VSCode

If using Visual Studio Code and want to use development tools, you will need to restart the editor
after setup.

Helpful extensions are

 * https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode[AsciiDoc]
 * https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml[YAML]
 * https://marketplace.visualstudio.com/items?itemName=castwide.solargraph[Solargraph] (for a Ruby Language Server)
 * https://marketplace.visualstudio.com/items?itemName=onnovalkering.vscode-singularity[Singularity] (if you plan on working on the container)

The `.vscode/settings.json` file in the repo will ensure that Solargraph works without any additional
configuration (assuming you've already run ./bin/setup).

== Tasks

Quick start:

[source,bash]
----
./do --tasks                 # list all documented tasks

# examples
./do validate                # validate against the schema
./do gen:arch[generic_rv64]  # generate arch spec for the 'generic_rv64' config
----

== More info

 * xref:arch/README.adoc[Architecture specification format]
 * xref:arch/README.adoc[Documentation for the generator tool and IDL]
 ** https://riscv-software-src.github.io/riscv-unified-db/ruby/index.html[YARD docs for the generator tool and IDL]
