# RISC-V Unified Database

The RISC-V Unified Database is intended to hold *all* the information needed to describe RISC-V,
including a list of extensions, instruction specifications, CSR specifications, and documentation prose. The vision is that anything one would need for RISC-V can be generated from the information in this repository.

This repository contains:

 * A (eventually complete) description of the RISC-V specification in a machine-readable format.
 * A tool to generate multiple views of that spec, including:
 ** A configuration-specific, human-readable documentation webpage
 ** [COMING SOON] A configuration-specific Instruction Set Simulator
 ** More backends are planned

## Prerequisites

The only requirement is the `Singularity CE` or `Apptainer` container system. Either one will work (they are forks).

If it is not installed, either as your IT admin or:

 * For Apptainer, see https://apptainer.org/docs/admin/main/installation.html[Apptainer Installation].
 * For Singularity CE, see https://docs.sylabs.io/guides/latest/admin-guide/installation.html[Singularity CE Installation].

[NOTE]
You do *not* need root privileges to download or use the container. However, to modify/build the container,
you will need either root privileges or the ability to run in `fakeroot` mode. See https://docs.sylabs.io/guides/4.1/user-guide/fakeroot.html[Singularity Fakeroot Documentation] for more information.

## Setup

Do once:

[source,bash]
----
./bin/setup

# or, if you also want development tools (:development group in Gemfile) installed
# DEVELOPMENT=1 ./bin/setup
----

[NOTE]
If you forget, don't worry. Setup will be invoked by any program in bin/ if necessary.

### VSCode

If using Visual Studio Code and want to use development tools, you will need to restart the editor
after setup.

Helpful extensions are

 * https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode[AsciiDoc]
 * https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml[YAML]
 * https://marketplace.visualstudio.com/items?itemName=castwide.solargraph[Solargraph] (for a Ruby Language Server)
 * https://marketplace.visualstudio.com/items?itemName=onnovalkering.vscode-singularity[Singularity] (if you plan on working on the container)

The `.vscode/settings.json` file in the repo will ensure that Solargraph works without any additional
configuration (assuming you've already run ./bin/setup).

## Tasks

Quick start:

[source,bash]
----
./do --tasks                 # list all documented tasks

# examples
./do gen:arch[generic_rv64]  # generate arch spec for the 'generic_rv64' config
./do validate                # validate against the schema
----

## More info

 * xref:arch/README.adoc[Architecture specification format]
 * xref:arch/README.adoc[Documentation for the generator tool and IDL]