# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# typed: true
# frozen_string_literal: true

# Add your extra requires here (`bin/tapioca require` can be used to bootstrap this list)
require "active_support/array_inquirer"
require "active_support/core_ext/date/calculations"
require "active_support/core_ext/date_and_time/calculations"
require "active_support/core_ext/date_and_time/zones"
require "active_support/core_ext/string/output_safety"
require "active_support/inflector/methods"
require "active_support/string_inquirer"
require "active_support/testing/error_reporter_assertions"
require "active_support/values/time_zone"
require "asciidoctor"
require "awesome_print"
require "bundler"
require "commander"
require "concurrent"
require "forwardable"
require "idlc"
require "idlc/interfaces"
require "idlc/passes/find_return_values"
require "idlc/passes/gen_adoc"
require "idlc/passes/gen_option_adoc"
require "idlc/passes/prune"
require "idlc/passes/reachable_exceptions"
require "idlc/passes/reachable_functions"
require "idlc/type"
require "json"
require "json_schemer"
require "minitest"
require "pathname"
require "rake/application"
require "simplecov"
require "sorbet-runtime"
require "terminal-table"
require "thor"
require "tilt"
require "tty-exit"
require "tty-option"
require "tty-progressbar"
require "udb/architecture"
require "udb/eqn_parser"
require "udb_helpers/backend_helpers"
require "yaml"
require "z3"
