# SPDX-FileCopyrightText: 2026 Contributors to the RISCV UnifiedDB <https://github.com/riscv/riscv-unified-db>
# SPDX-License-Identifier: BSD-3-Clause-Clear

"""IDL (ISA Description Language) parsing and syntax tree.

This subpackage is a Python port of the syntactic layer of Ruby's IDL
compiler (``tools/ruby-gems/idlc``): a hand-written packrat PEG parser
(:mod:`udb.idl.parser`) that mirrors ``idlc/lib/idlc/idl.treetop`` rule for
rule, and a syntax tree (:mod:`udb.idl.ast`) that mirrors every
``Idl::*Ast`` class's ``to_h``/``to_idl``/``from_h``.

Semantic analysis (type checking, constant evaluation, execution, adoc
generation) is out of scope for this slice and is added to these same node
classes in later migration slices.
"""

from __future__ import annotations

from .ast import (
    ArrayIncludes,
    ArrayLiteral,
    ArraySize,
    AryElementAccess,
    AryElementAssignment,
    AryRangeAccess,
    AryRangeAssignment,
    BinaryExpression,
    BitfieldDefinition,
    BitfieldFieldDefinition,
    BitsCast,
    BuiltinEnumDefinition,
    BuiltinTypeName,
    BuiltinVariable,
    Comment,
    ConcatenationExpression,
    ConditionalReturnStatement,
    ConditionalStatement,
    ConstraintBody,
    CsrFieldAssignment,
    CsrFieldReadExpression,
    CsrFunctionCall,
    CsrReadExpression,
    CsrSoftwareWrite,
    CsrWrite,
    DontCareLvalue,
    DontCareReturn,
    ElseIf,
    EnumArrayCast,
    EnumCast,
    EnumDefinition,
    EnumElementSize,
    EnumRef,
    EnumSize,
    FalseExpression,
    Fetch,
    FieldAccessExpression,
    FieldAssignment,
    ForLoop,
    FunctionBody,
    FunctionCallExpression,
    FunctionDef,
    Global,
    GlobalWithInitialization,
    Id,
    If,
    IfBody,
    ImplicationExpression,
    ImplicationStatement,
    IncludeStatement,
    IntLiteral,
    Isa,
    MultiVariableAssignment,
    MultiVariableDeclaration,
    Node,
    Noop,
    ParenExpression,
    ParseTimeDetectedTypeError,
    PcAssignment,
    PostDecrementExpression,
    PostIncrementExpression,
    ReplicationExpression,
    ReturnExpression,
    ReturnStatement,
    SignCast,
    Statement,
    StringLiteral,
    StructDefinition,
    TernaryOperatorExpression,
    TrueExpression,
    UnaryOperatorExpression,
    UnknownLiteral,
    UserTypeName,
    VariableAssignment,
    VariableDeclaration,
    VariableDeclarationWithInitialization,
    WidthReveal,
    from_h,
)
from .errors import (
    IdlError,
    IdlInternalError,
    IdlSemanticError,
    IdlSyntaxError,
    IdlTypeError,
    IdlValueUnknown,
)
from .parser import (
    ROOTS,
    parse,
    parse_constraint_body,
    parse_expression,
    parse_for_loop,
    parse_function_body,
    parse_instruction_operation,
    parse_isa,
)
from .source import IdlSource

__all__ = [
    "ROOTS",
    "ArrayIncludes",
    "ArrayLiteral",
    "ArraySize",
    "AryElementAccess",
    "AryElementAssignment",
    "AryRangeAccess",
    "AryRangeAssignment",
    "BinaryExpression",
    "BitfieldDefinition",
    "BitfieldFieldDefinition",
    "BitsCast",
    "BuiltinEnumDefinition",
    "BuiltinTypeName",
    "BuiltinVariable",
    "Comment",
    "ConcatenationExpression",
    "ConditionalReturnStatement",
    "ConditionalStatement",
    "ConstraintBody",
    "CsrFieldAssignment",
    "CsrFieldReadExpression",
    "CsrFunctionCall",
    "CsrReadExpression",
    "CsrSoftwareWrite",
    "CsrWrite",
    "DontCareLvalue",
    "DontCareReturn",
    "ElseIf",
    "EnumArrayCast",
    "EnumCast",
    "EnumDefinition",
    "EnumElementSize",
    "EnumRef",
    "EnumSize",
    "FalseExpression",
    "Fetch",
    "FieldAccessExpression",
    "FieldAssignment",
    "ForLoop",
    "FunctionBody",
    "FunctionCallExpression",
    "FunctionDef",
    "Global",
    "GlobalWithInitialization",
    "Id",
    "IdlError",
    "IdlInternalError",
    "IdlSemanticError",
    "IdlSource",
    "IdlSyntaxError",
    "IdlTypeError",
    "IdlValueUnknown",
    "If",
    "IfBody",
    "ImplicationExpression",
    "ImplicationStatement",
    "IncludeStatement",
    "IntLiteral",
    "Isa",
    "MultiVariableAssignment",
    "MultiVariableDeclaration",
    "Node",
    "Noop",
    "ParenExpression",
    "ParseTimeDetectedTypeError",
    "PcAssignment",
    "PostDecrementExpression",
    "PostIncrementExpression",
    "ReplicationExpression",
    "ReturnExpression",
    "ReturnStatement",
    "SignCast",
    "Statement",
    "StringLiteral",
    "StructDefinition",
    "TernaryOperatorExpression",
    "TrueExpression",
    "UnaryOperatorExpression",
    "UnknownLiteral",
    "UserTypeName",
    "VariableAssignment",
    "VariableDeclaration",
    "VariableDeclarationWithInitialization",
    "WidthReveal",
    "from_h",
    "parse",
    "parse_constraint_body",
    "parse_expression",
    "parse_for_loop",
    "parse_function_body",
    "parse_instruction_operation",
    "parse_isa",
]
