# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `bigdecimal` gem.
# Please instead update this file by running `bin/tapioca gem bigdecimal`.


# source://bigdecimal//lib/bigdecimal.rb#8
class BigDecimal < ::Numeric
  # source://bigdecimal//lib/bigdecimal.rb#61
  def **(y); end

  # source://bigdecimal//lib/bigdecimal.rb#81
  def power(y, prec = T.unsafe(nil)); end

  # source://bigdecimal//lib/bigdecimal.rb#185
  def sqrt(prec); end

  # source://bigdecimal//lib/bigdecimal/util.rb#110
  def to_d; end

  # source://bigdecimal//lib/bigdecimal/util.rb#90
  def to_digits; end
end

# source://bigdecimal//lib/bigdecimal.rb#9
module BigDecimal::Internal
  class << self
    # source://bigdecimal//lib/bigdecimal.rb#13
    def coerce_to_bigdecimal(x, prec, method_name); end

    # source://bigdecimal//lib/bigdecimal.rb#34
    def infinity_computation_result; end

    # source://bigdecimal//lib/bigdecimal.rb#41
    def nan_computation_result; end

    # source://bigdecimal//lib/bigdecimal.rb#25
    def validate_prec(prec, method_name, accept_zero: T.unsafe(nil)); end
  end
end

BigDecimal::VERSION = T.let(T.unsafe(nil), String)

# source://bigdecimal//lib/bigdecimal/util.rb#138
class Complex < ::Numeric
  # source://bigdecimal//lib/bigdecimal/util.rb#157
  def to_d(*args); end
end
