# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `minitest` gem.
# Please instead update this file by running `bin/tapioca gem minitest`.


# source://minitest//lib/minitest/parallel.rb#3
module Minitest
  class << self
    # source://minitest//lib/minitest.rb#337
    def __run(reporter, options); end

    # source://minitest//lib/minitest.rb#96
    def after_run(&block); end

    # source://minitest//lib/minitest.rb#20
    def allow_fork; end

    # source://minitest//lib/minitest.rb#20
    def allow_fork=(_arg0); end

    # source://minitest//lib/minitest.rb#70
    def autorun; end

    # source://minitest//lib/minitest.rb#20
    def backtrace_filter; end

    # source://minitest//lib/minitest.rb#20
    def backtrace_filter=(_arg0); end

    # source://minitest//lib/minitest.rb#19
    def cattr_accessor(name); end

    # source://minitest//lib/minitest.rb#1231
    def clock_time; end

    # source://minitest//lib/minitest.rb#317
    def empty_run!(options); end

    # source://minitest//lib/minitest.rb#20
    def extensions; end

    # source://minitest//lib/minitest.rb#20
    def extensions=(_arg0); end

    # source://minitest//lib/minitest.rb#350
    def filter_backtrace(bt); end

    # source://minitest//lib/minitest.rb#20
    def info_signal; end

    # source://minitest//lib/minitest.rb#20
    def info_signal=(_arg0); end

    # source://minitest//lib/minitest.rb#124
    def init_plugins(options); end

    # source://minitest//lib/minitest.rb#108
    def load_plugins; end

    # source://minitest//lib/minitest.rb#20
    def parallel_executor; end

    # source://minitest//lib/minitest.rb#20
    def parallel_executor=(_arg0); end

    # source://minitest//lib/minitest.rb#142
    def process_args(args = T.unsafe(nil)); end

    # source://minitest//lib/minitest.rb#103
    def register_plugin(name_or_mod); end

    # source://minitest//lib/minitest.rb#20
    def reporter; end

    # source://minitest//lib/minitest.rb#20
    def reporter=(_arg0); end

    # source://minitest//lib/minitest.rb#282
    def run(args = T.unsafe(nil)); end

    # source://minitest//lib/minitest.rb#1222
    def run_one_method(klass, method_name); end

    # source://minitest//lib/minitest.rb#20
    def seed; end

    # source://minitest//lib/minitest.rb#20
    def seed=(_arg0); end
  end
end

# source://minitest//lib/minitest.rb#702
class Minitest::AbstractReporter
  # source://minitest//lib/minitest.rb#704
  def initialize; end

  # source://minitest//lib/minitest.rb#739
  def passed?; end

  # source://minitest//lib/minitest.rb#718
  def prerecord(klass, name); end

  # source://minitest//lib/minitest.rb#727
  def record(result); end

  # source://minitest//lib/minitest.rb#733
  def report; end

  # source://minitest//lib/minitest.rb#711
  def start; end

  # source://minitest//lib/minitest.rb#743
  def synchronize(&block); end
end

# source://minitest//lib/minitest.rb#1035
class Minitest::Assertion < ::Exception
  # source://minitest//lib/minitest.rb#1038
  def error; end

  # source://minitest//lib/minitest.rb#1045
  def location; end

  # source://minitest//lib/minitest.rb#1053
  def result_code; end

  # source://minitest//lib/minitest.rb#1057
  def result_label; end
end

# source://minitest//lib/minitest.rb#1036
Minitest::Assertion::RE = T.let(T.unsafe(nil), Regexp)

# source://minitest//lib/minitest/assertions.rb#16
module Minitest::Assertions
  # source://minitest//lib/minitest/assertions.rb#199
  def _caller_uplevel; end

  # source://minitest//lib/minitest/assertions.rb#181
  def _synchronize; end

  # source://minitest//lib/minitest/assertions.rb#194
  def _where; end

  # source://minitest//lib/minitest/assertions.rb#171
  def assert(test, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#188
  def assert_empty(obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#220
  def assert_equal(exp, act, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#241
  def assert_in_delta(exp, act, delta = T.unsafe(nil), msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#253
  def assert_in_epsilon(exp, act, epsilon = T.unsafe(nil), msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#260
  def assert_includes(collection, obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#271
  def assert_instance_of(cls, obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#282
  def assert_kind_of(cls, obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#293
  def assert_match(matcher, obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#305
  def assert_nil(obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#315
  def assert_operator(o1, op, o2 = T.unsafe(nil), msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#333
  def assert_output(stdout = T.unsafe(nil), stderr = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#357
  def assert_path_exists(path, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#376
  def assert_pattern; end

  # source://minitest//lib/minitest/assertions.rb#394
  def assert_predicate(o1, op, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#421
  def assert_raises(*exp); end

  # source://minitest//lib/minitest/assertions.rb#453
  def assert_respond_to(obj, meth, msg = T.unsafe(nil), include_all: T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#463
  def assert_same(exp, act, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#476
  def assert_send(send_ary, m = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#491
  def assert_silent; end

  # source://minitest//lib/minitest/assertions.rb#500
  def assert_throws(sym, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#536
  def capture_io; end

  # source://minitest//lib/minitest/assertions.rb#569
  def capture_subprocess_io; end

  # source://minitest//lib/minitest/assertions.rb#57
  def diff(exp, act); end

  # source://minitest//lib/minitest/assertions.rb#601
  def exception_details(e, msg); end

  # source://minitest//lib/minitest/assertions.rb#617
  def fail_after(y, m, d, msg); end

  # source://minitest//lib/minitest/assertions.rb#624
  def flunk(msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#632
  def message(msg = T.unsafe(nil), ending = T.unsafe(nil), &default); end

  # source://minitest//lib/minitest/assertions.rb#127
  def mu_pp(obj); end

  # source://minitest//lib/minitest/assertions.rb#145
  def mu_pp_for_diff(obj); end

  # source://minitest//lib/minitest/assertions.rb#643
  def pass(_msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#650
  def refute(test, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#658
  def refute_empty(obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#669
  def refute_equal(exp, act, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#681
  def refute_in_delta(exp, act, delta = T.unsafe(nil), msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#693
  def refute_in_epsilon(exp, act, epsilon = T.unsafe(nil), msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#700
  def refute_includes(collection, obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#711
  def refute_instance_of(cls, obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#721
  def refute_kind_of(cls, obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#729
  def refute_match(matcher, obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#739
  def refute_nil(obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#771
  def refute_operator(o1, op, o2 = T.unsafe(nil), msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#780
  def refute_path_exists(path, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#756
  def refute_pattern; end

  # source://minitest//lib/minitest/assertions.rb#794
  def refute_predicate(o1, op, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#803
  def refute_respond_to(obj, meth, msg = T.unsafe(nil), include_all: T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#812
  def refute_same(exp, act, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#825
  def skip(msg = T.unsafe(nil), _ignored = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#837
  def skip_until(y, m, d, msg); end

  # source://minitest//lib/minitest/assertions.rb#846
  def skipped?; end

  # source://minitest//lib/minitest/assertions.rb#102
  def things_to_diff(exp, act); end

  class << self
    # source://minitest//lib/minitest/assertions.rb#27
    def diff; end

    # source://minitest//lib/minitest/assertions.rb#45
    def diff=(o); end
  end
end

# source://minitest//lib/minitest/assertions.rb#205
Minitest::Assertions::E = T.let(T.unsafe(nil), String)

# source://minitest//lib/minitest/assertions.rb#17
Minitest::Assertions::UNDEFINED = T.let(T.unsafe(nil), Object)

# source://minitest//lib/minitest.rb#1190
class Minitest::BacktraceFilter
  # source://minitest//lib/minitest.rb#1199
  def initialize(regexp = T.unsafe(nil)); end

  # source://minitest//lib/minitest.rb#1207
  def filter(bt); end

  # source://minitest//lib/minitest.rb#1197
  def regexp; end

  # source://minitest//lib/minitest.rb#1197
  def regexp=(_arg0); end
end

# source://minitest//lib/minitest.rb#1192
Minitest::BacktraceFilter::MT_RE = T.let(T.unsafe(nil), Regexp)

# source://minitest//lib/minitest.rb#984
class Minitest::CompositeReporter < ::Minitest::AbstractReporter
  # source://minitest//lib/minitest.rb#990
  def initialize(*reporters); end

  # source://minitest//lib/minitest.rb#1002
  def <<(reporter); end

  # source://minitest//lib/minitest.rb#995
  def io; end

  # source://minitest//lib/minitest.rb#1006
  def passed?; end

  # source://minitest//lib/minitest.rb#1014
  def prerecord(klass, name); end

  # source://minitest//lib/minitest.rb#1021
  def record(result); end

  # source://minitest//lib/minitest.rb#1027
  def report; end

  # source://minitest//lib/minitest.rb#988
  def reporters; end

  # source://minitest//lib/minitest.rb#988
  def reporters=(_arg0); end

  # source://minitest//lib/minitest.rb#1010
  def start; end
end

# source://minitest//lib/minitest/compress.rb#5
module Minitest::Compress
  # source://minitest//lib/minitest/compress.rb#11
  def compress(orig); end
end

# source://minitest//lib/minitest.rb#1134
module Minitest::Guard
  # source://minitest//lib/minitest.rb#1139
  def jruby?(platform = T.unsafe(nil)); end

  # source://minitest//lib/minitest.rb#1146
  def maglev?(platform = T.unsafe(nil)); end

  # source://minitest//lib/minitest.rb#1156
  def mri?(platform = T.unsafe(nil)); end

  # source://minitest//lib/minitest.rb#1163
  def osx?(platform = T.unsafe(nil)); end

  # source://minitest//lib/minitest.rb#1170
  def rubinius?(platform = T.unsafe(nil)); end

  # source://minitest//lib/minitest.rb#1180
  def windows?(platform = T.unsafe(nil)); end
end

# source://minitest//lib/minitest/parallel.rb#4
module Minitest::Parallel; end

# source://minitest//lib/minitest/parallel.rb#9
class Minitest::Parallel::Executor
  # source://minitest//lib/minitest/parallel.rb#19
  def initialize(size); end

  # source://minitest//lib/minitest/parallel.rb#45
  def <<(work); end

  # source://minitest//lib/minitest/parallel.rb#52
  def shutdown; end

  # source://minitest//lib/minitest/parallel.rb#14
  def size; end

  # source://minitest//lib/minitest/parallel.rb#28
  def start; end
end

# source://minitest//lib/minitest/parallel.rb#58
module Minitest::Parallel::Test
  # source://minitest//lib/minitest/parallel.rb#59
  def _synchronize; end
end

# source://minitest//lib/minitest/parallel.rb#61
module Minitest::Parallel::Test::ClassMethods
  # source://minitest//lib/minitest/parallel.rb#62
  def run_one_method(klass, method_name, reporter); end

  # source://minitest//lib/minitest/parallel.rb#66
  def test_order; end
end

# source://minitest//lib/minitest.rb#774
class Minitest::ProgressReporter < ::Minitest::Reporter
  # source://minitest//lib/minitest.rb#775
  def prerecord(klass, name); end

  # source://minitest//lib/minitest.rb#782
  def record(result); end
end

# source://minitest//lib/minitest.rb#596
module Minitest::Reportable
  # source://minitest//lib/minitest.rb#618
  def class_name; end

  # source://minitest//lib/minitest.rb#639
  def error?; end

  # source://minitest//lib/minitest.rb#613
  def location; end

  # source://minitest//lib/minitest.rb#603
  def passed?; end

  # source://minitest//lib/minitest.rb#625
  def result_code; end

  # source://minitest//lib/minitest.rb#632
  def skipped?; end
end

# source://minitest//lib/minitest.rb#607
Minitest::Reportable::BASE_DIR = T.let(T.unsafe(nil), String)

# source://minitest//lib/minitest.rb#750
class Minitest::Reporter < ::Minitest::AbstractReporter
  # source://minitest//lib/minitest.rb#759
  def initialize(io = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://minitest//lib/minitest.rb#752
  def io; end

  # source://minitest//lib/minitest.rb#752
  def io=(_arg0); end

  # source://minitest//lib/minitest.rb#757
  def options; end

  # source://minitest//lib/minitest.rb#757
  def options=(_arg0); end
end

# source://minitest//lib/minitest.rb#651
class Minitest::Result < ::Minitest::Runnable
  include ::Minitest::Reportable

  # source://minitest//lib/minitest.rb#685
  def class_name; end

  # source://minitest//lib/minitest.rb#660
  def klass; end

  # source://minitest//lib/minitest.rb#660
  def klass=(_arg0); end

  # source://minitest//lib/minitest.rb#665
  def source_location; end

  # source://minitest//lib/minitest.rb#665
  def source_location=(_arg0); end

  # source://minitest//lib/minitest.rb#689
  def to_s; end

  class << self
    # source://minitest//lib/minitest.rb#670
    def from(runnable); end
  end
end

# source://minitest//lib/minitest.rb#363
class Minitest::Runnable
  # source://minitest//lib/minitest.rb#527
  def initialize(name); end

  # source://minitest//lib/minitest.rb#367
  def assertions; end

  # source://minitest//lib/minitest.rb#367
  def assertions=(_arg0); end

  # source://minitest//lib/minitest.rb#523
  def failure; end

  # source://minitest//lib/minitest.rb#372
  def failures; end

  # source://minitest//lib/minitest.rb#372
  def failures=(_arg0); end

  # source://minitest//lib/minitest.rb#509
  def marshal_dump; end

  # source://minitest//lib/minitest.rb#519
  def marshal_load(ary); end

  # source://minitest//lib/minitest.rb#542
  def metadata; end

  # source://minitest//lib/minitest.rb#549
  def metadata=(_arg0); end

  # source://minitest//lib/minitest.rb#554
  def metadata?; end

  # source://minitest//lib/minitest.rb#390
  def name; end

  # source://minitest//lib/minitest.rb#397
  def name=(o); end

  # source://minitest//lib/minitest.rb#571
  def passed?; end

  # source://minitest//lib/minitest.rb#580
  def result_code; end

  # source://minitest//lib/minitest.rb#561
  def run; end

  # source://minitest//lib/minitest.rb#587
  def skipped?; end

  # source://minitest//lib/minitest.rb#377
  def time; end

  # source://minitest//lib/minitest.rb#377
  def time=(_arg0); end

  # source://minitest//lib/minitest.rb#379
  def time_it; end

  class << self
    # source://minitest//lib/minitest.rb#1241
    def inherited(klass); end

    # source://minitest//lib/minitest.rb#404
    def methods_matching(re); end

    # source://minitest//lib/minitest.rb#479
    def on_signal(name, action); end

    # source://minitest//lib/minitest.rb#408
    def reset; end

    # source://minitest//lib/minitest.rb#419
    def run(reporter, options = T.unsafe(nil)); end

    # source://minitest//lib/minitest.rb#460
    def run_one_method(klass, method_name, reporter); end

    # source://minitest//lib/minitest.rb#496
    def runnable_methods; end

    # source://minitest//lib/minitest.rb#503
    def runnables; end

    # source://minitest//lib/minitest.rb#469
    def test_order; end

    # source://minitest//lib/minitest.rb#473
    def with_info_handler(reporter, &block); end
  end
end

# source://minitest//lib/minitest.rb#477
Minitest::Runnable::SIGNALS = T.let(T.unsafe(nil), Hash)

# source://minitest//lib/minitest.rb#1065
class Minitest::Skip < ::Minitest::Assertion
  # source://minitest//lib/minitest.rb#1066
  def result_label; end
end

# source://minitest//lib/minitest.rb#810
class Minitest::StatisticsReporter < ::Minitest::Reporter
  # source://minitest//lib/minitest.rb#859
  def initialize(io = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://minitest//lib/minitest.rb#814
  def assertions; end

  # source://minitest//lib/minitest.rb#814
  def assertions=(_arg0); end

  # source://minitest//lib/minitest.rb#819
  def count; end

  # source://minitest//lib/minitest.rb#819
  def count=(_arg0); end

  # source://minitest//lib/minitest.rb#847
  def errors; end

  # source://minitest//lib/minitest.rb#847
  def errors=(_arg0); end

  # source://minitest//lib/minitest.rb#842
  def failures; end

  # source://minitest//lib/minitest.rb#842
  def failures=(_arg0); end

  # source://minitest//lib/minitest.rb#873
  def passed?; end

  # source://minitest//lib/minitest.rb#881
  def record(result); end

  # source://minitest//lib/minitest.rb#891
  def report; end

  # source://minitest//lib/minitest.rb#824
  def results; end

  # source://minitest//lib/minitest.rb#824
  def results=(_arg0); end

  # source://minitest//lib/minitest.rb#857
  def skips; end

  # source://minitest//lib/minitest.rb#857
  def skips=(_arg0); end

  # source://minitest//lib/minitest.rb#877
  def start; end

  # source://minitest//lib/minitest.rb#831
  def start_time; end

  # source://minitest//lib/minitest.rb#831
  def start_time=(_arg0); end

  # source://minitest//lib/minitest.rb#837
  def total_time; end

  # source://minitest//lib/minitest.rb#837
  def total_time=(_arg0); end

  # source://minitest//lib/minitest.rb#852
  def warnings; end

  # source://minitest//lib/minitest.rb#852
  def warnings=(_arg0); end
end

# source://minitest//lib/minitest.rb#912
class Minitest::SummaryReporter < ::Minitest::StatisticsReporter
  # source://minitest//lib/minitest.rb#945
  def aggregated_results(io); end

  # source://minitest//lib/minitest.rb#914
  def old_sync; end

  # source://minitest//lib/minitest.rb#914
  def old_sync=(_arg0); end

  # source://minitest//lib/minitest.rb#928
  def report; end

  # source://minitest//lib/minitest.rb#916
  def start; end

  # source://minitest//lib/minitest.rb#940
  def statistics; end

  # source://minitest//lib/minitest.rb#965
  def summary; end

  # source://minitest//lib/minitest.rb#913
  def sync; end

  # source://minitest//lib/minitest.rb#913
  def sync=(_arg0); end

  # source://minitest//lib/minitest.rb#961
  def to_s; end
end

# source://minitest//lib/minitest/test.rb#10
class Minitest::Test < ::Minitest::Runnable
  include ::Minitest::Reportable
  include ::Minitest::Assertions
  include ::Minitest::Test::LifecycleHooks
  include ::Minitest::Guard
  extend ::Minitest::Guard

  # source://minitest//lib/minitest/test.rb#190
  def capture_exceptions; end

  # source://minitest//lib/minitest/test.rb#15
  def class_name; end

  # source://minitest//lib/minitest/test.rb#207
  def neuter_exception(e); end

  # source://minitest//lib/minitest/test.rb#218
  def new_exception(klass, msg, bt, kill = T.unsafe(nil)); end

  # source://minitest//lib/minitest/test.rb#88
  def run; end

  # source://minitest//lib/minitest/test.rb#200
  def sanitize_exception(e); end

  class << self
    # source://minitest//lib/minitest/test.rb#35
    def i_suck_and_my_tests_are_order_dependent!; end

    # source://minitest//lib/minitest/test.rb#26
    def io_lock; end

    # source://minitest//lib/minitest/test.rb#26
    def io_lock=(_arg0); end

    # source://minitest//lib/minitest/test.rb#48
    def make_my_diffs_pretty!; end

    # source://minitest//lib/minitest/test.rb#60
    def parallelize_me!; end

    # source://minitest//lib/minitest/test.rb#71
    def runnable_methods; end
  end
end

# source://minitest//lib/minitest/test.rb#113
module Minitest::Test::LifecycleHooks
  # source://minitest//lib/minitest/test.rb#163
  def after_setup; end

  # source://minitest//lib/minitest/test.rb#187
  def after_teardown; end

  # source://minitest//lib/minitest/test.rb#148
  def before_setup; end

  # source://minitest//lib/minitest/test.rb#172
  def before_teardown; end

  # source://minitest//lib/minitest/test.rb#154
  def setup; end

  # source://minitest//lib/minitest/test.rb#178
  def teardown; end
end

# source://minitest//lib/minitest/test.rb#19
Minitest::Test::PASSTHROUGH_EXCEPTIONS = T.let(T.unsafe(nil), Array)

# source://minitest//lib/minitest/test.rb#21
Minitest::Test::SETUP_METHODS = T.let(T.unsafe(nil), Array)

# source://minitest//lib/minitest/test.rb#23
Minitest::Test::TEARDOWN_METHODS = T.let(T.unsafe(nil), Array)

# source://minitest//lib/minitest.rb#1074
class Minitest::UnexpectedError < ::Minitest::Assertion
  include ::Minitest::Compress

  # source://minitest//lib/minitest.rb#1080
  def initialize(error); end

  # source://minitest//lib/minitest.rb#1093
  def backtrace; end

  # source://minitest//lib/minitest.rb#1078
  def error; end

  # source://minitest//lib/minitest.rb#1078
  def error=(_arg0); end

  # source://minitest//lib/minitest.rb#1099
  def message; end

  # source://minitest//lib/minitest.rb#1105
  def result_label; end
end

# source://minitest//lib/minitest.rb#1097
Minitest::UnexpectedError::BASE_RE = T.let(T.unsafe(nil), Regexp)

# source://minitest//lib/minitest.rb#1113
class Minitest::UnexpectedWarning < ::Minitest::Assertion
  # source://minitest//lib/minitest.rb#1114
  def result_label; end
end

# source://minitest//lib/minitest.rb#13
Minitest::VERSION = T.let(T.unsafe(nil), String)
