# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `minitest` gem.
# Please instead update this file by running `bin/tapioca gem minitest`.


# source://minitest//lib/minitest/parallel.rb#3
module Minitest
  class << self
    # source://minitest//lib/minitest.rb#338
    def __run(reporter, options); end

    # source://minitest//lib/minitest.rb#97
    def after_run(&block); end

    # source://minitest//lib/minitest.rb#20
    def allow_fork; end

    # source://minitest//lib/minitest.rb#20
    def allow_fork=(_arg0); end

    # source://minitest//lib/minitest.rb#70
    def autorun; end

    # source://minitest//lib/minitest.rb#20
    def backtrace_filter; end

    # source://minitest//lib/minitest.rb#20
    def backtrace_filter=(_arg0); end

    # source://minitest//lib/minitest.rb#19
    def cattr_accessor(name); end

    # source://minitest//lib/minitest.rb#1232
    def clock_time; end

    # source://minitest//lib/minitest.rb#318
    def empty_run!(options); end

    # source://minitest//lib/minitest.rb#20
    def extensions; end

    # source://minitest//lib/minitest.rb#20
    def extensions=(_arg0); end

    # source://minitest//lib/minitest.rb#351
    def filter_backtrace(bt); end

    # source://minitest//lib/minitest.rb#20
    def info_signal; end

    # source://minitest//lib/minitest.rb#20
    def info_signal=(_arg0); end

    # source://minitest//lib/minitest.rb#125
    def init_plugins(options); end

    # source://minitest//lib/minitest.rb#109
    def load_plugins; end

    # source://minitest//lib/minitest.rb#20
    def parallel_executor; end

    # source://minitest//lib/minitest.rb#20
    def parallel_executor=(_arg0); end

    # source://minitest//lib/minitest.rb#143
    def process_args(args = T.unsafe(nil)); end

    # source://minitest//lib/minitest.rb#104
    def register_plugin(name_or_mod); end

    # source://minitest//lib/minitest.rb#20
    def reporter; end

    # source://minitest//lib/minitest.rb#20
    def reporter=(_arg0); end

    # source://minitest//lib/minitest.rb#283
    def run(args = T.unsafe(nil)); end

    # source://minitest//lib/minitest.rb#1223
    def run_one_method(klass, method_name); end

    # source://minitest//lib/minitest.rb#20
    def seed; end

    # source://minitest//lib/minitest.rb#20
    def seed=(_arg0); end
  end
end

# source://minitest//lib/minitest.rb#703
class Minitest::AbstractReporter
  # source://minitest//lib/minitest.rb#705
  def initialize; end

  # source://minitest//lib/minitest.rb#740
  def passed?; end

  # source://minitest//lib/minitest.rb#719
  def prerecord(klass, name); end

  # source://minitest//lib/minitest.rb#728
  def record(result); end

  # source://minitest//lib/minitest.rb#734
  def report; end

  # source://minitest//lib/minitest.rb#712
  def start; end

  # source://minitest//lib/minitest.rb#744
  def synchronize(&block); end
end

# source://minitest//lib/minitest.rb#1036
class Minitest::Assertion < ::Exception
  # source://minitest//lib/minitest.rb#1039
  def error; end

  # source://minitest//lib/minitest.rb#1046
  def location; end

  # source://minitest//lib/minitest.rb#1054
  def result_code; end

  # source://minitest//lib/minitest.rb#1058
  def result_label; end
end

# source://minitest//lib/minitest.rb#1037
Minitest::Assertion::RE = T.let(T.unsafe(nil), Regexp)

# source://minitest//lib/minitest/assertions.rb#16
module Minitest::Assertions
  # source://minitest//lib/minitest/assertions.rb#181
  def _synchronize; end

  # source://minitest//lib/minitest/assertions.rb#194
  def _where; end

  # source://minitest//lib/minitest/assertions.rb#171
  def assert(test, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#188
  def assert_empty(obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#214
  def assert_equal(exp, act, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#235
  def assert_in_delta(exp, act, delta = T.unsafe(nil), msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#247
  def assert_in_epsilon(exp, act, epsilon = T.unsafe(nil), msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#254
  def assert_includes(collection, obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#265
  def assert_instance_of(cls, obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#276
  def assert_kind_of(cls, obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#287
  def assert_match(matcher, obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#299
  def assert_nil(obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#309
  def assert_operator(o1, op, o2 = T.unsafe(nil), msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#327
  def assert_output(stdout = T.unsafe(nil), stderr = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#351
  def assert_path_exists(path, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#370
  def assert_pattern; end

  # source://minitest//lib/minitest/assertions.rb#391
  def assert_predicate(o1, op, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#418
  def assert_raises(*exp); end

  # source://minitest//lib/minitest/assertions.rb#450
  def assert_respond_to(obj, meth, msg = T.unsafe(nil), include_all: T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#460
  def assert_same(exp, act, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#473
  def assert_send(send_ary, m = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#488
  def assert_silent; end

  # source://minitest//lib/minitest/assertions.rb#497
  def assert_throws(sym, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#533
  def capture_io; end

  # source://minitest//lib/minitest/assertions.rb#566
  def capture_subprocess_io; end

  # source://minitest//lib/minitest/assertions.rb#57
  def diff(exp, act); end

  # source://minitest//lib/minitest/assertions.rb#598
  def exception_details(e, msg); end

  # source://minitest//lib/minitest/assertions.rb#614
  def fail_after(y, m, d, msg); end

  # source://minitest//lib/minitest/assertions.rb#621
  def flunk(msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#629
  def message(msg = T.unsafe(nil), ending = T.unsafe(nil), &default); end

  # source://minitest//lib/minitest/assertions.rb#127
  def mu_pp(obj); end

  # source://minitest//lib/minitest/assertions.rb#145
  def mu_pp_for_diff(obj); end

  # source://minitest//lib/minitest/assertions.rb#640
  def pass(_msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#647
  def refute(test, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#655
  def refute_empty(obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#666
  def refute_equal(exp, act, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#678
  def refute_in_delta(exp, act, delta = T.unsafe(nil), msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#690
  def refute_in_epsilon(exp, act, epsilon = T.unsafe(nil), msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#697
  def refute_includes(collection, obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#708
  def refute_instance_of(cls, obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#718
  def refute_kind_of(cls, obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#726
  def refute_match(matcher, obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#736
  def refute_nil(obj, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#771
  def refute_operator(o1, op, o2 = T.unsafe(nil), msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#780
  def refute_path_exists(path, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#753
  def refute_pattern; end

  # source://minitest//lib/minitest/assertions.rb#794
  def refute_predicate(o1, op, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#803
  def refute_respond_to(obj, meth, msg = T.unsafe(nil), include_all: T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#812
  def refute_same(exp, act, msg = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#825
  def skip(msg = T.unsafe(nil), _ignored = T.unsafe(nil)); end

  # source://minitest//lib/minitest/assertions.rb#837
  def skip_until(y, m, d, msg); end

  # source://minitest//lib/minitest/assertions.rb#846
  def skipped?; end

  # source://minitest//lib/minitest/assertions.rb#102
  def things_to_diff(exp, act); end

  class << self
    # source://minitest//lib/minitest/assertions.rb#27
    def diff; end

    # source://minitest//lib/minitest/assertions.rb#45
    def diff=(o); end
  end
end

# source://minitest//lib/minitest/assertions.rb#199
Minitest::Assertions::E = T.let(T.unsafe(nil), String)

# source://minitest//lib/minitest/assertions.rb#17
Minitest::Assertions::UNDEFINED = T.let(T.unsafe(nil), Object)

# source://minitest//lib/minitest.rb#1191
class Minitest::BacktraceFilter
  # source://minitest//lib/minitest.rb#1200
  def initialize(regexp = T.unsafe(nil)); end

  # source://minitest//lib/minitest.rb#1208
  def filter(bt); end

  # source://minitest//lib/minitest.rb#1198
  def regexp; end

  # source://minitest//lib/minitest.rb#1198
  def regexp=(_arg0); end
end

# source://minitest//lib/minitest.rb#1193
Minitest::BacktraceFilter::MT_RE = T.let(T.unsafe(nil), Regexp)

# source://minitest//lib/minitest.rb#985
class Minitest::CompositeReporter < ::Minitest::AbstractReporter
  # source://minitest//lib/minitest.rb#991
  def initialize(*reporters); end

  # source://minitest//lib/minitest.rb#1003
  def <<(reporter); end

  # source://minitest//lib/minitest.rb#996
  def io; end

  # source://minitest//lib/minitest.rb#1007
  def passed?; end

  # source://minitest//lib/minitest.rb#1015
  def prerecord(klass, name); end

  # source://minitest//lib/minitest.rb#1022
  def record(result); end

  # source://minitest//lib/minitest.rb#1028
  def report; end

  # source://minitest//lib/minitest.rb#989
  def reporters; end

  # source://minitest//lib/minitest.rb#989
  def reporters=(_arg0); end

  # source://minitest//lib/minitest.rb#1011
  def start; end
end

# source://minitest//lib/minitest/compress.rb#5
module Minitest::Compress
  # source://minitest//lib/minitest/compress.rb#11
  def compress(orig); end
end

# source://minitest//lib/minitest.rb#1135
module Minitest::Guard
  # source://minitest//lib/minitest.rb#1140
  def jruby?(platform = T.unsafe(nil)); end

  # source://minitest//lib/minitest.rb#1147
  def maglev?(platform = T.unsafe(nil)); end

  # source://minitest//lib/minitest.rb#1157
  def mri?(platform = T.unsafe(nil)); end

  # source://minitest//lib/minitest.rb#1164
  def osx?(platform = T.unsafe(nil)); end

  # source://minitest//lib/minitest.rb#1171
  def rubinius?(platform = T.unsafe(nil)); end

  # source://minitest//lib/minitest.rb#1181
  def windows?(platform = T.unsafe(nil)); end
end

# source://minitest//lib/minitest/parallel.rb#4
module Minitest::Parallel; end

# source://minitest//lib/minitest/parallel.rb#9
class Minitest::Parallel::Executor
  # source://minitest//lib/minitest/parallel.rb#19
  def initialize(size); end

  # source://minitest//lib/minitest/parallel.rb#45
  def <<(work); end

  # source://minitest//lib/minitest/parallel.rb#52
  def shutdown; end

  # source://minitest//lib/minitest/parallel.rb#14
  def size; end

  # source://minitest//lib/minitest/parallel.rb#28
  def start; end
end

# source://minitest//lib/minitest/parallel.rb#58
module Minitest::Parallel::Test
  # source://minitest//lib/minitest/parallel.rb#59
  def _synchronize; end
end

# source://minitest//lib/minitest/parallel.rb#61
module Minitest::Parallel::Test::ClassMethods
  # source://minitest//lib/minitest/parallel.rb#62
  def run_one_method(klass, method_name, reporter); end

  # source://minitest//lib/minitest/parallel.rb#66
  def test_order; end
end

# source://minitest//lib/minitest.rb#775
class Minitest::ProgressReporter < ::Minitest::Reporter
  # source://minitest//lib/minitest.rb#776
  def prerecord(klass, name); end

  # source://minitest//lib/minitest.rb#783
  def record(result); end
end

# source://minitest//lib/minitest.rb#597
module Minitest::Reportable
  # source://minitest//lib/minitest.rb#619
  def class_name; end

  # source://minitest//lib/minitest.rb#640
  def error?; end

  # source://minitest//lib/minitest.rb#614
  def location; end

  # source://minitest//lib/minitest.rb#604
  def passed?; end

  # source://minitest//lib/minitest.rb#626
  def result_code; end

  # source://minitest//lib/minitest.rb#633
  def skipped?; end
end

# source://minitest//lib/minitest.rb#608
Minitest::Reportable::BASE_DIR = T.let(T.unsafe(nil), String)

# source://minitest//lib/minitest.rb#751
class Minitest::Reporter < ::Minitest::AbstractReporter
  # source://minitest//lib/minitest.rb#760
  def initialize(io = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://minitest//lib/minitest.rb#753
  def io; end

  # source://minitest//lib/minitest.rb#753
  def io=(_arg0); end

  # source://minitest//lib/minitest.rb#758
  def options; end

  # source://minitest//lib/minitest.rb#758
  def options=(_arg0); end
end

# source://minitest//lib/minitest.rb#652
class Minitest::Result < ::Minitest::Runnable
  include ::Minitest::Reportable

  # source://minitest//lib/minitest.rb#686
  def class_name; end

  # source://minitest//lib/minitest.rb#661
  def klass; end

  # source://minitest//lib/minitest.rb#661
  def klass=(_arg0); end

  # source://minitest//lib/minitest.rb#666
  def source_location; end

  # source://minitest//lib/minitest.rb#666
  def source_location=(_arg0); end

  # source://minitest//lib/minitest.rb#690
  def to_s; end

  class << self
    # source://minitest//lib/minitest.rb#671
    def from(runnable); end
  end
end

# source://minitest//lib/minitest.rb#364
class Minitest::Runnable
  # source://minitest//lib/minitest.rb#528
  def initialize(name); end

  # source://minitest//lib/minitest.rb#368
  def assertions; end

  # source://minitest//lib/minitest.rb#368
  def assertions=(_arg0); end

  # source://minitest//lib/minitest.rb#524
  def failure; end

  # source://minitest//lib/minitest.rb#373
  def failures; end

  # source://minitest//lib/minitest.rb#373
  def failures=(_arg0); end

  # source://minitest//lib/minitest.rb#510
  def marshal_dump; end

  # source://minitest//lib/minitest.rb#520
  def marshal_load(ary); end

  # source://minitest//lib/minitest.rb#543
  def metadata; end

  # source://minitest//lib/minitest.rb#550
  def metadata=(_arg0); end

  # source://minitest//lib/minitest.rb#555
  def metadata?; end

  # source://minitest//lib/minitest.rb#391
  def name; end

  # source://minitest//lib/minitest.rb#398
  def name=(o); end

  # source://minitest//lib/minitest.rb#572
  def passed?; end

  # source://minitest//lib/minitest.rb#581
  def result_code; end

  # source://minitest//lib/minitest.rb#562
  def run; end

  # source://minitest//lib/minitest.rb#588
  def skipped?; end

  # source://minitest//lib/minitest.rb#378
  def time; end

  # source://minitest//lib/minitest.rb#378
  def time=(_arg0); end

  # source://minitest//lib/minitest.rb#380
  def time_it; end

  class << self
    # source://minitest//lib/minitest.rb#1242
    def inherited(klass); end

    # source://minitest//lib/minitest.rb#405
    def methods_matching(re); end

    # source://minitest//lib/minitest.rb#480
    def on_signal(name, action); end

    # source://minitest//lib/minitest.rb#409
    def reset; end

    # source://minitest//lib/minitest.rb#420
    def run(reporter, options = T.unsafe(nil)); end

    # source://minitest//lib/minitest.rb#461
    def run_one_method(klass, method_name, reporter); end

    # source://minitest//lib/minitest.rb#497
    def runnable_methods; end

    # source://minitest//lib/minitest.rb#504
    def runnables; end

    # source://minitest//lib/minitest.rb#470
    def test_order; end

    # source://minitest//lib/minitest.rb#474
    def with_info_handler(reporter, &block); end
  end
end

# source://minitest//lib/minitest.rb#478
Minitest::Runnable::SIGNALS = T.let(T.unsafe(nil), Hash)

# source://minitest//lib/minitest.rb#1066
class Minitest::Skip < ::Minitest::Assertion
  # source://minitest//lib/minitest.rb#1067
  def result_label; end
end

# source://minitest//lib/minitest.rb#811
class Minitest::StatisticsReporter < ::Minitest::Reporter
  # source://minitest//lib/minitest.rb#860
  def initialize(io = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://minitest//lib/minitest.rb#815
  def assertions; end

  # source://minitest//lib/minitest.rb#815
  def assertions=(_arg0); end

  # source://minitest//lib/minitest.rb#820
  def count; end

  # source://minitest//lib/minitest.rb#820
  def count=(_arg0); end

  # source://minitest//lib/minitest.rb#848
  def errors; end

  # source://minitest//lib/minitest.rb#848
  def errors=(_arg0); end

  # source://minitest//lib/minitest.rb#843
  def failures; end

  # source://minitest//lib/minitest.rb#843
  def failures=(_arg0); end

  # source://minitest//lib/minitest.rb#874
  def passed?; end

  # source://minitest//lib/minitest.rb#882
  def record(result); end

  # source://minitest//lib/minitest.rb#892
  def report; end

  # source://minitest//lib/minitest.rb#825
  def results; end

  # source://minitest//lib/minitest.rb#825
  def results=(_arg0); end

  # source://minitest//lib/minitest.rb#858
  def skips; end

  # source://minitest//lib/minitest.rb#858
  def skips=(_arg0); end

  # source://minitest//lib/minitest.rb#878
  def start; end

  # source://minitest//lib/minitest.rb#832
  def start_time; end

  # source://minitest//lib/minitest.rb#832
  def start_time=(_arg0); end

  # source://minitest//lib/minitest.rb#838
  def total_time; end

  # source://minitest//lib/minitest.rb#838
  def total_time=(_arg0); end

  # source://minitest//lib/minitest.rb#853
  def warnings; end

  # source://minitest//lib/minitest.rb#853
  def warnings=(_arg0); end
end

# source://minitest//lib/minitest.rb#913
class Minitest::SummaryReporter < ::Minitest::StatisticsReporter
  # source://minitest//lib/minitest.rb#946
  def aggregated_results(io); end

  # source://minitest//lib/minitest.rb#915
  def old_sync; end

  # source://minitest//lib/minitest.rb#915
  def old_sync=(_arg0); end

  # source://minitest//lib/minitest.rb#929
  def report; end

  # source://minitest//lib/minitest.rb#917
  def start; end

  # source://minitest//lib/minitest.rb#941
  def statistics; end

  # source://minitest//lib/minitest.rb#966
  def summary; end

  # source://minitest//lib/minitest.rb#914
  def sync; end

  # source://minitest//lib/minitest.rb#914
  def sync=(_arg0); end

  # source://minitest//lib/minitest.rb#962
  def to_s; end
end

# source://minitest//lib/minitest/test.rb#10
class Minitest::Test < ::Minitest::Runnable
  include ::Minitest::Reportable
  include ::Minitest::Assertions
  include ::Minitest::Test::LifecycleHooks
  include ::Minitest::Guard
  extend ::Minitest::Guard

  # source://minitest//lib/minitest/test.rb#190
  def capture_exceptions; end

  # source://minitest//lib/minitest/test.rb#15
  def class_name; end

  # source://minitest//lib/minitest/test.rb#207
  def neuter_exception(e); end

  # source://minitest//lib/minitest/test.rb#218
  def new_exception(klass, msg, bt, kill = T.unsafe(nil)); end

  # source://minitest//lib/minitest/test.rb#88
  def run; end

  # source://minitest//lib/minitest/test.rb#200
  def sanitize_exception(e); end

  class << self
    # source://minitest//lib/minitest/test.rb#35
    def i_suck_and_my_tests_are_order_dependent!; end

    # source://minitest//lib/minitest/test.rb#26
    def io_lock; end

    # source://minitest//lib/minitest/test.rb#26
    def io_lock=(_arg0); end

    # source://minitest//lib/minitest/test.rb#48
    def make_my_diffs_pretty!; end

    # source://minitest//lib/minitest/test.rb#60
    def parallelize_me!; end

    # source://minitest//lib/minitest/test.rb#71
    def runnable_methods; end
  end
end

# source://minitest//lib/minitest/test.rb#113
module Minitest::Test::LifecycleHooks
  # source://minitest//lib/minitest/test.rb#163
  def after_setup; end

  # source://minitest//lib/minitest/test.rb#187
  def after_teardown; end

  # source://minitest//lib/minitest/test.rb#148
  def before_setup; end

  # source://minitest//lib/minitest/test.rb#172
  def before_teardown; end

  # source://minitest//lib/minitest/test.rb#154
  def setup; end

  # source://minitest//lib/minitest/test.rb#178
  def teardown; end
end

# source://minitest//lib/minitest/test.rb#19
Minitest::Test::PASSTHROUGH_EXCEPTIONS = T.let(T.unsafe(nil), Array)

# source://minitest//lib/minitest/test.rb#21
Minitest::Test::SETUP_METHODS = T.let(T.unsafe(nil), Array)

# source://minitest//lib/minitest/test.rb#23
Minitest::Test::TEARDOWN_METHODS = T.let(T.unsafe(nil), Array)

# source://minitest//lib/minitest.rb#1075
class Minitest::UnexpectedError < ::Minitest::Assertion
  include ::Minitest::Compress

  # source://minitest//lib/minitest.rb#1081
  def initialize(error); end

  # source://minitest//lib/minitest.rb#1094
  def backtrace; end

  # source://minitest//lib/minitest.rb#1079
  def error; end

  # source://minitest//lib/minitest.rb#1079
  def error=(_arg0); end

  # source://minitest//lib/minitest.rb#1100
  def message; end

  # source://minitest//lib/minitest.rb#1106
  def result_label; end
end

# source://minitest//lib/minitest.rb#1098
Minitest::UnexpectedError::BASE_RE = T.let(T.unsafe(nil), Regexp)

# source://minitest//lib/minitest.rb#1114
class Minitest::UnexpectedWarning < ::Minitest::Assertion
  # source://minitest//lib/minitest.rb#1115
  def result_label; end
end

# source://minitest//lib/minitest.rb#13
Minitest::VERSION = T.let(T.unsafe(nil), String)
