# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ostruct` gem.
# Please instead update this file by running `bin/tapioca gem ostruct`.


# source://ostruct//lib/ostruct.rb#109
class OpenStruct
  # source://ostruct//lib/ostruct.rb#134
  def initialize(hash = T.unsafe(nil)); end

  # source://ostruct//lib/ostruct.rb#426
  def ==(other); end

  # source://ostruct//lib/ostruct.rb#306
  def [](name); end

  # source://ostruct//lib/ostruct.rb#321
  def []=(name, value); end

  # source://ostruct//lib/ostruct.rb#374
  def delete_field(name, &block); end

  # source://ostruct//lib/ostruct.rb#374
  def delete_field!(name, &block); end

  # source://ostruct//lib/ostruct.rb#343
  def dig(name, *names); end

  # source://ostruct//lib/ostruct.rb#343
  def dig!(name, *names); end

  # source://ostruct//lib/ostruct.rb#211
  def each_pair; end

  # source://ostruct//lib/ostruct.rb#211
  def each_pair!; end

  # source://ostruct//lib/ostruct.rb#449
  def encode_with(coder); end

  # source://ostruct//lib/ostruct.rb#449
  def encode_with!(coder); end

  # source://ostruct//lib/ostruct.rb#436
  def eql?(other); end

  # source://ostruct//lib/ostruct.rb#272
  def freeze; end

  # source://ostruct//lib/ostruct.rb#272
  def freeze!; end

  # source://ostruct//lib/ostruct.rb#442
  def hash; end

  # source://ostruct//lib/ostruct.rb#442
  def hash!; end

  # source://ostruct//lib/ostruct.rb#462
  def init_with(coder); end

  # source://ostruct//lib/ostruct.rb#462
  def init_with!(coder); end

  # source://ostruct//lib/ostruct.rb#391
  def inspect; end

  # source://ostruct//lib/ostruct.rb#391
  def inspect!; end

  # source://ostruct//lib/ostruct.rb#220
  def marshal_dump; end

  # source://ostruct//lib/ostruct.rb#220
  def marshal_dump!; end

  # source://ostruct//lib/ostruct.rb#409
  def table; end

  # source://ostruct//lib/ostruct.rb#182
  def to_h(&block); end

  # source://ostruct//lib/ostruct.rb#182
  def to_h!(&block); end

  # source://ostruct//lib/ostruct.rb#391
  def to_s; end

  # source://ostruct//lib/ostruct.rb#391
  def to_s!; end

  protected

  # source://ostruct//lib/ostruct.rb#409
  def table!; end

  private

  # source://ostruct//lib/ostruct.rb#147
  def initialize_clone(orig); end

  # source://ostruct//lib/ostruct.rb#152
  def initialize_dup(orig); end

  # source://ostruct//lib/ostruct.rb#254
  def is_method_protected!(name); end

  # source://ostruct//lib/ostruct.rb#157
  def marshal_load(hash); end

  # source://ostruct//lib/ostruct.rb#277
  def method_missing(mid, *args); end

  # source://ostruct//lib/ostruct.rb#234
  def new_ostruct_member!(name); end

  # source://ostruct//lib/ostruct.rb#321
  def set_ostruct_member_value!(name, value); end

  # source://ostruct//lib/ostruct.rb#157
  def update_to_values!(hash); end
end

# source://ostruct//lib/ostruct.rb#112
OpenStruct::HAS_PERFORMANCE_WARNINGS = T.let(T.unsafe(nil), TrueClass)

# source://ostruct//lib/ostruct.rb#110
OpenStruct::VERSION = T.let(T.unsafe(nil), String)
