# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tty-cursor` gem.
# Please instead update this file by running `bin/tapioca gem tty-cursor`.


# source://tty-cursor//lib/tty/cursor/version.rb#3
module TTY; end

# source://tty-cursor//lib/tty/cursor/version.rb#4
module TTY::Cursor
  private

  # source://tty-cursor//lib/tty/cursor.rb#94
  def backward(n = T.unsafe(nil)); end

  # source://tty-cursor//lib/tty/cursor.rb#137
  def clear_char(n = T.unsafe(nil)); end

  # source://tty-cursor//lib/tty/cursor.rb#143
  def clear_line; end

  # source://tty-cursor//lib/tty/cursor.rb#157
  def clear_line_after; end

  # source://tty-cursor//lib/tty/cursor.rb#150
  def clear_line_before; end

  # source://tty-cursor//lib/tty/cursor.rb#169
  def clear_lines(n, direction = T.unsafe(nil)); end

  # source://tty-cursor//lib/tty/cursor.rb#169
  def clear_rows(n, direction = T.unsafe(nil)); end

  # source://tty-cursor//lib/tty/cursor.rb#191
  def clear_screen; end

  # source://tty-cursor//lib/tty/cursor.rb#179
  def clear_screen_down; end

  # source://tty-cursor//lib/tty/cursor.rb#185
  def clear_screen_up; end

  # source://tty-cursor//lib/tty/cursor.rb#111
  def column(n = T.unsafe(nil)); end

  # source://tty-cursor//lib/tty/cursor.rb#51
  def current; end

  # source://tty-cursor//lib/tty/cursor.rb#94
  def cursor_backward(n = T.unsafe(nil)); end

  # source://tty-cursor//lib/tty/cursor.rb#86
  def cursor_down(n = T.unsafe(nil)); end

  # source://tty-cursor//lib/tty/cursor.rb#102
  def cursor_forward(n = T.unsafe(nil)); end

  # source://tty-cursor//lib/tty/cursor.rb#78
  def cursor_up(n = T.unsafe(nil)); end

  # source://tty-cursor//lib/tty/cursor.rb#86
  def down(n = T.unsafe(nil)); end

  # source://tty-cursor//lib/tty/cursor.rb#102
  def forward(n = T.unsafe(nil)); end

  # source://tty-cursor//lib/tty/cursor.rb#24
  def hide; end

  # source://tty-cursor//lib/tty/cursor.rb#30
  def invisible(stream = T.unsafe(nil)); end

  # source://tty-cursor//lib/tty/cursor.rb#70
  def move(x, y); end

  # source://tty-cursor//lib/tty/cursor.rb#59
  def move_to(row = T.unsafe(nil), column = T.unsafe(nil)); end

  # source://tty-cursor//lib/tty/cursor.rb#125
  def next_line; end

  # source://tty-cursor//lib/tty/cursor.rb#131
  def prev_line; end

  # source://tty-cursor//lib/tty/cursor.rb#45
  def restore; end

  # source://tty-cursor//lib/tty/cursor.rb#119
  def row(n = T.unsafe(nil)); end

  # source://tty-cursor//lib/tty/cursor.rb#39
  def save; end

  # source://tty-cursor//lib/tty/cursor.rb#203
  def scroll_down; end

  # source://tty-cursor//lib/tty/cursor.rb#197
  def scroll_up; end

  # source://tty-cursor//lib/tty/cursor.rb#18
  def show; end

  # source://tty-cursor//lib/tty/cursor.rb#78
  def up(n = T.unsafe(nil)); end

  class << self
    # source://tty-cursor//lib/tty/cursor.rb#94
    def backward(n = T.unsafe(nil)); end

    # source://tty-cursor//lib/tty/cursor.rb#137
    def clear_char(n = T.unsafe(nil)); end

    # source://tty-cursor//lib/tty/cursor.rb#143
    def clear_line; end

    # source://tty-cursor//lib/tty/cursor.rb#157
    def clear_line_after; end

    # source://tty-cursor//lib/tty/cursor.rb#150
    def clear_line_before; end

    # source://tty-cursor//lib/tty/cursor.rb#169
    def clear_lines(n, direction = T.unsafe(nil)); end

    # source://tty-cursor//lib/tty/cursor.rb#191
    def clear_screen; end

    # source://tty-cursor//lib/tty/cursor.rb#179
    def clear_screen_down; end

    # source://tty-cursor//lib/tty/cursor.rb#185
    def clear_screen_up; end

    # source://tty-cursor//lib/tty/cursor.rb#111
    def column(n = T.unsafe(nil)); end

    # source://tty-cursor//lib/tty/cursor.rb#51
    def current; end

    # source://tty-cursor//lib/tty/cursor.rb#86
    def down(n = T.unsafe(nil)); end

    # source://tty-cursor//lib/tty/cursor.rb#102
    def forward(n = T.unsafe(nil)); end

    # source://tty-cursor//lib/tty/cursor.rb#24
    def hide; end

    # source://tty-cursor//lib/tty/cursor.rb#30
    def invisible(stream = T.unsafe(nil)); end

    # source://tty-cursor//lib/tty/cursor.rb#70
    def move(x, y); end

    # source://tty-cursor//lib/tty/cursor.rb#59
    def move_to(row = T.unsafe(nil), column = T.unsafe(nil)); end

    # source://tty-cursor//lib/tty/cursor.rb#125
    def next_line; end

    # source://tty-cursor//lib/tty/cursor.rb#131
    def prev_line; end

    # source://tty-cursor//lib/tty/cursor.rb#45
    def restore; end

    # source://tty-cursor//lib/tty/cursor.rb#119
    def row(n = T.unsafe(nil)); end

    # source://tty-cursor//lib/tty/cursor.rb#39
    def save; end

    # source://tty-cursor//lib/tty/cursor.rb#203
    def scroll_down; end

    # source://tty-cursor//lib/tty/cursor.rb#197
    def scroll_up; end

    # source://tty-cursor//lib/tty/cursor.rb#18
    def show; end

    # source://tty-cursor//lib/tty/cursor.rb#78
    def up(n = T.unsafe(nil)); end
  end
end

# source://tty-cursor//lib/tty/cursor.rb#11
TTY::Cursor::CSI = T.let(T.unsafe(nil), String)

# source://tty-cursor//lib/tty/cursor.rb#12
TTY::Cursor::DEC_RST = T.let(T.unsafe(nil), String)

# source://tty-cursor//lib/tty/cursor.rb#13
TTY::Cursor::DEC_SET = T.let(T.unsafe(nil), String)

# source://tty-cursor//lib/tty/cursor.rb#14
TTY::Cursor::DEC_TCEM = T.let(T.unsafe(nil), String)

# source://tty-cursor//lib/tty/cursor.rb#10
TTY::Cursor::ESC = T.let(T.unsafe(nil), String)

# source://tty-cursor//lib/tty/cursor/version.rb#5
TTY::Cursor::VERSION = T.let(T.unsafe(nil), String)
