# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tty-screen` gem.
# Please instead update this file by running `bin/tapioca gem tty-screen`.


# source://tty-screen//lib/tty/screen/version.rb#3
module TTY; end

# source://tty-screen//lib/tty/screen/version.rb#4
module TTY::Screen
  private

  # source://tty-screen//lib/tty/screen.rb#128
  def cols; end

  # source://tty-screen//lib/tty/screen.rb#128
  def columns; end

  # source://tty-screen//lib/tty/screen.rb#442
  def command_exist?(command); end

  # source://tty-screen//lib/tty/screen.rb#146
  def height; end

  # source://tty-screen//lib/tty/screen.rb#331
  def ioctl?(control, buf); end

  # source://tty-screen//lib/tty/screen.rb#55
  def jruby?; end

  # source://tty-screen//lib/tty/screen.rb#146
  def lines; end

  # source://tty-screen//lib/tty/screen.rb#476
  def nonzero_column?(column); end

  # source://tty-screen//lib/tty/screen.rb#146
  def rows; end

  # source://tty-screen//lib/tty/screen.rb#461
  def run_command(*args); end

  # source://tty-screen//lib/tty/screen.rb#106
  def size(verbose: T.unsafe(nil)); end

  # source://tty-screen//lib/tty/screen.rb#426
  def size_from_ansicon; end

  # source://tty-screen//lib/tty/screen.rb#161
  def size_from_default; end

  # source://tty-screen//lib/tty/screen.rb#412
  def size_from_env; end

  # source://tty-screen//lib/tty/screen.rb#249
  def size_from_io_console(verbose: T.unsafe(nil)); end

  # source://tty-screen//lib/tty/screen.rb#308
  def size_from_ioctl; end

  # source://tty-screen//lib/tty/screen.rb#232
  def size_from_java(verbose: T.unsafe(nil)); end

  # source://tty-screen//lib/tty/screen.rb#353
  def size_from_readline(verbose: T.unsafe(nil)); end

  # source://tty-screen//lib/tty/screen.rb#390
  def size_from_stty; end

  # source://tty-screen//lib/tty/screen.rb#373
  def size_from_tput; end

  # source://tty-screen//lib/tty/screen.rb#207
  def size_from_win_api(verbose: T.unsafe(nil)); end

  # source://tty-screen//lib/tty/screen.rb#128
  def width; end

  # source://tty-screen//lib/tty/screen.rb#42
  def windows?; end

  class << self
    # source://tty-screen//lib/tty/screen.rb#128
    def cols; end

    # source://tty-screen//lib/tty/screen.rb#128
    def columns; end

    # source://tty-screen//lib/tty/screen.rb#81
    def env; end

    # source://tty-screen//lib/tty/screen.rb#81
    def env=(_arg0); end

    # source://tty-screen//lib/tty/screen.rb#146
    def height; end

    # source://tty-screen//lib/tty/screen.rb#331
    def ioctl?(control, buf); end

    # source://tty-screen//lib/tty/screen.rb#55
    def jruby?; end

    # source://tty-screen//lib/tty/screen.rb#146
    def lines; end

    # source://tty-screen//lib/tty/screen.rb#94
    def output; end

    # source://tty-screen//lib/tty/screen.rb#94
    def output=(_arg0); end

    # source://tty-screen//lib/tty/screen.rb#28
    def private_module_function(name); end

    # source://tty-screen//lib/tty/screen.rb#146
    def rows; end

    # source://tty-screen//lib/tty/screen.rb#106
    def size(verbose: T.unsafe(nil)); end

    # source://tty-screen//lib/tty/screen.rb#426
    def size_from_ansicon; end

    # source://tty-screen//lib/tty/screen.rb#161
    def size_from_default; end

    # source://tty-screen//lib/tty/screen.rb#412
    def size_from_env; end

    # source://tty-screen//lib/tty/screen.rb#249
    def size_from_io_console(verbose: T.unsafe(nil)); end

    # source://tty-screen//lib/tty/screen.rb#308
    def size_from_ioctl; end

    # source://tty-screen//lib/tty/screen.rb#232
    def size_from_java(verbose: T.unsafe(nil)); end

    # source://tty-screen//lib/tty/screen.rb#353
    def size_from_readline(verbose: T.unsafe(nil)); end

    # source://tty-screen//lib/tty/screen.rb#390
    def size_from_stty; end

    # source://tty-screen//lib/tty/screen.rb#373
    def size_from_tput; end

    # source://tty-screen//lib/tty/screen.rb#207
    def size_from_win_api(verbose: T.unsafe(nil)); end

    # source://tty-screen//lib/tty/screen.rb#128
    def width; end

    # source://tty-screen//lib/tty/screen.rb#42
    def windows?; end

    private

    # source://tty-screen//lib/tty/screen.rb#442
    def command_exist?(command); end

    # source://tty-screen//lib/tty/screen.rb#476
    def nonzero_column?(column); end

    # source://tty-screen//lib/tty/screen.rb#461
    def run_command(*args); end
  end
end

# source://tty-screen//lib/tty/screen.rb#64
TTY::Screen::DEFAULT_SIZE = T.let(T.unsafe(nil), Array)

# source://tty-screen//lib/tty/screen.rb#20
TTY::Screen::RUBY_CONFIG = T.let(T.unsafe(nil), Hash)

# source://tty-screen//lib/tty/screen.rb#270
TTY::Screen::TIOCGWINSZ = T.let(T.unsafe(nil), Integer)

# source://tty-screen//lib/tty/screen.rb#291
TTY::Screen::TIOCGWINSZ_BUF_FMT = T.let(T.unsafe(nil), String)

# source://tty-screen//lib/tty/screen.rb#299
TTY::Screen::TIOCGWINSZ_BUF_LEN = T.let(T.unsafe(nil), Integer)

# source://tty-screen//lib/tty/screen.rb#277
TTY::Screen::TIOCGWINSZ_PPC = T.let(T.unsafe(nil), Integer)

# source://tty-screen//lib/tty/screen.rb#284
TTY::Screen::TIOCGWINSZ_SOL = T.let(T.unsafe(nil), Integer)

# source://tty-screen//lib/tty/screen/version.rb#5
TTY::Screen::VERSION = T.let(T.unsafe(nil), String)
