# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tty-progressbar` gem.
# Please instead update this file by running `bin/tapioca gem tty-progressbar`.


# source://tty-progressbar//lib/tty/progressbar/timer.rb#3
module TTY; end

# source://tty-progressbar//lib/tty/progressbar/timer.rb#4
class TTY::ProgressBar
  include ::MonitorMixin
  extend ::Forwardable

  # source://tty-progressbar//lib/tty/progressbar.rb#106
  def initialize(format, options = T.unsafe(nil)); end

  # source://tty-progressbar//lib/tty/progressbar.rb#205
  def advance(progress = T.unsafe(nil), tokens = T.unsafe(nil)); end

  # source://tty-progressbar//lib/tty/progressbar.rb#170
  def attach_to(multibar); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def bar_format(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def clear(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def clear_head(*args, **_arg1, &block); end

  # source://tty-progressbar//lib/tty/progressbar.rb#489
  def clear_line; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def complete(*args, **_arg1, &block); end

  # source://tty-progressbar//lib/tty/progressbar.rb#499
  def complete?; end

  # source://tty-progressbar//lib/tty/progressbar.rb#151
  def configure; end

  # source://tty-progressbar//lib/tty/progressbar.rb#33
  def current; end

  # source://tty-progressbar//lib/tty/progressbar.rb#292
  def current=(value); end

  # source://tty-progressbar//lib/tty/progressbar.rb#526
  def done?; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def elapsed_time(*args, **_arg1, &block); end

  # source://tty-progressbar//lib/tty/progressbar.rb#424
  def finish; end

  # source://tty-progressbar//lib/tty/progressbar.rb#31
  def format; end

  # source://tty-progressbar//lib/tty/progressbar.rb#31
  def format=(_arg0); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def frequency(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def head(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def hide_cursor(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def incomplete(*args, **_arg1, &block); end

  # source://tty-progressbar//lib/tty/progressbar.rb#160
  def indeterminate?; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def inset(*args, **_arg1, &block); end

  # source://tty-progressbar//lib/tty/progressbar.rb#577
  def inspect; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def interval(*args, **_arg1, &block); end

  # source://tty-progressbar//lib/tty/progressbar.rb#259
  def iterate(collection, progress = T.unsafe(nil), &block); end

  # source://tty-progressbar//lib/tty/progressbar.rb#551
  def log(message); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def mean_rate(*args, **_arg1, &block); end

  # source://tty-progressbar//lib/tty/progressbar.rb#367
  def move_to_row; end

  # source://tty-progressbar//lib/tty/progressbar.rb#538
  def on(name, &callback); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def output(*args, **_arg1, &block); end

  # source://tty-progressbar//lib/tty/progressbar.rb#478
  def pause; end

  # source://tty-progressbar//lib/tty/progressbar.rb#517
  def paused?; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def rate(*args, **_arg1, &block); end

  # source://tty-progressbar//lib/tty/progressbar.rb#323
  def ratio; end

  # source://tty-progressbar//lib/tty/progressbar.rb#309
  def ratio=(value); end

  # source://tty-progressbar//lib/tty/progressbar.rb#337
  def render; end

  # source://tty-progressbar//lib/tty/progressbar.rb#132
  def reset; end

  # source://tty-progressbar//lib/tty/progressbar.rb#410
  def resize(new_width = T.unsafe(nil)); end

  # source://tty-progressbar//lib/tty/progressbar.rb#446
  def resume; end

  # source://tty-progressbar//lib/tty/progressbar.rb#35
  def row; end

  # source://tty-progressbar//lib/tty/progressbar.rb#191
  def start; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def start_time(*args, **_arg1, &block); end

  # source://tty-progressbar//lib/tty/progressbar.rb#457
  def stop; end

  # source://tty-progressbar//lib/tty/progressbar.rb#508
  def stopped?; end

  # source://tty-progressbar//lib/tty/progressbar.rb#568
  def to_s; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def total(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def unknown(*args, **_arg1, &block); end

  # source://tty-progressbar//lib/tty/progressbar.rb#276
  def update(options = T.unsafe(nil)); end

  # source://tty-progressbar//lib/tty/progressbar.rb#180
  def use(formatter_class); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def width(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def width=(*args, **_arg1, &block); end

  # source://tty-progressbar//lib/tty/progressbar.rb#393
  def write(data, clear_first = T.unsafe(nil)); end

  private

  # source://tty-progressbar//lib/tty/progressbar.rb#611
  def emit(name, *args); end

  # source://tty-progressbar//lib/tty/progressbar.rb#595
  def padout(message); end

  # source://tty-progressbar//lib/tty/progressbar.rb#622
  def tty?; end

  class << self
    # source://tty-progressbar//lib/tty/progressbar.rb#62
    def display_columns(value); end

    # source://tty-progressbar//lib/tty/progressbar.rb#50
    def max_columns; end
  end
end

# source://tty-progressbar//lib/tty/progressbar/formatter/bar.rb#10
class TTY::ProgressBar::BarFormatter
  # source://tty-progressbar//lib/tty/progressbar/formatter/bar.rb#19
  def call(value); end

  private

  # source://tty-progressbar//lib/tty/progressbar/formatter/bar.rb#65
  def format_determinate(value, width); end

  # source://tty-progressbar//lib/tty/progressbar/formatter/bar.rb#40
  def format_indeterminate(value, width); end
end

# source://tty-progressbar//lib/tty/progressbar/formatter/current_byte.rb#11
class TTY::ProgressBar::ByteFormatter
  # source://tty-progressbar//lib/tty/progressbar/formatter/current_byte.rb#20
  def call(value); end
end

# source://tty-progressbar//lib/tty/progressbar/formatter/byte_rate.rb#11
class TTY::ProgressBar::ByteRateFormatter
  # source://tty-progressbar//lib/tty/progressbar/formatter/byte_rate.rb#20
  def call(value); end
end

# source://tty-progressbar//lib/tty/progressbar.rb#29
TTY::ProgressBar::CURSOR_LOCK = T.let(T.unsafe(nil), Monitor)

# source://tty-progressbar//lib/tty/progressbar/configuration.rb#7
class TTY::ProgressBar::Configuration
  include ::TTY::ProgressBar::Formats

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#66
  def initialize(options); end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#40
  def bar_format; end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#40
  def bar_format=(_arg0); end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#60
  def clear; end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#60
  def clear=(_arg0); end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#64
  def clear_head; end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#64
  def clear_head=(_arg0); end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#20
  def complete; end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#88
  def complete=(value); end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#48
  def frequency; end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#48
  def frequency=(_arg0); end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#28
  def head; end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#28
  def head=(_arg0); end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#56
  def hide_cursor; end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#56
  def hide_cursor=(_arg0); end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#24
  def incomplete; end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#99
  def incomplete=(value); end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#36
  def inset; end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#36
  def inset=(_arg0); end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#52
  def interval; end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#52
  def interval=(_arg0); end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#44
  def output; end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#44
  def output=(_arg0); end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#12
  def total; end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#121
  def total=(value); end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#32
  def unknown; end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#110
  def unknown=(value); end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#16
  def width; end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#16
  def width=(_arg0); end

  private

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#134
  def fetch_char(name, property); end

  # source://tty-progressbar//lib/tty/progressbar/configuration.rb#149
  def raise_if_empty(name, value); end
end

# source://tty-progressbar//lib/tty/progressbar/converter.rb#8
module TTY::ProgressBar::Converter
  private

  # source://tty-progressbar//lib/tty/progressbar/converter.rb#68
  def to_bytes(value, decimals: T.unsafe(nil), separator: T.unsafe(nil), unit_separator: T.unsafe(nil)); end

  # source://tty-progressbar//lib/tty/progressbar/converter.rb#46
  def to_seconds(seconds, precision: T.unsafe(nil)); end

  # source://tty-progressbar//lib/tty/progressbar/converter.rb#17
  def to_time(seconds); end

  class << self
    # source://tty-progressbar//lib/tty/progressbar/converter.rb#68
    def to_bytes(value, decimals: T.unsafe(nil), separator: T.unsafe(nil), unit_separator: T.unsafe(nil)); end

    # source://tty-progressbar//lib/tty/progressbar/converter.rb#46
    def to_seconds(seconds, precision: T.unsafe(nil)); end

    # source://tty-progressbar//lib/tty/progressbar/converter.rb#17
    def to_time(seconds); end
  end
end

# source://tty-progressbar//lib/tty/progressbar/converter.rb#52
TTY::ProgressBar::Converter::BYTE_UNITS = T.let(T.unsafe(nil), Array)

# source://tty-progressbar//lib/tty/progressbar/converter.rb#9
TTY::ProgressBar::Converter::HOURSECONDS = T.let(T.unsafe(nil), Integer)

# source://tty-progressbar//lib/tty/progressbar/formatter/current.rb#8
class TTY::ProgressBar::CurrentFormatter
  # source://tty-progressbar//lib/tty/progressbar/formatter/current.rb#17
  def call(value); end
end

# source://tty-progressbar//lib/tty/progressbar.rb#25
TTY::ProgressBar::ECMA_CSI = T.let(T.unsafe(nil), String)

# source://tty-progressbar//lib/tty/progressbar/formatter/elapsed.rb#11
class TTY::ProgressBar::ElapsedFormatter
  # source://tty-progressbar//lib/tty/progressbar/formatter/elapsed.rb#20
  def call(value); end
end

# source://tty-progressbar//lib/tty/progressbar/formatter/estimated.rb#11
class TTY::ProgressBar::EstimatedFormatter
  # source://tty-progressbar//lib/tty/progressbar/formatter/estimated.rb#20
  def call(value); end
end

# source://tty-progressbar//lib/tty/progressbar/formatter/estimated_time.rb#8
class TTY::ProgressBar::EstimatedTimeFormatter
  # source://tty-progressbar//lib/tty/progressbar/formatter/estimated_time.rb#17
  def call(value); end
end

# source://tty-progressbar//lib/tty/progressbar/formats.rb#5
module TTY::ProgressBar::Formats; end

# source://tty-progressbar//lib/tty/progressbar/formats.rb#6
TTY::ProgressBar::Formats::FORMATS = T.let(T.unsafe(nil), Hash)

# source://tty-progressbar//lib/tty/progressbar/formatter.rb#5
class TTY::ProgressBar::Formatter < ::Module
  # source://tty-progressbar//lib/tty/progressbar/formatter.rb#19
  def initialize(token_match); end

  class << self
    # source://tty-progressbar//lib/tty/progressbar/formatter.rb#9
    def [](token_match); end
  end
end

# source://tty-progressbar//lib/tty/progressbar/formatters.rb#23
class TTY::ProgressBar::Formatters
  extend ::Forwardable

  # source://tty-progressbar//lib/tty/progressbar/formatters.rb#29
  def initialize(pipeline = T.unsafe(nil)); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def decorate(*args, **_arg1, &block); end

  # source://tty-progressbar//lib/tty/progressbar/formatters.rb#36
  def load(progress); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def use(*args, **_arg1, &block); end
end

# source://tty-progressbar//lib/tty/progressbar/formatter/mean_byte.rb#11
class TTY::ProgressBar::MeanByteFormatter
  # source://tty-progressbar//lib/tty/progressbar/formatter/mean_byte.rb#20
  def call(value); end
end

# source://tty-progressbar//lib/tty/progressbar/formatter/mean_rate.rb#11
class TTY::ProgressBar::MeanRateFormatter
  # source://tty-progressbar//lib/tty/progressbar/formatter/mean_rate.rb#20
  def call(value); end
end

# source://tty-progressbar//lib/tty/progressbar/meter.rb#9
class TTY::ProgressBar::Meter
  # source://tty-progressbar//lib/tty/progressbar/meter.rb#16
  def initialize(interval); end

  # source://tty-progressbar//lib/tty/progressbar/meter.rb#98
  def avg_rate; end

  # source://tty-progressbar//lib/tty/progressbar/meter.rb#111
  def clear; end

  # source://tty-progressbar//lib/tty/progressbar/meter.rb#98
  def mean_rate; end

  # source://tty-progressbar//lib/tty/progressbar/meter.rb#51
  def prune_samples(at); end

  # source://tty-progressbar//lib/tty/progressbar/meter.rb#75
  def rate; end

  # source://tty-progressbar//lib/tty/progressbar/meter.rb#88
  def rates; end

  # source://tty-progressbar//lib/tty/progressbar/meter.rb#41
  def sample(at, value); end

  # source://tty-progressbar//lib/tty/progressbar/meter.rb#62
  def save_rate(at); end

  # source://tty-progressbar//lib/tty/progressbar/meter.rb#24
  def start; end
end

# source://tty-progressbar//lib/tty/progressbar/multi.rb#13
class TTY::ProgressBar::Multi
  include ::Enumerable
  include ::MonitorMixin
  extend ::Forwardable

  # source://tty-progressbar//lib/tty/progressbar/multi.rb#46
  def initialize(*args); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def [](*args, **_arg1, &block); end

  # source://tty-progressbar//lib/tty/progressbar/multi.rb#165
  def complete?; end

  # source://tty-progressbar//lib/tty/progressbar/multi.rb#154
  def current; end

  # source://tty-progressbar//lib/tty/progressbar/multi.rb#187
  def done?; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def each(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def empty?(*args, **_arg1, &block); end

  # source://tty-progressbar//lib/tty/progressbar/multi.rb#214
  def finish; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def length(*args, **_arg1, &block); end

  # source://tty-progressbar//lib/tty/progressbar/multi.rb#242
  def line_inset(bar); end

  # source://tty-progressbar//lib/tty/progressbar/multi.rb#94
  def next_row; end

  # source://tty-progressbar//lib/tty/progressbar/multi.rb#106
  def observe(bar); end

  # source://tty-progressbar//lib/tty/progressbar/multi.rb#261
  def on(name, &callback); end

  # source://tty-progressbar//lib/tty/progressbar/multi.rb#221
  def pause; end

  # source://tty-progressbar//lib/tty/progressbar/multi.rb#198
  def paused?; end

  # source://tty-progressbar//lib/tty/progressbar/multi.rb#116
  def progress_handler; end

  # source://tty-progressbar//lib/tty/progressbar/multi.rb#73
  def register(format, options = T.unsafe(nil)); end

  # source://tty-progressbar//lib/tty/progressbar/multi.rb#228
  def resume; end

  # source://tty-progressbar//lib/tty/progressbar/multi.rb#30
  def rows; end

  # source://tty-progressbar//lib/tty/progressbar/multi.rb#132
  def start; end

  # source://tty-progressbar//lib/tty/progressbar/multi.rb#207
  def stop; end

  # source://tty-progressbar//lib/tty/progressbar/multi.rb#176
  def stopped?; end

  # source://tty-progressbar//lib/tty/progressbar/multi.rb#126
  def top_bar; end

  # source://tty-progressbar//lib/tty/progressbar/multi.rb#143
  def total; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def width(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def width=(*args, **_arg1, &block); end

  private

  # source://tty-progressbar//lib/tty/progressbar/multi.rb#276
  def emit(name, *args); end
end

# source://tty-progressbar//lib/tty/progressbar/multi.rb#23
TTY::ProgressBar::Multi::DEFAULT_INSET = T.let(T.unsafe(nil), Hash)

# source://tty-progressbar//lib/tty/progressbar.rb#27
TTY::ProgressBar::NEWLINE = T.let(T.unsafe(nil), String)

# source://tty-progressbar//lib/tty/progressbar/formatter/percent.rb#10
class TTY::ProgressBar::PercentFormatter
  # source://tty-progressbar//lib/tty/progressbar/formatter/percent.rb#19
  def call(value); end
end

# source://tty-progressbar//lib/tty/progressbar/pipeline.rb#8
class TTY::ProgressBar::Pipeline
  include ::Enumerable

  # source://tty-progressbar//lib/tty/progressbar/pipeline.rb#14
  def initialize(formatters = T.unsafe(nil)); end

  # source://tty-progressbar//lib/tty/progressbar/pipeline.rb#40
  def decorate(tokenized); end

  # source://tty-progressbar//lib/tty/progressbar/pipeline.rb#54
  def each(&block); end

  # source://tty-progressbar//lib/tty/progressbar/pipeline.rb#25
  def use(formatter); end

  protected

  # source://tty-progressbar//lib/tty/progressbar/pipeline.rb#60
  def formatters; end
end

# source://tty-progressbar//lib/tty/progressbar/formatter/rate.rb#11
class TTY::ProgressBar::RateFormatter
  # source://tty-progressbar//lib/tty/progressbar/formatter/rate.rb#20
  def call(value); end
end

# source://tty-progressbar//lib/tty/progressbar/timer.rb#8
class TTY::ProgressBar::Timer
  # source://tty-progressbar//lib/tty/progressbar/timer.rb#14
  def initialize; end

  # source://tty-progressbar//lib/tty/progressbar/timer.rb#42
  def elapsed_time; end

  # source://tty-progressbar//lib/tty/progressbar/timer.rb#53
  def elapsed_until_now; end

  # source://tty-progressbar//lib/tty/progressbar/timer.rb#21
  def reset; end

  # source://tty-progressbar//lib/tty/progressbar/timer.rb#32
  def running?; end

  # source://tty-progressbar//lib/tty/progressbar/timer.rb#65
  def start; end

  # source://tty-progressbar//lib/tty/progressbar/timer.rb#9
  def start_time; end

  # source://tty-progressbar//lib/tty/progressbar/timer.rb#78
  def stop; end
end

# source://tty-progressbar//lib/tty/progressbar/formatter/total_byte.rb#11
class TTY::ProgressBar::TotalByteFormatter
  # source://tty-progressbar//lib/tty/progressbar/formatter/total_byte.rb#20
  def call(value); end
end

# source://tty-progressbar//lib/tty/progressbar/formatter/total.rb#10
class TTY::ProgressBar::TotalFormatter
  # source://tty-progressbar//lib/tty/progressbar/formatter/total.rb#19
  def call(value); end
end

# source://tty-progressbar//lib/tty/progressbar/version.rb#5
TTY::ProgressBar::VERSION = T.let(T.unsafe(nil), String)
