# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# typed: true
# frozen_string_literal: true

RUBY_UDB_ROOT = Kernel.__dir__

namespace :gen do
  namespace :udb do
    desc "Generate the UDB Ruby API documentation"
    task "ruby-doc" do
      sh "yard doc"
    end
  end
end

# initialize sorbet
file "#{RUBY_UDB_ROOT}/Gemfile.lock" do
  Dir.chdir(RUBY_UDB_ROOT) do
    sh "bundle install --gemfile Gemfile"
  end
end

# initialize sorbet
namespace :chore do
  namespace :udb do

    task :lsp do
      Dir.chdir(RUBY_UDB_ROOT) do
        sh "bundle exec srb tc --lsp --disable-watchman"
      end
    end

    task :collate_cov, [:cov_dir] do |t, args|
      require "simplecov"
      require "simplecov-cobertura"

      SimpleCov.collate Dir["#{args[:cov_dir]}/*.resultset.json"] do
        coverage_dir ("#{RUBY_UDB_ROOT}/coverage").to_s
        formatter SimpleCov::Formatter::MultiFormatter.new([
          SimpleCov::Formatter::CoberturaFormatter,
          SimpleCov::Formatter::HTMLFormatter,
        ])
      end
    end
  end
end

namespace :gen do
  namespace :udb do
    task :api_doc do
      Dir.chdir(RUBY_UDB_ROOT) do
        FileUtils.rm_rf $root / "gen" / "udb_api_doc"
        sh "bundle exec yard --plugin sorbet lib --no-save --embed-mixins --hide-void-return -o #{$root}/gen/udb_api_doc"
      end
    end
  end
end

namespace :test do
  namespace :udb do
    desc "Type check the Ruby UDB source code"
    task sorbet: "#{RUBY_UDB_ROOT}/sorbet/config" do
      Dir.chdir(RUBY_UDB_ROOT) do
        Udb.logger.info "Type checking udb gem"
        sh "bundle exec srb tc"
      end
    end

    desc "Run unit tests for the udb gem"
    task :unit do
      Dir.chdir(RUBY_UDB_ROOT) do
        Udb.logger.info "Type checking udb gem"
        sh "ruby -Ilib:test test/run.rb"
      end
    end
  end
end
