#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Contributors to the RISCV UnifiedDB <https://github.com/riscv/riscv-unified-db>
# SPDX-License-Identifier: BSD-3-Clause-Clear
#MISE description="Regression task translated from regress-idl-typecheck-other"
#USAGE flag "--cfg <cfg>" help="Matrix axis cfg" {
#USAGE   choices _ rv32
#USAGE }

set -e

# Step 1: Type check IDL for ${{ matrix.cfg }}
(
  ./do test:idl CFG=${usage_cfg:?}
)
