%version: 1.0

builtin function implemented? {
  returns Boolean
  arguments ExtensionName extension
  description {
    Return true if the implementation supports `extension`.
  }
}

builtin function unpredictable {
  arguments String why
  description {
    Indicate that the hart has reached a state that is unpredictable because the
    RISC-V spec allows multiple behaviors. Generally, this will be a fatal condition
    to any emulation, since it is unclear what to do next.

    The single argument _why_ is a string describing why the hart entered an
    unpredictable state.
  }
}

builtin function read_hpm_counter {
  returns Bits<64>
  arguments Bits<5> n
  description {
    Returns the value of hpmcounterN.

    N must be between 3..31.

    hpmcounterN must be implemented.
  }
}

builtin function hartid {
  returns XReg   # hart id
  description {
    Returns the value for `mhartid` as seen by this hart.

    Must obey the rules of the priv spec:

    [quote]
    ____
    The `mhartid` CSR is an MXLEN-bit read-only register containing the integer ID of the hardware
    thread running the code.
    This register must be readable in any implementation.
    Hart IDs might not necessarily be numbered contiguously in a multiprocessor system, but at
    least one hart must have a hart ID of zero.
    Hart IDs must be unique within the execution environment.
    ____
  }
}

builtin function read_mcycle {
  returns Bits<64>
  description {
    Return the current value of the cycle counter.
  }
}

builtin function read_mtime {
  returns Bits<64>
  description {
    Return the current value of the real time device.
  }
}

builtin function sw_write_mcycle {
  returns Bits<64>
  arguments Bits<64> value
  description {
    Given a _value_ that software is trying to write into mcycle,
    perform the write and
    return the value that will actually be written.
  }
}

builtin function cache_block_zero {
  arguments
    XReg cache_block_physical_address
  description {
    Zero the cache block at the given physical address.

    The cache block may be zeroed using 1 or more writes.

    A cache-block-sized region is zeroed regardless of whether
    or not the memory is in a cacheable PMA region.
  }
}

builtin function eei_ecall_from_m {
  description {
    When TRAP_ON_ECALL_FROM_M is false, this function will be called to
    emulate the EEI handling of ECALL-from-M.

    If TRAP_ON_ECALL_FROM_M is true, this function will never be called,
    and does not need to be provided (if pruning is applied to IDL).
  }
}

builtin function eei_ecall_from_s {
  description {
    When TRAP_ON_ECALL_FROM_S is false, this function will be called to
    emulate the EEI handling of ECALL-from-S.

    If TRAP_ON_ECALL_FROM_S is true, this function will never be called,
    and does not need to be provided (if pruning is applied to IDL).
  }
}

builtin function eei_ecall_from_u {
  description {
    When TRAP_ON_ECALL_FROM_U is false, this function will be called to
    emulate the EEI handling of ECALL-from-U.

    If TRAP_ON_ECALL_FROM_U is true, this function will never be called,
    and does not need to be provided (if pruning is applied to IDL).
  }
}

builtin function eei_ecall_from_vs {
  description {
    When TRAP_ON_ECALL_FROM_VS is false, this function will be called to
    emulate the EEI handling of ECALL-from-VS.

    If TRAP_ON_ECALL_FROM_VS is true, this function will never be called,
    and does not need to be provided (if pruning is applied to IDL).
  }
}

builtin function eei_ebreak {
  description {
    When TRAP_ON_EBREAK is false, this function will be called to
    emulate the EEI handling of EBREAK

    If TRAP_ON_EBREAK is true, this function will never be called,
    and does not need to be provided (if pruning is applied to IDL).
  }
}

builtin function memory_model_acquire {
  description {
    Perform an acquire; that is, ensure that no subsequent
    operation in program order appears to an external observer
    to occur after the operation calling this function.
  }
}

builtin function memory_model_release {
  description {
    Perform a release; that is, ensure that no prior store
    in program order can be observed external to this hart
    after this function returns.
  }
}

builtin function assert {
  arguments
    Boolean test,   # the result of a test
    String message  # a helpful message explaining what was expected
  description {
    Assert that a condition is true. Failure represents an error in the IDL model.
  }
}

builtin function notify_mode_change {
  arguments PrivilegeMode new_mode, PrivilegeMode old_mode
  description {
    Called whenever the privilege mode changes. Downstream tools can use this to hook events.
  }
}

builtin function abort_current_instruction {
  description {
    Abort the current instruction, and start refetching from $pc.
  }
}


builtin function zext {
  returns XReg
  arguments XReg value, XReg first_extended_bit
  description {
    Zero extend `value` starting at `first_extended_bit`.

    Bits [`XLEN-1`:`first_extended_bit`] of the return value
    should get the value `0`;
  }
}

builtin function ebreak {
  description {
    Raise an `Environment Break` exception, returning control to the debug environment.
  }
}

builtin function saturate {
  returns XReg
  arguments XReg value, XReg max_value
  description {
    If unsigned `value` is less than `max_value`, return `value`.
    Otherwise, return `max_value`.
  }
}

builtin function prefetch_instruction {
  arguments
    XReg virtual_address     # virtual cache block address
  description {
    Hint to prefetch a block containing +virtual_address+ for an upcoming fetch.
  }
}

builtin function prefetch_read {
  arguments
    XReg virtual_address     # virtual cache block address
  description {
    Hint to prefetch a block containing +virtual_address+ for an upcoming load.
  }
}

builtin function prefetch_write {
  arguments
    XReg virtual_address     # virtual cache block address
  description {
    Hint to prefetch a block containing +virtual_address+ for an upcoming store.
  }
}

# TODO: REMOVE THESE AFTER MERGE WITH FP BRANCH!
builtin function check_f_ok {
  description { REmove me. }
}
builtin function mark_f_state_dirty {
  description { Remove me. }
}

# TODO: move this *fixed* function to fp.idl
function nan_box {
  template U32 FROM_SIZE, U32 TO_SIZE
  returns Bits<TO_SIZE>
  arguments Bits<FROM_SIZE> from_value
  description {
    Produces a properly NaN-boxed floating-point value from a floating-point value
    of smaller size by adding all 1's to the upper bits.
  }
  body {
    assert(FROM_SIZE < TO_SIZE, "Bad template arugments; FROM_SIZE must be less than TO_SIZE");

    return {{TO_SIZE - FROM_SIZE{1'b1}}, from_value};
  }
}
Bits<32> SP_POS_INF       = 32'b0_11111111_00000000000000000000000;
Bits<32> SP_NEG_INF       = 32'b1_11111111_00000000000000000000000;
Bits<32> SP_POS_ZERO      = 32'b0_00000000_00000000000000000000000;
Bits<32> SP_NEG_ZERO      = 32'b1_00000000_00000000000000000000000;
Bits<32> SP_CANONICAL_NAN = 32'b0_11111111_10000000000000000000000;
Bits<16> HP_CANONICAL_NAN = 16'b0_11111_1000000000;
Bits<32> WORD_NEG_OVERFLOW = 32'h8000_0000; # minimum 32-bit integer
Bits<32> WORD_POS_OVERFLOW = 32'h7FFF_FFFF; # maximum 32-bit integer
enum FpFlag {
  NX 0b00001 # Inexact
  UF 0b00010 # Underflow
  OF 0b00100 # Overflow
  DZ 0b01000 # Divide by zero
  NV 0b10000 # Invalid Operation
}
builtin function set_fp_flag {
  arguments
    FpFlag f
  description { Remove me. }
}
function packToF32UI {
  returns Bits<32>
  arguments
    Bits<1> sign,
    Bits<8> exp,
    Bits<23> sig
  description {
    Pack components into a 32-bit value
  }
  body {
    return {sign, exp, sig};
  }
}

# TODO: THis needs to move to fp.idl
function packToF16UI {
  returns Bits<32>
  arguments
    Bits<1> sign,
    Bits<5> exp,
    Bits<10> sig
  description {
    Pack components into a 16-bit value
  }
  body {
    return {sign, exp, sig};
  }
}

# TODO: This need to move to fp.idl
function softfloat_normSubnormalF16Sig {
  returns Bits<5>, Bits<10>
  arguments
    Bits<16> hp_value
  description {
    normalize subnormal half-precision value
  }
  body {
    Bits<8> shift_dist = count_leading_zeros<16>(hp_value);
    return {1 - shift_dist, hp_value << shift_dist};
  }
}


builtin function fence {
  arguments
    Boolean pi, Boolean pr, Boolean po, Boolean pw,
    Boolean si, Boolean sr, Boolean so, Boolean sw
  description {
    Execute a memory ordering fence.(according to the FENCE instruction).
  }
}

builtin function fence_tso {
  description {
    Execute a TSO memory ordering fence.(according to the FENCE instruction).
  }
}

builtin function ifence {
  description {
    Execute a memory ordering instruction fence (according to FENCE.I).
  }
}

builtin function pause {
  description {
    Pause hart retirement for a implementation-defined period of time, which may be zero.

    See `Zihintpause` for more.
  }
}

builtin function pow {
  returns XReg
  arguments XReg value, XReg exponent
  description {
    Return `value` to the power `exponent`.
  }
}


builtin function maybe_cache_translation {
  arguments
    XReg vaddr,
    MemoryOperation op,
    TranslationResult result
  description {
    Given a translation result, potentially cache the result for later use. This function models
    a TLB fill operation. A valid implementation does nothing.
  }
}

builtin function cached_translation {
  returns
    Boolean,                     # whether or not the cached translation is valid
    TranslationResult            # cached result
  arguments
    XReg vaddr,         # virtual address
    MemoryOperation op  # operation
  description {
    Possibly returns a cached translation result matching +vaddr+.

    If the result is value, the first return value will be true.
    +paddr+ is the full translation of +vaddr+, including the page offset
    +pbmt+ is the result of any paged-based attributes for the translation
  }
}

builtin function order_pgtbl_writes_before_vmafence {
  arguments
    VmaOrderType order_type
  description {
    Orders all writes prior to this call in global memory order that affect a page table in the set
    identified by +order_type+ before any subsequent
    sfence.vma/hfence.vma/sinval.vma/hinval.gvma/hinval.vvma in program order.

    Performs the ordering function of SFENCE.VMA/HFENCE.[GV]VMA/SFENCE.W.INVAL.

    A valid implementation does nothing if address caching is not used.
  }
}

builtin function order_pgtbl_reads_after_vmafence {
  arguments
    VmaOrderType order_type
  description {
    Orders all reads after to this call in global memory order to a page table in the set
    identified by +order_type+ after any prior
    sfence.vma/hfence.vma/sinval.vma/hinval.gvma/hinval.vvma in program order.

    Performs the ordering function of SFENCE.VMA/HFENCE.[GV]VMA/SFENCE.INVAL.IR.

    A valid implementation does nothing if address caching is not used.
  }
}

builtin function invalidate_translations {
  arguments
    VmaOrderType inval_type
  description {
    Locally invalidate the cached S-mode/VS-mode/G-stage address translations
    contained in the set identified by +inval_type+.

    A valid implementation does nothing if address caching is not used.
  }
}

builtin function read_physical_memory {
  template U32 len
  returns Bits<len>
  arguments XReg paddr
  description {
    Read from physical memory.
  }
}

builtin function write_physical_memory {
  template U32 len
  arguments XReg paddr, Bits<len> value
  description {
    Write to physical memory.
  }
}

builtin function wfi {
  description {
    Wait-for-interrupt: hint that the processor
    should enter a low power state until the next interrupt.

    A valid implementation is a no-op.

    The model will advance the PC; this function does not need to.
  }
}

builtin function pma_applies? {
  returns Boolean
  arguments
    PmaAttribute          attr,   #< PMA attribute to check
    Bits<PHYS_ADDR_WIDTH> paddr,  #< Start of the region
    U32                   len     #< Size of the region, in bits
  description {
    Checks if _attr_ is applied to the entire physical address region
    between [paddr, paddr + len) based on static PMA attributes.
  }
}

builtin function atomic_check_then_write_32 {
  returns Boolean
  arguments
    Bits<PHYS_ADDR_WIDTH> paddr,          # the physical address
    Bits<32>              compare_value,  # the comparison value
    Bits<32>              write_value     # the value to be written if the value in memory matches compare_value
  description {
    Atomically:

     * Reads 32-bits from paddr
     * Compares the read value to compare_value
     * Writes write_value to paddr **if** the comparison was bitwise-equal

    returns true if the write occurs, and false otherwise

    Preconditions:

     * paddr will be aligned to 32-bits

  }
}

builtin function atomic_check_then_write_64 {
  returns Boolean
  arguments
    Bits<PHYS_ADDR_WIDTH> paddr,          # the physical address
    Bits<64>              compare_value,  # the comparison value
    Bits<64>              write_value     # the value to be written if the value in memory matches compare_value
  description {
    Atomically:

     * Reads 64-bits from paddr
     * Compares the read value to compare_value
     * Writes write_value to paddr **if** the comparison was bitwise-equal

    returns true if the write occurs, and false otherwise

    Preconditions:

     * paddr will be aligned to 64-bits
  }
}

builtin function atomically_set_pte_a {
  returns Boolean
  arguments
    Bits<PHYS_ADDR_WIDTH> pte_addr,
    Bits<XLEN>            pte_value,
    U32                   pte_len
  description {
    Atomically:
    
      * Reads the _pte_len_ value at _pte_addr_
      ** If the read value does not exactly equal pte_value, returns false
      * Sets the 'A' bit and writes the result to _pte_addr_
      * return true 

    Preconditions:

      * pte_addr will be aligned to 64-bits
  }
}

builtin function atomically_set_pte_a_d {
  returns Boolean
  arguments
    Bits<PHYS_ADDR_WIDTH> pte_addr,
    Bits<XLEN>            pte_value,
    U32                   pte_len
  description {
    Atomically:
    
      * Reads the _pte_len_ value at _pte_addr_
      ** If the read value does not exactly equal pte_value, returns false
      * Sets the 'A' and 'D' bits and writes the result to _pte_addr_
      * return true

    Preconditions:

      * pte_addr will be aligned to 64-bits
  }
}

builtin function atomic_read_modify_write_32 {
  returns Bits<32>
  arguments
    Bits<PHYS_ADDR_WIDTH>  phys_addr,
    Bits<32>               value,
    AmoOperation           op
  description {
    Atomically read-modify-write 32-bits starting at phys_address using +value+ and +op+.

    Return the original (unmodified) read value.

    All access checks/alignment checks/etc. should be done before calling this function;
    it's assumed the RMW is OK to proceed.
  }
}

builtin function atomic_read_modify_write_64 {
  returns Bits<64>
  arguments
    Bits<PHYS_ADDR_WIDTH>  phys_addr,
    Bits<64>               value,
    AmoOperation           op
  description {
    Atomically read-modify-write 64-bits starting at phys_address using +value+ and +op+.

    Return the original (unmodified) read value.

    All access checks/alignment checks/etc. should be done before calling this function;
    it's assumed the RMW is OK to proceed.
  }
}
