/*
 * generated by Xtext 2.39.0
 */
package org.riscv.idl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class IdlUiModule extends AbstractIdlUiModule {

	public IdlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
