/*
 * SPDX-License-Identifier: BSD-3-Clause-Clear
 *
 * Auto-generated by riscv-unified-db (udb-gen cfg-c-header)
 * Config: Header -- demo
 *
 * Define conventions:
 *   Extensions:           #define NAME_SUPPORTED and #define NAMEverPver_SUPPORTED
 *   Boolean params:       #define UDB_NAME           (present when true, absent when false)
 *   Integer params:       #define UDB_NAME value     and #define UDB_NAME_<value>
 *   Enum (string) params: #define UDB_NAME_VALUE     (value sanitized to uppercase identifier)
 *   Boolean arrays:       #define UDB_NAME_<index>   (one per true element)
 *   Integer arrays:       #define UDB_NAME_<value>   (one per unique element, sorted)
 *   String arrays:        #define UDB_NAME_<VALUE>   (one per unique element, sanitized)
 */

#ifndef UDB_CFG_HEADER____DEMO_H
#define UDB_CFG_HEADER____DEMO_H

/* Implemented extensions */

/* Configuration parameters */
#define UDB_BOOLS_1
#define UDB_BOOLS_3
#define UDB_DIGIT_STR_32_BIT
#define UDB_EMPTY_STR_
#define UDB_INTS_0
#define UDB_INTS_2
#define UDB_INTS_10
#define UDB_MXLEN 32
#define UDB_MXLEN_32
#define UDB_STR_MIXED_CASE_VALUE
#define UDB_STRINGS_A_B
#define UDB_STRINGS_Z
#define UDB_TRUE
#define UDB_U32_MAX 4294967295
#define UDB_U32_MAX_4294967295
#define UDB_U32_NEXT 4294967296
#define UDB_U32_NEXT_4294967296
#define UDB_U64_MAX 18446744073709551615
#define UDB_U64_MAX_18446744073709551615
#define UDB_U64_NEXT 18446744073709551616
#define UDB_U64_NEXT_18446744073709551616
#define UDB_U96_NEXT 79228162514264337593543950336
#define UDB_U96_NEXT_79228162514264337593543950336
#define UDB_UNEVALUATED_MXLEN
#define UDB_ZERO 0
#define UDB_ZERO_0

#endif /* UDB_CFG_HEADER____DEMO_H */
