/*
 * generated by Xtext 2.39.0
 */
package org.xtext.example.udb.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.xtext.validation.Check;
import org.xtext.example.udb.parser.antlr.UdbParser;
import org.xtext.example.udb.udb.FieldDef;
import org.xtext.example.udb.udb.IntType;
import org.xtext.example.udb.udb.LengthType;
import org.xtext.example.udb.udb.Model;
import org.xtext.example.udb.udb.ParmType;
import org.xtext.example.udb.udb.UdbPackage;


/**
 * This class contains custom validation rules.
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class UdbValidator extends AbstractUdbValidator {

	@Check
	public void checkAddress(Model m) {
		int address = m.getAddress() != null ? m.getAddress().getAddress().getValue() : null;

		if(address < 0 || address > 4096) {
			error("Address must be between 0 and 12 bits.", UdbPackage.Literals.MODEL__ADDRESS);
		}
	}

	@Check
	public void checkVirtualAddressValue(Model m) {
		/* Ensure virtual address is in required range 0-4095 */
		int vaddress = m.getVirtualAddress() != null ?
					   m.getVirtualAddress().getVirtualAddress().getValue() : null;

		if (vaddress < 0 || vaddress > 4095) {
			error("Virtual address must be between 0 and 12 bits.", UdbPackage.Literals.MODEL__VIRTUAL_ADDRESS);
		}
	}

	@Check
	public void checkIndirectAddressValue(Model m) {
		/* Ensure indirect address is in required range */
		int iaddress = m.getIndirectAddress() != null ?
					   m.getIndirectAddress().getIndirectAddress().getValue() : null;

		if(iaddress < 0 || iaddress > (2^64)) {
			error("Indirect address must be between 0 and 64 bits.", UdbPackage.Literals.MODEL__INDIRECT_ADDRESS);
		}
	}

	@Check
	public void checkBaseValue(Model m) {
		/* Ensure base value is either 32 or 64 */
		int base = m.getBase() != null ? m.getBase().getBase() : null;

		if (base != 32 && base != 64) {
			error("Base must have value of 32 or 64.", UdbPackage.Literals.MODEL__BASE);
		}
	}

	@Check
	public void checkLengthValue(Model m) {
		// Containment reference is always instantiated
		LengthType length_t = m.getLength().getLength();
		if (length_t == null) {
			error("length should not be null",
					UdbPackage.Literals.MODEL__LENGTH);
		}
		// If length is an integer, value is either 32 or 64
		if (length_t instanceof IntType) {
			Integer length = ((IntType) m.getLength().getLength()).getIntVal();
			if (length != 32 && length != 64) {
				error("length if specified as integer, should be 32 or 64",
						UdbPackage.Literals.MODEL__LENGTH);
			}
		}
//		if (length != null && length != "MXLEN" && length != "SXLEN" && length != "VSXLEN" && length != "XLEN") {
//			if (Integer.valueOf(length) != 32 && Integer.valueOf(length) != 64) {
//			error("Integer length value must be 32 or 64.", UdbPackage.Literals.MODEL__LENGTH);
//			}
//		}

	}

	@Check
	public void checkIndirectSlotValue(Model m) {
		/* Ensure indirect_slot is between 1 and 6 */
		int slot = m.getIndirectSlot() != null ? m.getIndirectSlot().getIndirectSlot() : null;

		if (slot < 1 || slot > 6) {
			error("Indirect slot value must be between 1 and 6.", UdbPackage.Literals.MODEL__INDIRECT_SLOT);
		}
	}

	@Check
	public void checkVirtualAddress(Model m) {
		String mode = m.getPrivmode() != null ? m.getPrivmode().getPrivMode().getType() : null;

		if (mode.equals("VS")) {
			if (m.getVirtualAddress() == null) {
				error("VS mode requires a virtual address.", UdbPackage.Literals.MODEL__PRIVMODE);
			}
		}

	}

}
