# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

# typed: true
# frozen_string_literal: true

UDB_GEN_ROOT = Pathname.new Kernel.__dir__
$root ||= UDB_GEN_ROOT

file "#{UDB_GEN_ROOT}/Gemfile.lock" do
  Dir.chdir(UDB_GEN_ROOT) do
    sh "bundle install --gemfile Gemfile"
  end
end

namespace :test do
  namespace :udb_gen do
    task :sorbet do
      Dir.chdir(UDB_GEN_ROOT) do
        Udb.logger.info "Type checking udb-gen gem"
        sh "bundle exec srb tc"
      end
    end
  end
end
