# REUSE.toml file for fonts in the PDF theme directory
# This file provides copyright and license information for all font files
# following the REUSE specification (https://reuse.software/)

version = 1

[[annotations]]
path = "cmunbt*.ttf"
SPDX-FileCopyrightText = "Copyright (C) 2003-2009, Andrey V. Panov (panov@canopus.iacp.dvo.ru)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "Montserrat*.ttf"
SPDX-FileCopyrightText = "Copyright 2024 The Montserrat.Git Project Authors (https://github.com/JulietaUla/Montserrat.git)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "mplus-*.ttf"
SPDX-FileCopyrightText = "Copyright 2021 The M+ FONTS Project Authors (https://github.com/coz-m/MPLUS_FONTS)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "Petrona*.ttf"
SPDX-FileCopyrightText = "Copyright 2019 The Petrona Project Authors (https://github.com/RingoSeeber/Petrona)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = "droid-sans-fallback.ttf"
SPDX-FileCopyrightText = "Copyright (C) 2008 Google Inc."
SPDX-License-Identifier = "Apache-2.0"
