#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Contributors to the RISCV UnifiedDB <https://github.com/riscv/riscv-unified-db>
# SPDX-License-Identifier: BSD-3-Clause-Clear
#MISE description="Regression task translated from regress-test-inst-encodings"

set -e

# Step 1: Checking for conflicts in instruction encodings
(
  ./do test:inst_encodings
)
