# SPDX-FileCopyrightText: 2026 Contributors to the RISCV UnifiedDB <https://github.com/riscv/riscv-unified-db>
# SPDX-License-Identifier: BSD-3-Clause-Clear

"""Spike/ACTs/Sail-compatible generic C encoding header."""

from collections.abc import Sequence

from .encoding_inputs import (
    EncodingGeneratorError,
    EncodingSource,
    ExceptionRecord,
    TargetArch,
    build_encoding_inputs,
    causes,
    identifier,
)
from .encoding_inputs import (
    exception_records as resolve_exception_records,
)

# These masks are the legacy public interface, not an instruction descriptor.
# The old loader discards variables before field extraction, so its header
# always exposes these common masks and no instruction-specific field macros.
_COMMON_FIELDS = {
    "opcode": (6, 0),
    "rd": (11, 7),
    "rs1": (19, 15),
    "rs2": (24, 20),
    "rs3": (31, 27),
    "funct3": (14, 12),
    "funct5": (31, 27),
    "funct7": (31, 25),
    "imm_i": (31, 20),
    "imm_s": (31, 25),
    "imm_b": (31, 25),
    "imm_u": (31, 12),
    "imm_j": (31, 12),
    "zimm": (19, 15),
    "pred": (27, 24),
    "succ": (23, 20),
    "rm": (14, 12),
    "csr": (31, 20),
}


def _legacy_name(name: str) -> str:
    return name[:-5] + "_rv32" if name.endswith(".rv32") else name


def generate_c_encoding(
    source: EncodingSource,
    *,
    extensions: str | Sequence[str] = (),
    include_all: bool = True,
    arch: TargetArch = "BOTH",
    exception_records: Sequence[ExceptionRecord] | None = None,
) -> str:
    """Render a generic header; defaults match the original Rake wrapper.

    ``arch`` additionally exposes the native loader's RV32/RV64 selection;
    the original C script always selected BOTH. Exception rows are independent
    of the instruction/CSR filter, matching the original all-code wrapper.
    """
    inputs = build_encoding_inputs(
        source, extensions=extensions, include_all=include_all, arch=arch
    )
    codes = causes(resolve_exception_records(source, exception_records))
    masks, instructions, csr_defines, csr_declarations, code_defines, code_declarations = (
        [],
        [],
        [],
        [],
        [],
        [],
    )
    names: set[str] = set()
    for encoding in sorted(inputs.instructions, key=lambda item: _legacy_name(item.name)):
        name = _legacy_name(encoding.name)
        c_name = identifier(name.replace(".", "_"), "C instruction identifier")
        if c_name.upper() in names:
            raise EncodingGeneratorError(f"C instruction identifier collision: {c_name}")
        names.add(c_name.upper())
        upper = c_name.upper()
        masks.append(
            f"#define MATCH_{upper} 0x{encoding.value:x}\n#define MASK_{upper} 0x{encoding.mask:x}\n"
        )
        instructions.append(f"DECLARE_INSN({c_name}, MATCH_{upper}, MASK_{upper})\n")
    csr_names: set[str] = set()
    for address, name in inputs.csrs:
        upper = identifier(name.replace(".", "_"), "C CSR identifier")
        if upper in csr_names:
            raise EncodingGeneratorError(f"C CSR identifier collision: {upper}")
        csr_names.add(upper)
        csr_defines.append(f"#define CSR_{upper} 0x{address:x}\n")
        csr_declarations.append(f"DECLARE_CSR({upper.lower()}, CSR_{upper})\n")
    for num, name in codes:
        code_defines.append(f"#define CAUSE_{name.upper()} 0x{num:x}\n")
        code_declarations.append(f'DECLARE_CAUSE("{name}", CAUSE_{name.upper()})\n')
    fields = []
    for name, (high, low) in sorted(_COMMON_FIELDS.items()):
        mask = ((1 << (high - low + 1)) - 1) << low
        fields.append(f"#define INSN_FIELD_{name.upper()} 0x{mask:x}  /* {high}-{low} */\n")
    return f"""/* SPDX-License-Identifier: BSD-3-Clause-Clear */
/* Copyright (c) 2023 RISC-V International */
/*
 * This file is auto-generated by riscv-unified-db
 */

#ifndef RISCV_ENCODING_H
#define RISCV_ENCODING_H
{"".join(masks)}
{"".join(csr_defines)}
{"".join(code_defines)}
{"".join(fields)}#endif
#ifdef DECLARE_INSN
{"".join(instructions)}#endif
#ifdef DECLARE_CSR
{"".join(csr_declarations)}#endif
#ifdef DECLARE_CAUSE
{"".join(code_declarations)}#endif
"""


if __name__ == "__main__":
    from .generic_cli import main

    raise SystemExit(main("c-encoding"))
