# SPDX-FileCopyrightText: 2026 Contributors to the RISCV UnifiedDB <https://github.com/riscv/riscv-unified-db>
# SPDX-License-Identifier: BSD-3-Clause-Clear

"""Deterministic C and SystemVerilog configuration headers."""

from __future__ import annotations

import re
from typing import Literal

from udb.architecture import ConfiguredArchitecture
from udb.configuration import ConfigurationKind
from udb.errors import DataError
from udb.versions import Version

type HeaderLanguage = Literal["c", "svh"]


class ConfigHeaderError(DataError):
    """The configuration cannot be represented by a valid header."""


def _sanitize(value: str) -> str:
    return re.sub("_+", "_", re.sub("[^A-Z0-9]", "_", value.upper())).strip("_")


def _integer(value: int, language: HeaderLanguage) -> str:
    if language == "c":
        return str(value)
    width = ((max(32, value.bit_length()) + 31) // 32) * 32
    return f"{width}'h{value:X}"


def generate_config_header(architecture: ConfiguredArchitecture, language: HeaderLanguage) -> str:
    """Return a validated full configuration's header, including its final newline.

    Extension versions and parameter values are explicit declarations, not
    values chosen from a solver model. Unsupported input raises ConfigHeaderError.
    """
    if language not in ("c", "svh"):
        raise ConfigHeaderError(f"Unsupported configuration header language {language!r}")
    configuration = architecture.configuration
    if configuration.kind is not ConfigurationKind.FULL:
        raise ConfigHeaderError(
            f"Config {configuration.name!r} is not fully configured. "
            "Only fully configured configs are supported."
        )
    if any(character in configuration.name for character in ("\r", "\n", "*/")):
        raise ConfigHeaderError("Configuration name cannot be represented in a header comment")
    check = architecture.check()
    if not check.valid:
        details = "; ".join(diagnostic.message for diagnostic in check.diagnostics)
        if check.conflict:
            details += "; " + "; ".join(check.conflict)
        raise ConfigHeaderError(
            f"Config {configuration.name!r} cannot generate a header: {check.status.value}"
            + (f": {details}" if details else "")
        )

    directive = "#define" if language == "c" else "`define"
    command = f"cfg-{language}-header"
    suffix = "_H" if language == "c" else "_SVH"
    guard = "UDB_CFG_" + re.sub("[^A-Z0-9]", "_", configuration.name.upper()) + suffix
    conventions = [
        "SPDX-License-Identifier: BSD-3-Clause-Clear",
        "",
        f"Auto-generated by riscv-unified-db (udb-gen {command})",
        f"Config: {configuration.name}",
        "",
        "Define conventions:",
        f"  Extensions:           {directive} NAME_SUPPORTED and {directive} NAMEverPver_SUPPORTED",
        (
            f"  Boolean params:       {directive} UDB_NAME           "
            "(present when true, absent when false)"
        ),
        f"  Integer params:       {directive} UDB_NAME value     and {directive} UDB_NAME_<value>",
        (
            f"  Enum (string) params: {directive} UDB_NAME_VALUE     "
            "(value sanitized to uppercase identifier)"
        ),
        f"  Boolean arrays:       {directive} UDB_NAME_<index>   (one per true element)",
        f"  Integer arrays:       {directive} UDB_NAME_<value>   (one per unique element, sorted)",
        (
            f"  String arrays:        {directive} UDB_NAME_<VALUE>   "
            "(one per unique element, sanitized)"
        ),
    ]
    if language == "c":
        lines = ["/*", *[" *" + (f" {line}" if line else "") for line in conventions], " */"]
        lines.extend(["", f"#ifndef {guard}"])
    else:
        lines = ["//" + (f" {line}" if line else "") for line in conventions]
        lines.extend(["", f"`ifndef {guard}"])
    emitted: set[str] = set()

    def emit(name: str, value: str | None = None) -> None:
        if re.fullmatch("[A-Za-z_][A-Za-z_0-9]*", name) is None:
            raise ConfigHeaderError(f"Unsupported macro identifier {name!r}")
        if name in emitted:
            raise ConfigHeaderError(f"Configuration header macro collision: {name}")
        emitted.add(name)
        lines.append(f"{directive} {name}" + (f" {value}" if value is not None else ""))

    def section(text: str) -> None:
        lines.extend(["", f"/* {text} */" if language == "c" else f"// {text}"])

    emit(guard)
    section("Implemented extensions")
    # Selection requirements normalize version spelling; use the preserved
    # declaration to retain Ruby's explicitly supplied component precision.
    extensions = configuration.to_dict()["implemented_extensions"]
    for selection in sorted(extensions, key=lambda item: item["name"].upper()):
        name = selection["name"]
        text = selection["version"].strip()
        version = Version.parse(text[1:].strip() if text.startswith("=") else text)
        architecture.database.extension(name).version(version)
        emit(f"{name.upper()}_SUPPORTED")
        emit(f"{name.upper()}{version.to_rvi().upper()}_SUPPORTED")

    section("Configuration parameters")
    for name, value in sorted(configuration.params.items()):
        prefixed = f"UDB_{name}"
        if re.fullmatch("[A-Za-z_][A-Za-z_0-9]*", prefixed) is None:
            raise ConfigHeaderError(f"Unsupported parameter macro identifier {prefixed!r}")
        if type(value) is bool:
            if value:
                emit(prefixed)
        elif type(value) is int:
            emit(prefixed, _integer(value, language))
            emit(f"{prefixed}_{value}")
        elif isinstance(value, str):
            emit(f"{prefixed}_{_sanitize(value)}")
        elif isinstance(value, tuple):
            if all(type(item) is bool for item in value):
                for index, item in enumerate(value):
                    if item:
                        emit(f"{prefixed}_{index}")
            elif all(type(item) is int for item in value):
                for item in sorted(set(value)):
                    emit(f"{prefixed}_{item}")
            elif all(isinstance(item, str) for item in value):
                for item in sorted({_sanitize(item) for item in value}):
                    emit(f"{prefixed}_{item}")
            else:
                raise ConfigHeaderError(
                    f"Parameter {name!r} has an unsupported heterogeneous array"
                )
        else:
            raise ConfigHeaderError(f"Parameter {name!r} has an unsupported value")

    lines.extend(["", f"#endif /* {guard} */" if language == "c" else f"`endif // {guard}", ""])
    return "\n".join(lines)
