# SPDX-FileCopyrightText: 2026 Contributors to the RISCV UnifiedDB <https://github.com/riscv/riscv-unified-db>
# SPDX-License-Identifier: BSD-3-Clause-Clear

"""SystemVerilog decode package, retaining 32-bit wildcard instruction masks."""

from collections.abc import Sequence

from .encoding_inputs import (
    EncodingGeneratorError,
    EncodingSource,
    ExceptionRecord,
    TargetArch,
    build_encoding_inputs,
    causes,
    identifier,
)
from .encoding_inputs import (
    exception_records as resolve_exception_records,
)


def generate_sv_decode(
    source: EncodingSource,
    *,
    package_name: str = "riscv_decode_package",
    extensions: str | Sequence[str] = (),
    include_all: bool = True,
    arch: TargetArch = "BOTH",
    exception_records: Sequence[ExceptionRecord] | None = None,
) -> str:
    """Return an SV package, with the original wrapper's all/BOTH defaults.

    The CLI derives package_name from the output basename, as the native script
    did; the library takes this output-dependent name explicitly.
    """
    identifier(package_name, "SystemVerilog package identifier")
    inputs = build_encoding_inputs(
        source, extensions=extensions, include_all=include_all, arch=arch
    )
    if any(address > 0xFFF for address, _ in inputs.csrs):
        raise EncodingGeneratorError("SystemVerilog CSR addresses must fit 12 bits")
    codes = causes(resolve_exception_records(source, exception_records))
    if any(num >= 64 for num, _ in codes):
        raise EncodingGeneratorError("SystemVerilog exception numbers must fit 6 bits")
    instructions = [
        (identifier(encoding.name.replace(".", "_").upper(), "SV instruction identifier"), encoding)
        for encoding in sorted(inputs.instructions, key=lambda item: item.name)
    ]
    csrs = [
        (address, identifier("CSR_" + name.replace(".", "_").upper(), "SV CSR identifier"))
        for address, name in inputs.csrs
    ]
    names = [name for name, _ in instructions] + [name for _, name in csrs]
    code_names = [
        (num, identifier("CAUSE_" + name.upper(), "SV exception identifier")) for num, name in codes
    ]
    all_names = names + [name for _, name in code_names]
    if len(set(all_names)) != len(all_names):
        raise EncodingGeneratorError("SystemVerilog parameter identifier collision")
    max_length = max((len(name) for name in names), default=0)
    max_cause = max((len(name) for _, name in code_names), default=0)
    lines = ["/* Automatically generated by UDB */\n", f"package {package_name};\n"]
    for name, encoding in instructions:
        match = encoding.match.replace("-", "?")
        if len(match) == 16:
            match = "?" * 16 + match
        elif len(match) != 32:
            raise EncodingGeneratorError(
                f"{encoding.name}: SystemVerilog decode needs a 16- or 32-bit encoding"
            )
        lines.append(f"  localparam logic [31:0] {name.ljust(max_length)} = 32'b{match};\n")
    for address, name in csrs:
        lines.append(f"  localparam logic [11:0] {name.ljust(max_length)} = 12'h{address:03x};\n")
    for num, name in code_names:
        lines.append(f"  localparam logic [5:0] {name.ljust(max_cause)} = 6'h{num:02x};\n")
    lines.append("\nendpackage\n")
    return "".join(lines)


if __name__ == "__main__":
    from .generic_cli import main

    raise SystemExit(main("sv-decode"))
