#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause-Clear
# Copyright (c) 2023 RISC-V International

import argparse
import logging
import os
import sys

# Add parent directory to path to import generator.py
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from generator import load_instructions_with_metadata, parse_match


def calculate_mask(match_str):
    """Convert the bit pattern string to a mask (1 for fixed bits, 0 for variable bits)."""
    return int("".join("0" if c == "-" else "1" for c in match_str), 2)


def generate_overlap_header(instr_dict, metadata_dict, output_file):
    overlaps = []

    names = sorted(instr_dict.keys())

    # Precompute match and mask values for all instructions
    precomputed = {}
    for name in names:
        match_str = instr_dict[name]["match"]
        precomputed[name] = {
            "match_str": match_str,
            "match_val": parse_match(match_str),
            "mask_val": calculate_mask(match_str),
            "exts": set(metadata_dict[name]["extensions"]),
        }

    for i in range(len(names)):
        name_a = names[i]
        a = precomputed[name_a]

        for j in range(i + 1, len(names)):
            name_b = names[j]
            b = precomputed[name_b]

            # Only compare encodings of the same width (e.g., 16b vs 16b, 32b vs 32b)
            if len(a["match_str"]) != len(b["match_str"]):
                continue

            # Check if instructions come from completely different extensions
            if a["exts"].isdisjoint(b["exts"]):
                # Overlap exists if all common fixed bits agree
                common_mask = a["mask_val"] & b["mask_val"]
                if ((a["match_val"] ^ b["match_val"]) & common_mask) == 0:
                    overlaps.append((name_a, sorted(a["exts"]), name_b, sorted(b["exts"])))

    # Format overlaps for output
    output_lines = [
        "/* SPDX-" + "License-Identifier: BSD-3-Clause-Clear */",
        "/* Copyright (c) 2023 RISC-V International */",
        "/*",
        " * This file is auto-generated by riscv-unified-db",
        " */",
        "",
        "// Overlapping instructions",
    ]

    declared = set()
    for name_a, exts_a, name_b, exts_b in overlaps:
        for ext in sorted(exts_a):
            # Handle instructions ending in _rv32
            base_name_a = name_a.replace(".", "_")
            if base_name_a.endswith("_rv32"):
                base_name_a = base_name_a[:-5]
            decl_a = f"DECLARE_OVERLAP_INSN({base_name_a}, EXT_{ext.upper()})"
            if decl_a not in declared:
                output_lines.append(decl_a)
                declared.add(decl_a)
        for ext in sorted(exts_b):
            base_name_b = name_b.replace(".", "_")
            if base_name_b.endswith("_rv32"):
                base_name_b = base_name_b[:-5]
            decl_b = f"DECLARE_OVERLAP_INSN({base_name_b}, EXT_{ext.upper()})"
            if decl_b not in declared:
                output_lines.append(decl_b)
                declared.add(decl_b)

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(output_lines) + "\n")

    logging.info(f"Generated {output_file} with {len(declared)} overlap declarations")


def parse_args():
    parser = argparse.ArgumentParser(description="Generate RISC-V overlap instructions header")
    parser.add_argument(
        "--inst-dir",
        default="../../../arch/inst/",
        help="Directory containing instruction YAML files",
    )
    parser.add_argument(
        "--output",
        default="overlap_list.out.h",
        help="Output filename (default: overlap_list.out.h)",
    )
    parser.add_argument(
        "--include-all",
        "-a",
        action="store_true",
        help="Include all instructions, ignoring extension filtering",
    )
    parser.add_argument("--debug", "-d", action="store_true", help="Enable debug logging")
    parser.add_argument(
        "--extensions",
        "-e",
        nargs="+",
        default=[],
        help="List of extensions to include",
    )
    parser.add_argument(
        "--arch",
        default="BOTH",
        choices=["RV32", "RV64", "BOTH"],
        help="Target architecture (RV32, RV64, or BOTH). Default is BOTH.",
    )

    return parser.parse_args()


def main():
    args = parse_args()

    if args.debug:
        logging.getLogger().setLevel(logging.DEBUG)

    # Load instructions
    logging.info(f"Loading instructions from {args.inst_dir}")
    instr_dict, metadata_dict = load_instructions_with_metadata(
        args.inst_dir, args.extensions, include_all=args.include_all, target_arch=args.arch
    )

    # Generate overlap list
    generate_overlap_header(instr_dict, metadata_dict, args.output)


if __name__ == "__main__":
    main()
