/*
 * generated by Xtext 2.39.0
 */
package org.riscv.idl.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class IdlProposalProvider extends AbstractIdlProposalProvider {
}
