#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Contributors to the RISCV UnifiedDB <https://github.com/riscv/riscv-unified-db>
# SPDX-License-Identifier: BSD-3-Clause-Clear
#MISE description="Regression task translated from regress-gen-ext-pdf"

set -e

# Step 1: Generate Xqci extension PDF
(
  ./python tools/scripts/gen_xqci.py
)
