#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Contributors to the RISCV UnifiedDB <https://github.com/riscv/riscv-unified-db>
# SPDX-License-Identifier: BSD-3-Clause-Clear
#MISE description="Regression task translated from regress-profile-strict-cfg"

set -e

# Step 1: Check that profile configs are up to date
(
  ./bin/chore gen -f profile-cfgs
)
