/*
 * generated by Xtext 2.39.0
 */
package org.xtext.example.udb.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.xtext.example.udb.udb.Model

@ExtendWith(InjectionExtension)
@InjectWith(UdbInjectorProvider)
class UdbParsingTest {
	@Inject
	ParseHelper<Model> parseHelper

	@Test
	def void parsesValidCSR() {
		val result = parseHelper.parse('''
			$schema: "csr_schema.json#"
			kind: csr
			name: vcsr
			long_name: "Vector Control and Status Register"
			address: 0x00F
			writable: true
			priv_mode: U
			length: MXLEN
			description: "Contains aliases to vxrm and vxsat CSRs"
			definedBy: "V"
			fields:
				VXRM:
					location: 2-1
					description: "See vxrm."
					type: RW-RH
					alias: vxrm.VALUE[1:0]
					sw_write(csr_value): "|
					  CSR[vxrm].VALUE = csr_value.VXRM;
					  return csr_value.VXRM;"
					reset_value: UNDEFINED_LEGAL
				VXSAT:
					location: 0
					description: "See vxsat."
					type: RW-RH
					alias: vxsat.VALUE[0]
					sw_write(csr_value): "|
					  CSR[vxsat].VALUE = csr_value.VXSAT;
					  return csr_value.VXSAT;"
					reset_value: UNDEFINED_LEGAL
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')


		// check basic inputs
		var schema = result.getSchema().getSchema();
		Assertions.assertEquals("csr_schema.json#", schema as String);
		var k = result.getKind().getKind().getType();
		Assertions.assertEquals("csr", k as String);
		var n = result.getCsrName().getName().getType();
		Assertions.assertEquals("vcsr", n as String);
		var ln = result.getLongName().getLongName();
		Assertions.assertEquals("Vector Control and Status Register", ln);
		var add = result.getAddress().getAddress().getValue();
		Assertions.assertEquals(0x00F, add);
		var writ = result.getWritable().isWritable();
		Assertions.assertTrue(writ);
		var priv = result.getPrivmode().getPrivMode().getType();
		Assertions.assertEquals("U", priv);
		var len = result.getLength().getLength().getParmType().getParmName();
		Assertions.assertEquals("MXLEN", len as String);
		var desc = result.getDescription().getDescription();
		Assertions.assertEquals("Contains aliases to vxrm and vxsat CSRs", desc);
		var def = result.getDefinedBy().getExtensionName();
		Assertions.assertEquals("V", def);

		// test fields
		var vxrm = result.getFields().getFields().get(0);
		var vxsat = result.getFields().getFields().get(1);
		Assertions.assertEquals("VXRM", vxrm.getName());
		Assertions.assertEquals("VXSAT", vxsat.getName());

		// test location
		var rmrange = vxrm.getLocation().getStaticLoc().getLocValue().getRange();
		var satloc = vxsat.getLocation().getStaticLoc().getLocValue().getValue();
		Assertions.assertEquals(2, rmrange.getUpper());
		Assertions.assertEquals(1, rmrange.getLower());
		Assertions.assertEquals(0, satloc);

		// test reset value
		var rmreset = vxrm.getResetValue().getValue().getResetValue().getUndefinedLegal();
		var satreset = vxsat.getResetValue().getValue().getResetValue().getUndefinedLegal();
		Assertions.assertEquals("UNDEFINED_LEGAL", rmreset as String);
		Assertions.assertEquals("UNDEFINED_LEGAL", satreset as String);

		// test IDL
		var rmsw = vxrm.getSwWriteFunc().getSwWriteFunc().getIdl();
		var satsw = vxsat.getSwWriteFunc().getSwWriteFunc().getIdl();
		Assertions.assertNotNull(rmsw)
		Assertions.assertNotNull(satsw)

		// testing description of fields
		var rmdesc = vxrm.getDescription().getDescription();
		var satdesc = vxsat.getDescription().getDescription();
		Assertions.assertEquals("See vxrm.", rmdesc);
		Assertions.assertEquals("See vxsat.", satdesc);

		// testing field type
		var rmtype = vxrm.getType().getTypeVal().getPerms();
		var sattype = vxsat.getType().getTypeVal().getPerms();
		Assertions.assertEquals("RW-RH", rmtype);
		Assertions.assertEquals("RW-RH", sattype);

		// testing alias
		var vxalias = vxrm.getAlias().getAlias().getAlias().get(0);
		var satalias = vxsat.getAlias().getAlias().getAlias().get(0);
		Assertions.assertEquals("vxrm.VALUE[1:0]", vxalias);
		Assertions.assertEquals("vxsat.VALUE[0]", satalias);


	}

}
