# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `terminal-table` gem.
# Please instead update this file by running `bin/tapioca gem terminal-table`.


# source://terminal-table//lib/terminal-table/cell.rb#3
module Terminal; end

# source://terminal-table//lib/terminal-table/cell.rb#4
class Terminal::Table
  # source://terminal-table//lib/terminal-table/table.rb#12
  def initialize(options = T.unsafe(nil), &block); end

  # source://terminal-table//lib/terminal-table/table.rb#39
  def <<(array); end

  # source://terminal-table//lib/terminal-table/table.rb#206
  def ==(other); end

  # source://terminal-table//lib/terminal-table/table.rb#39
  def add_row(array); end

  # source://terminal-table//lib/terminal-table/table.rb#49
  def add_separator(border_type: T.unsafe(nil)); end

  # source://terminal-table//lib/terminal-table/table.rb#29
  def align_column(n, alignment); end

  # source://terminal-table//lib/terminal-table/table.rb#57
  def cell_padding; end

  # source://terminal-table//lib/terminal-table/table.rb#53
  def cell_spacing; end

  # source://terminal-table//lib/terminal-table/table.rb#64
  def column(n, method = T.unsafe(nil), array = T.unsafe(nil)); end

  # source://terminal-table//lib/terminal-table/table.rb#96
  def column_width(n); end

  # source://terminal-table//lib/terminal-table/table.rb#82
  def column_with_headings(n, method = T.unsafe(nil)); end

  # source://terminal-table//lib/terminal-table/table.rb#89
  def columns; end

  # source://terminal-table//lib/terminal-table/table.rb#128
  def elaborate_rows; end

  # source://terminal-table//lib/terminal-table/table.rb#7
  def headings; end

  # source://terminal-table//lib/terminal-table/table.rb#111
  def headings=(arrays); end

  # source://terminal-table//lib/terminal-table/table.rb#96
  def length_of_column(n); end

  # source://terminal-table//lib/terminal-table/table.rb#104
  def number_of_columns; end

  # source://terminal-table//lib/terminal-table/table.rb#171
  def render; end

  # source://terminal-table//lib/terminal-table/table.rb#180
  def rows; end

  # source://terminal-table//lib/terminal-table/table.rb#184
  def rows=(array); end

  # source://terminal-table//lib/terminal-table/table.rb#193
  def style; end

  # source://terminal-table//lib/terminal-table/table.rb#189
  def style=(options); end

  # source://terminal-table//lib/terminal-table/table.rb#6
  def title; end

  # source://terminal-table//lib/terminal-table/table.rb#197
  def title=(title); end

  # source://terminal-table//lib/terminal-table/table.rb#171
  def to_s; end

  private

  # source://terminal-table//lib/terminal-table/table.rb#369
  def column_widths; end

  # source://terminal-table//lib/terminal-table/table.rb#214
  def columns_width; end

  # source://terminal-table//lib/terminal-table/table.rb#348
  def headings_with_rows; end

  # source://terminal-table//lib/terminal-table/table.rb#218
  def recalc_column_widths; end

  # source://terminal-table//lib/terminal-table/table.rb#365
  def require_column_widths_recalc; end

  # source://terminal-table//lib/terminal-table/table.rb#361
  def title_cell_options; end

  # source://terminal-table//lib/terminal-table/table.rb#352
  def yield_or_eval(&block); end
end

# source://terminal-table//lib/terminal-table/style.rb#39
class Terminal::Table::AsciiBorder < ::Terminal::Table::Border
  # source://terminal-table//lib/terminal-table/style.rb#44
  def initialize; end

  # source://terminal-table//lib/terminal-table/style.rb#57
  def horizontal(_type); end

  # source://terminal-table//lib/terminal-table/style.rb#51
  def vertical; end
end

# source://terminal-table//lib/terminal-table/style.rb#40
Terminal::Table::AsciiBorder::HORIZONTALS = T.let(T.unsafe(nil), Array)

# source://terminal-table//lib/terminal-table/style.rb#42
Terminal::Table::AsciiBorder::INTERSECTIONS = T.let(T.unsafe(nil), Array)

# source://terminal-table//lib/terminal-table/style.rb#41
Terminal::Table::AsciiBorder::VERTICALS = T.let(T.unsafe(nil), Array)

# source://terminal-table//lib/terminal-table/style.rb#7
class Terminal::Table::Border
  # source://terminal-table//lib/terminal-table/style.rb#10
  def initialize; end

  # source://terminal-table//lib/terminal-table/style.rb#16
  def [](key); end

  # source://terminal-table//lib/terminal-table/style.rb#13
  def []=(key, val); end

  # source://terminal-table//lib/terminal-table/style.rb#9
  def bottom; end

  # source://terminal-table//lib/terminal-table/style.rb#9
  def bottom=(_arg0); end

  # source://terminal-table//lib/terminal-table/style.rb#9
  def data; end

  # source://terminal-table//lib/terminal-table/style.rb#9
  def data=(_arg0); end

  # source://terminal-table//lib/terminal-table/style.rb#9
  def left; end

  # source://terminal-table//lib/terminal-table/style.rb#9
  def left=(_arg0); end

  # source://terminal-table//lib/terminal-table/style.rb#32
  def maybeleft(key); end

  # source://terminal-table//lib/terminal-table/style.rb#35
  def mayberight(key); end

  # source://terminal-table//lib/terminal-table/style.rb#27
  def remove_horizontals; end

  # source://terminal-table//lib/terminal-table/style.rb#23
  def remove_verticals; end

  # source://terminal-table//lib/terminal-table/style.rb#9
  def right; end

  # source://terminal-table//lib/terminal-table/style.rb#9
  def right=(_arg0); end

  # source://terminal-table//lib/terminal-table/style.rb#9
  def top; end

  # source://terminal-table//lib/terminal-table/style.rb#9
  def top=(_arg0); end

  private

  # source://terminal-table//lib/terminal-table/style.rb#19
  def initialize_dup(other); end
end

# source://terminal-table//lib/terminal-table/cell.rb#5
class Terminal::Table::Cell
  # source://terminal-table//lib/terminal-table/cell.rb#19
  def initialize(options = T.unsafe(nil)); end

  # source://terminal-table//lib/terminal-table/cell.rb#46
  def align(val, position, length); end

  # source://terminal-table//lib/terminal-table/cell.rb#33
  def alignment; end

  # source://terminal-table//lib/terminal-table/cell.rb#37
  def alignment=(val); end

  # source://terminal-table//lib/terminal-table/cell.rb#29
  def alignment?; end

  # source://terminal-table//lib/terminal-table/cell.rb#14
  def colspan; end

  # source://terminal-table//lib/terminal-table/cell.rb#85
  def inspect; end

  # source://terminal-table//lib/terminal-table/cell.rb#50
  def lines; end

  # source://terminal-table//lib/terminal-table/cell.rb#57
  def render(line = T.unsafe(nil)); end

  # source://terminal-table//lib/terminal-table/cell.rb#57
  def to_s(line = T.unsafe(nil)); end

  # source://terminal-table//lib/terminal-table/cell.rb#9
  def value; end

  # source://terminal-table//lib/terminal-table/cell.rb#70
  def value_for_column_width_recalc; end

  # source://terminal-table//lib/terminal-table/cell.rb#77
  def width; end
end

# source://terminal-table//lib/terminal-table/style.rb#63
class Terminal::Table::MarkdownBorder < ::Terminal::Table::AsciiBorder
  # source://terminal-table//lib/terminal-table/style.rb#64
  def initialize; end
end

# source://terminal-table//lib/terminal-table/row.rb#3
class Terminal::Table::Row
  # source://terminal-table//lib/terminal-table/row.rb#15
  def initialize(table, array = T.unsafe(nil), **_kwargs); end

  # source://terminal-table//lib/terminal-table/row.rb#22
  def <<(item); end

  # source://terminal-table//lib/terminal-table/row.rb#30
  def [](index); end

  # source://terminal-table//lib/terminal-table/row.rb#22
  def add_cell(item); end

  # source://terminal-table//lib/terminal-table/row.rb#8
  def cells; end

  # source://terminal-table//lib/terminal-table/row.rb#58
  def crossings; end

  # source://terminal-table//lib/terminal-table/row.rb#34
  def height; end

  # source://terminal-table//lib/terminal-table/row.rb#47
  def number_of_columns; end

  # source://terminal-table//lib/terminal-table/row.rb#38
  def render; end

  # source://terminal-table//lib/terminal-table/row.rb#10
  def table; end
end

# source://terminal-table//lib/terminal-table/separator.rb#3
class Terminal::Table::Separator < ::Terminal::Table::Row
  # source://terminal-table//lib/terminal-table/separator.rb#15
  def initialize(*args, border_type: T.unsafe(nil), implicit: T.unsafe(nil)); end

  # source://terminal-table//lib/terminal-table/separator.rb#22
  def border_type; end

  # source://terminal-table//lib/terminal-table/separator.rb#22
  def border_type=(_arg0); end

  # source://terminal-table//lib/terminal-table/separator.rb#23
  def implicit; end

  # source://terminal-table//lib/terminal-table/separator.rb#25
  def render; end

  # source://terminal-table//lib/terminal-table/separator.rb#59
  def save_adjacent_rows(prevrow, nextrow); end
end

# source://terminal-table//lib/terminal-table/style.rb#190
class Terminal::Table::Style
  extend ::Forwardable

  # source://terminal-table//lib/terminal-table/style.rb#248
  def initialize(options = T.unsafe(nil)); end

  # source://terminal-table//lib/terminal-table/style.rb#243
  def alignment; end

  # source://terminal-table//lib/terminal-table/style.rb#243
  def alignment=(_arg0); end

  # source://terminal-table//lib/terminal-table/style.rb#245
  def all_separators; end

  # source://terminal-table//lib/terminal-table/style.rb#245
  def all_separators=(_arg0); end

  # source://terminal-table//lib/terminal-table/style.rb#252
  def apply(options); end

  # source://terminal-table//lib/terminal-table/style.rb#210
  def border; end

  # source://terminal-table//lib/terminal-table/style.rb#211
  def border=(val); end

  # source://terminal-table//lib/terminal-table/style.rb#232
  def border_bottom; end

  # source://terminal-table//lib/terminal-table/style.rb#227
  def border_bottom=(val); end

  # source://terminal-table//lib/terminal-table/style.rb#205
  def border_i=(val); end

  # source://terminal-table//lib/terminal-table/style.rb#233
  def border_left; end

  # source://terminal-table//lib/terminal-table/style.rb#228
  def border_left=(val); end

  # source://terminal-table//lib/terminal-table/style.rb#234
  def border_right; end

  # source://terminal-table//lib/terminal-table/style.rb#229
  def border_right=(val); end

  # source://terminal-table//lib/terminal-table/style.rb#231
  def border_top; end

  # source://terminal-table//lib/terminal-table/style.rb#226
  def border_top=(val); end

  # source://terminal-table//lib/terminal-table/style.rb#203
  def border_x=(val); end

  # source://terminal-table//lib/terminal-table/style.rb#206
  def border_y; end

  # source://terminal-table//lib/terminal-table/style.rb#204
  def border_y=(val); end

  # source://terminal-table//lib/terminal-table/style.rb#207
  def border_y_width; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def horizontal(*args, **_arg1, &block); end

  # source://terminal-table//lib/terminal-table/style.rb#240
  def margin_left; end

  # source://terminal-table//lib/terminal-table/style.rb#240
  def margin_left=(_arg0); end

  # source://terminal-table//lib/terminal-table/style.rb#273
  def on_change(attr); end

  # source://terminal-table//lib/terminal-table/style.rb#237
  def padding_left; end

  # source://terminal-table//lib/terminal-table/style.rb#237
  def padding_left=(_arg0); end

  # source://terminal-table//lib/terminal-table/style.rb#238
  def padding_right; end

  # source://terminal-table//lib/terminal-table/style.rb#238
  def padding_right=(_arg0); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def remove_horizontals(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def remove_verticals(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def vertical(*args, **_arg1, &block); end

  # source://terminal-table//lib/terminal-table/style.rb#242
  def width; end

  # source://terminal-table//lib/terminal-table/style.rb#242
  def width=(_arg0); end

  class << self
    # source://terminal-table//lib/terminal-table/style.rb#259
    def defaults; end

    # source://terminal-table//lib/terminal-table/style.rb#267
    def defaults=(options); end
  end
end

# source://terminal-table//lib/terminal-table/table_helper.rb#3
module Terminal::Table::TableHelper
  # source://terminal-table//lib/terminal-table/table_helper.rb#4
  def table(headings = T.unsafe(nil), *rows, &block); end
end

# source://terminal-table//lib/terminal-table/style.rb#71
class Terminal::Table::UnicodeBorder < ::Terminal::Table::Border
  # source://terminal-table//lib/terminal-table/style.rb#89
  def initialize; end

  # source://terminal-table//lib/terminal-table/style.rb#112
  def horizontal(type); end

  # source://terminal-table//lib/terminal-table/style.rb#106
  def vertical; end
end

# source://terminal-table//lib/terminal-table/style.rb#73
Terminal::Table::UnicodeBorder::ALLOWED_SEPARATOR_BORDER_STYLES = T.let(T.unsafe(nil), Array)

# source://terminal-table//lib/terminal-table/style.rb#82
Terminal::Table::UnicodeBorder::HORIZONTALS = T.let(T.unsafe(nil), Array)

# source://terminal-table//lib/terminal-table/style.rb#84
Terminal::Table::UnicodeBorder::INTERSECTIONS = T.let(T.unsafe(nil), Array)

# source://terminal-table//lib/terminal-table/style.rb#83
Terminal::Table::UnicodeBorder::VERTICALS = T.let(T.unsafe(nil), Array)

# source://terminal-table//lib/terminal-table/style.rb#143
class Terminal::Table::UnicodeRoundBorder < ::Terminal::Table::UnicodeBorder
  # source://terminal-table//lib/terminal-table/style.rb#144
  def initialize; end
end

# source://terminal-table//lib/terminal-table/style.rb#151
class Terminal::Table::UnicodeThickEdgeBorder < ::Terminal::Table::UnicodeBorder
  # source://terminal-table//lib/terminal-table/style.rb#152
  def initialize; end
end

# source://terminal-table//lib/terminal-table/util.rb#3
module Terminal::Table::Util
  private

  # source://terminal-table//lib/terminal-table/util.rb#5
  def ansi_escape(line); end

  class << self
    # source://terminal-table//lib/terminal-table/util.rb#5
    def ansi_escape(line); end
  end
end

# source://terminal-table//lib/terminal-table/version.rb#3
Terminal::Table::VERSION = T.let(T.unsafe(nil), String)
