# SPDX-FileCopyrightText: 2026 Contributors to the RISCV UnifiedDB <https://github.com/riscv/riscv-unified-db>
# SPDX-License-Identifier: BSD-3-Clause-Clear

from __future__ import annotations

import argparse
import json
import os
import shlex
import subprocess
from dataclasses import asdict, dataclass

from .common import ROOT, DevError, entrypoint, python_command, udb_command


@dataclass(frozen=True)
class Fixture:
    name: str
    refreshable: bool
    detail: str


REGISTRY = {
    "config-headers": Fixture(
        "config-headers", True, "generated by the installed Python config-header generators"
    ),
    "extension-documents": Fixture(
        "extension-documents", False, "frozen: the source manifest requires Ruby oracle captures"
    ),
    "generic-codegen": Fixture(
        "generic-codegen", True, "Python matrix capture over frozen resolved inputs"
    ),
    "instruction-table": Fixture(
        "instruction-table", False, "frozen: refresh requires the Ruby instruction-table oracle"
    ),
    "query-reports": Fixture(
        "query-reports", False, "frozen: refresh scripts are Ruby native captures"
    ),
    "schema-docs": Fixture("schema-docs", False, "frozen: ordering and Psych captures invoke Ruby"),
}


def list_fixtures(output_format: str) -> int:
    fixtures = [asdict(entry) for entry in REGISTRY.values()]
    if output_format == "json":
        print(json.dumps(fixtures, indent=2, sort_keys=True))
    else:
        for entry in REGISTRY.values():
            state = "refreshable" if entry.refreshable else "frozen"
            print(f"{entry.name}: {state} — {entry.detail}")
    return 0


def commands_for(name: str, *, check: bool) -> list[list[str]]:
    if name == "config-headers":
        config = str(ROOT / "cfgs/mc100-32-full-example.yaml")
        commands = [
            udb_command(
                "generate",
                "config-c-header",
                "-c",
                config,
                "-o",
                str(ROOT / "tests/golden/mc100-32-full-example.golden.h"),
            ),
            udb_command(
                "generate",
                "config-sv-header",
                "-c",
                config,
                "-o",
                str(ROOT / "tests/golden/mc100-32-full-example.golden.svh"),
            ),
        ]
        if check:
            for command in commands:
                command.append("--check")
        return commands
    if name == "generic-codegen":
        if check:
            return [
                python_command(
                    "-m",
                    "pytest",
                    "-q",
                    "tests/python/test_generic_codegen.py",
                    "-k",
                    "fixture",
                )
            ]
        return [python_command(str(ROOT / "tests/python/regenerate_generic_codegen.py"))]
    raise DevError(REGISTRY[name].detail, 2)


def refresh(names: list[str], *, check: bool) -> int:
    unknown = [name for name in names if name not in REGISTRY]
    if unknown:
        raise DevError(f"unknown fixture(s): {', '.join(unknown)}", 2)
    for name in names:
        fixture = REGISTRY[name]
        if not fixture.refreshable:
            print(f"{name}: {fixture.detail}")
            continue
        for command in commands_for(name, check=check):
            status = subprocess.run(command, cwd=ROOT, check=False).returncode
            if status:
                return status
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    commands = parser.add_subparsers(dest="command", required=True)
    listing = commands.add_parser("list")
    listing.add_argument(
        "--format",
        choices=("text", "json"),
        default=os.environ.get("usage_format", "text"),
    )
    refresh_parser = commands.add_parser("refresh")
    refresh_parser.add_argument("names", nargs="*")
    refresh_parser.add_argument("--all", action="store_true")
    refresh_parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    if args.command == "list":
        return list_fixtures(args.format)
    names = args.names or shlex.split(os.environ.get("usage_names", ""))
    all_fixtures = args.all or os.environ.get("usage_all") == "true"
    check = args.check or os.environ.get("usage_check") == "true"
    if bool(names) == all_fixtures:
        raise DevError("choose fixture names or --all", 2)
    return refresh(list(REGISTRY) if all_fixtures else names, check=check)


if __name__ == "__main__":
    raise SystemExit(entrypoint(main))
