# Minimal Codex TOML snippet to register the RISC-V gen MCP server

[mcp_servers.riscv_gen]
command = "/home/afonsoo/riscv-unified-db/.venv_mcp/bin/python3"
args = ["tools/mcp_gen_server/server.py"]
cwd = "/home/afonsoo/riscv-unified-db"
startup_timeout_ms = 20000

  [mcp_servers.riscv_gen.env]
  PYTHONUNBUFFERED = "1"

# Usage:
# - If Codex supports a single config file, merge this block into your main TOML.
# - Or point Codex to this file if it supports loading an additional config.
# - Ensure the venv path matches your system and that the venv has `mcp` + `pyyaml` installed.
