#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Contributors to the RISCV UnifiedDB <https://github.com/riscv/riscv-unified-db>
# SPDX-License-Identifier: BSD-3-Clause-Clear
#MISE description="Regression task translated from regress-build-udb-gem"

set -e

# Step 1: Build udb gem via chore
(
  ./bin/chore build udb-gem
)

# Step 2: Verify udb gem was built
(
  ls gen/udb_gem/udb-*.gem
)
