#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Contributors to the RISCV UnifiedDB <https://github.com/riscv/riscv-unified-db>
# SPDX-License-Identifier: BSD-3-Clause-Clear
#MISE description="Regression task translated from check-gem-versions"

set -e

# Step 1: Check gem versions, pins, and lock files are up to date
(
  ./bin/chore gen -f gem-versions
)

# Step 2: Check lockfiles have no drift after re-locking
(
  git diff --exit-code -- \
    Gemfile.lock \
    tools/ruby-gems/idlc/Gemfile.lock \
    tools/ruby-gems/udb/Gemfile.lock \
    tools/ruby-gems/udb-gen/Gemfile.lock \
    tools/ruby-gems/udb_helpers/Gemfile.lock
)
