/*
 * generated by Xtext 2.40.0
 */
package org.xtext.example.udb.parser.antlr;

import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;
import org.xtext.example.udb.parser.antlr.internal.InternalUdbParser;

public class UdbTokenSource extends AbstractIndentationTokenSource {

	public UdbTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		// TODO Review assumption
		return token.getType() == InternalUdbParser.RULE_WS;
	}

	@Override
	protected int getBeginTokenType() {
		// TODO Review assumption
		return InternalUdbParser.RULE_INDENT;
	}

	@Override
	protected int getEndTokenType() {
		// TODO Review assumption
		return InternalUdbParser.RULE_DEDENT;
	}

}
