// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: CC-BY-4.0

= Architecture Specification

RISC-V is a highly configurable standard. Numerous unnamed implementation options exist, and
the presence/absence of hundreds of named optional extensions alter the behavior of the
architecture. Additionally, implementations are free to add custom, non-standard extensions
on top of those ratified by https://riscv.org[RISC-V International (RVI)]. As a result, two
equally valid implementations of RISC-V can have wildly different specifications.

This makes creating and maintaining generic RISC-V specifications a daunting task.
A few challenging issues that arise include:

 * The RISC-V standard actually specifies two different architectures, namely RV32 and RV64.
 * The presence/absence of standard instructions and CSRs is affected by both unnamed implementation options (_e.g._, the number of implemented PMP registers) and named extensions.
 * The behavior of architecturally-visible state is dependent on the set of implemented extensions. For example, the legal values of `satp.MODE` depend on whether or not the `Sv32`, `Sv39`, `Sv48`, and/or `Sv57` extensions are implemented.

To tame this challenge, this specification generator takes the following approach:

 * The RVI standard architecture (in the `arch/` folder) is described in a way that covers all implementation options. As much as possible, the architecture is defined in a structured way that can be easily parsed using any programming language with a https://en.wikipedia.org/wiki/YAML[YAML] library. Complex behavior (_e.g._, instruction operation) and some configuration-dependent metadata is specified in an architecture definition language (xref:prose/idl.adoc[IDL]) that can formally define the architecture in arbitrary ways.
 * An implementation of RISC-V is specified as a _configuration_ containing all unnamed parameters and list of named supported extensions (in the `cfgs/` folder).
 * A tool, included in this repository, can generate an implmentation-specific specification by applying the configuration to the generic spec. Behaviors that are not relevant are left out, and behaviors that are affected by multiple extensions are merged into a single description.

Three standard configs are present:

 * `_`: A completely _unconfigured_ configuration, i.e., where there are no restrictions and no known parameter values.
 * `rv32`: A configuration where only `MXLEN` is known to be 32, i.e., the RV32 ISA.
 * `rv64`: A configuration where only `MXLEN` is known to be 64, i.e., the RV64 ISA.

The architecture is specified in a series of https://en.wikipedia.org/wiki/YAML[YAML]
files for _Extensions_, _Instructions_, _RegFiles_, and _Control and Status Registers (CSRs)_.
Each extension/instruction/regfile/CSR has its own file.

== Flow

[ditaa]
....
+--------------------------------------------------------------------------+
| AbstractConfig (cfgs/NAME)                                                       |
| +------------------------------+ +-----------------------------------+   |
| | AbstractConfig (extensions & params) | | Implementation Overlay [optional] |   |
| | (cfgs/NAME/cfg.yaml)         | | (cfgs/NAME/arch_overlay/*.yaml)   |   |
| +------------------------------+ +-----------------------------------+   |
+--------|------------------------------------------------------|----------+
         |                                                      |
         |                     +----------------+               v
         |                     |{s} Standard    |    /--------------------\
         |                     |    Arch Spec   |--->|  JSON Merge Patch  |
         |                     | (arch)         |    |  RFC 7386          |
         |                     +----------------+    \--------------------/
         |                                                      |
         |                                                      v
         |                                        +--------------------------+
         |                                        | {s} Merged Arch Spec     |
         |                                        | (gen/arch/NAME/*.yaml)   |
         |                                        +--------------------------+
         |                                                      |
         |                                                      v
         |                                           /---------------------\
         |                                           |  Resolve Operators  |
         |                                           | ($inherits/$remove) |
         |                                           \---------------------/
         |                                                      |
         |                                                      v
         |                                     +---------------------------------+
         |                                     | {s} Implementation-specific     |
         |                                     |     Architecture Spec            |
         |                                     | (gen/resolved_arch/NAME/*.yaml) |
         |                                     +---------------------------------+
         |                                                 |
  +------|-------------------------------------------------|---------+
  |      |           Ruby Interface                        |         |
  |   /--------\                                           |         |
  |   | AbstractConfig |                                           |         |
  |   \--------/   /---------------\                       |         |
  |       |      +-| Architecture  |<----------------------+         |
  |       |      | \---------------/                                 |
  |       |      |                                                   |
  |       v      v                                                   |
  | /------------------------\                                       |
  | | ConfiguredArchitecture |                                       |
  | \------------------------/                                       |
  +------------------------------------------------------------------+
....

The final architecture files go through two transformation steps. First, config overlay files, if present,
are merged on top of the standard architecture files according to JSON Merge Patch. This step is where
any custom behavior can be added to the specification. Second, the (possibly) merged files are _resolved_
by implementing the database operators `$inherits` and `$remove`.

The `ConfiguredArchitecture` class represents a configured view of the database, and is the basis
of most queries about a config.

== Data Format

All specification data is written in YAML. The data for Extensions, Instructions, and CSRs follow
their own schemas, documented below. The files are checked for validity using
https://json-schema.org/[Json Schema], and the precise schemas are located in the `schemas/` directory.

=== Extensions

.Example extension specification
[source,yaml]
----
H: # <1>
  type: privileged # <2>
  versions: # <3>
  - version: 1.0
    ratification_date: 2019-12
    requires: [S, '>= 1.12'] # <4>
  interrupt_codes: # <5>
  - num: 2
    name: Virtual supervisor software interrupt
  - num: 6
    name: Virtual supervisor timer interrupt
  - num: 10
    name: Virtual supervisor external interrupt
  - num: 12
    name: Supervisor guest external interrupt
  exception_codes: # <6>
  - num: 10
    name: Environment call from VS-mode
  - num: 20
    name: Instruction guest page fault
  - num: 21
    name: Load guest page fault
  - num: 22
    name: Virtual instruction
  - num: 23
    name: Store/AMO guest page fault
  description: | # <7>
    An Asciidoc description... <6>
----
<1> Name of the extension, which must follow the https://wiki.riscv.org/display/CSC/Extension+Naming+Convention[RVI naming scheme].
<2> Extension type: privileged or unprivileged
<3> List of versions
<4> [Optional] Declares a dependency on another extension (may be a list if there is more than one dependency).
<5> [Optional] List of asynchronous interrupts added by this extension
<6> [Optional] List of synchronous exceptions added by this extension
<7> A description of the extension, as Asciidoc source

=== Instructions

=== Register Files

.Example register file specification
[source,yaml]
----
$schema: register_file_schema.json#
kind: register_file
name: X
long_name: Integer General Purpose Registers
definedBy: I
register_class: general_purpose
register_length: MXLEN # <1>
registers:
  - name: x0    # <2>
    abi_mnemonics: [zero] # <3>
    roles: [zero]
    sw_read(): | # <4>
      return 0;
    sw_write(value): |
      # x0 ignores all writes
  - name: x1
    abi_mnemonics: [ra]
    roles: [return_address]
  - name: x8
    abi_mnemonics: [s0, fp] # <5>
    roles: [callee_saved, frame_pointer]
----

<1> Registers can have either a fixed architecture width or take their width from a parameter (e.g., MXLEN, VLEN).
<2> Each register has a unique name (e.g., x0, x1, x2, etc.). The register's index is inferred from its position in the array (starting from 0).
<3> Registers can optionally have ABI mnemonics (e.g., ra, sp, fp, etc.).
<4> Individual registers can define `sw_read()` and `sw_write()` for special behavior (e.g., x0 hardwired to zero).
<5> A register can have multiple ABI mnemonics (e.g., x8 is known as both s0 and fp).

[source,yaml]
----
add: # <1>
  long_name: Add
  description: | # <2>
    Add the value in rs1 to rs2, and store the result in rd.
    Any overflow is thrown away.
  encoding: # <3>
    mask: 0000000----------000-----0110011
    fields:
    - name: rs2
      location: 24-20
    - name: rs1
      location: 19-15
    - name: rd
      location: 11-7
  definedBy: I # <4>
  assembly: xd, xs1, xs2 # <5>
  access: # <6>
    s: always
    u: always
    vs: always
    vu: always
  operation(): X[rd] = X[rs1] + X[rs2]; # <7>
----
<1> The instruction mnemonic, in lowercase
<2> Asciidoc description of the instruction
<3> Encoding of the instruction. 'mask' specifies the values and position of opcode fields, and 'fields' specifies the locations of decode variables.
<4> Extension that defines this instruction. May be a list if the instruction is defined by multiple extensions.
<5> Assembly format, to be used by ISS/disassembler/compiler/etc.
<6> Per-mode access rights (always, sometimes, or none). When 'sometimes', a field 'access-detail' should also be provided.
<7> Formal definition of the instruction operation, in IDL

Some instructions have decode fields that cannot take a certain value. This is especially common in the `C` extension where, for example, some register specifier fields can be anything but x0. That can be represented by adding a `not_mask` key to the encoding:

.encoding for `c.addi`
[source,yaml]
----
encoding:
  mask:     000-----------01
  not_mask: ----00000------- # rs1/rd cannot be 0
  fields:
  - name: imm
    location: 12|6-2
  - name: rs1_rd
    location: 11-7
----

Not mask can also be a list when more than one value is prohibited (_e.g._, `c.lui` prohibits both x0 and x2 for `rd`).

Some fields are shifted before use, and can be represented using the `left_shift` key:

.encoding for `jal`
[source,yaml]
----
  encoding:
    mask: -------------------------1101111
    fields:
    - name: imm
      # lsb of the immediate is always zero, so it isn't encoded in the instruction
      # this is also an example of representing decode variables that are split in the
      # encoding
      location: 31|19-12|20|30-21
      left_shift: 1
    - name: rd
      location: 11-7
----

=== CSRs

.CSR specification for `marchid`
[source,yaml]
----
marchid: # <1>
  long_name: Machine Architecture ID
  address: 0xf12 # <2>
  priv_mode: M # <3>
  length: MXLEN # <4>
  description: | # <5>
    Asciidoc description
  definedBy: Sm # <6>
  fields: # <7>
    Architecture:
      location_rv32: 31-0 # <8>
      location_rv64: 63-0
      type: RO # <7>
      description: Vendor-specific microarchitecture ID. # <9>
      reset_value(): return ARCH_ID; # <10>
----
<1> CSR name
<2> CSR address (used by CSRs that not indirect)
<3> Least-privileged mode required to access the CSR
<4> Length of the CSR, in bits. Can either be an integer (_e.g._ 32, 64), or 'MXLEN', 'SXLEN', or 'VSXLEN' when the length is equal to the XLEN in M, S, or VS mode, respectively.
<5> Asciidoc description
<6> Defining extension. Can be list when more than one extension defines the CSR.
<7> List of fields in the CSR
<8> Location. In this case, the location changes with XLEN, so `location_rv32` and `location_rv64` are used. When the location does not change, use the single key `location`.
<9> Type of the field. See below for more information.
<10> Reset value. In this case, the reset value is determined by the configuration, so it is specified as an IDL function.

CSR fields are given a type, which _does not_ necessarily correspond to the WARL/WLRL types in the RVI specs. We use a different format here because the RVI CSR types are vauge and inconsistent. The types are:

[cols="1,4"]
|===
| Type | Meaning

| *RO* | Read-only
| *RO-H* | Read-only, and hardware updates the field
| *RW* | Read-write
| *RW-R* | Read-write, but only a restricted set of values are allowed
| *RW-H* | Read-write, and hardware updates the field
| *RW-RH* | Read-write, only a restricted set of values are allowed, and hardware updates the field
|===

In many cases, the values of CSR and/or CSR field data are configuration dependent. Some of that is covered directly by the data model (_e.g._, with `location_rv32`, `location_rv64`), but some cases are too complex to express with YAML. For this reason, many of the keys can be specified as IDL functions. See the xref:csr/schema.adoc[schema] documentation and examples in the `arch/csr` folder for more information.

Some keys that only apply to certain CSRs are not shown above.
