# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::DateAndTime::Calculations; end
module ::DateAndTime::Zones; end
module ActiveSupport::ArrayInquirer; end
module ActiveSupport::Multibyte::Chars; end
module ActiveSupport::SafeBuffer; end
module ActiveSupport::StringInquirer; end
module ActiveSupport::TimeZone; end
module Idl::AstNode::ValueRbType; end
module Idl::Compiler::IdlParser; end
module Idl::Type::CppHartGen::TemplateEnv; end
module T::Integer; end
module Udb::Csr; end
module Udb::Extension; end
module Udb::Instruction; end
module Udb::Manual; end
module Udb::ManualVersion; end
module Udb::ProcCertClass; end
module Udb::ProcCertModel; end
module Udb::Profile; end
module Udb::ProfileClass; end
module Udb::ProfileRelease; end
