#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Contributors to the RISCV UnifiedDB <https://github.com/riscv/riscv-unified-db>
# SPDX-License-Identifier: BSD-3-Clause-Clear
#MISE description="Regression task translated from build-docs-site"

set -e

# Step 1: Build Docusaurus site
(
  ./bin/aubr -C doc --frozen-lockfile build
)
