#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Contributors to the RISCV UnifiedDB <https://github.com/riscv/riscv-unified-db>
# SPDX-License-Identifier: BSD-3-Clause-Clear
#MISE description="Regression task translated from build-udb-api-docs"

set -e

# Step 1: Generate UDB API Docs
(
  ./do gen:udb:api_doc
)
