/*
 * generated by Xtext 2.39.0
 */
package org.riscv.idl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.riscv.idl.IdlRuntimeModule;
import org.riscv.idl.IdlStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class IdlIdeSetup extends IdlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new IdlRuntimeModule(), new IdlIdeModule()));
	}

}
