/*
 * generated by Xtext 2.40.0
 */
package org.xtext.clinic;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RiscvRuntimeModule extends AbstractRiscvRuntimeModule {
}
