/*
 * generated by Xtext 2.39.0
 */
package org.xtext.udb.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class UdbWebModule extends AbstractUdbWebModule {
}
