/*
 * generated by Xtext 2.39.0
 */
package org.xtext.udb.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.udb.UdbRuntimeModule;
import org.xtext.udb.UdbStandaloneSetup;
import org.xtext.udb.ide.UdbIdeModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class UdbWebSetup extends UdbStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new UdbRuntimeModule(), new UdbIdeModule(), new UdbWebModule()));
	}
	
}
