/*
 * generated by Xtext 2.40.0
 */
package org.xtext.clinic.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class RiscvScopeProvider extends AbstractRiscvScopeProvider {

}
