name: Container Img Weekly Build and Release

on:
  schedule:
    # This will run every week at 00:00 UTC on Monday
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    name: Container Img Weekly Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the current date
        id: current_date
        run: echo "name=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./infrastructure/base-container-img
          platforms: linux/amd64,linux/arm64
          tags: |
            riscvintl/udb:${{ github.sha }}
            riscvintl/udb:latest
          push: ${{ github.event_name != 'pull_request' }}

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"
